// Package v1alpha1 contains the tunnels.cloudflare.flare.dev API group (x-fern-sdk-group-name
// "tunnels"): Tunnel, a remotely managed Cloudflare Tunnel (cfd_tunnel) together with the
// cloudflared connector Deployment, its token Secret and an egress NetworkPolicy.
//
// These types are hand-written (not generated by cmd/flaregen); `make generate manifests`
// (controller-gen) produces their deepcopy methods and CRD.
//
// +kubebuilder:object:generate=true
// +groupName=tunnels.cloudflare.flare.dev
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

var (
	// GroupVersion is the group version used to register these objects.
	GroupVersion = schema.GroupVersion{Group: "tunnels.cloudflare.flare.dev", Version: "v1alpha1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme.
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)
