// Package v1alpha1 contains kinds of the flare.dev API group (x-fern-sdk-group-name
// "pages" of /accounts/{account_id}/pages/projects): PagesProject, a Cloudflare Pages project
// with its build and deployment settings, and PagesDeployment, one Direct Upload deployment of
// an artifact to a project.
//
// Cloudflare recommends Workers static assets for new projects
// (https://developers.cloudflare.com/workers/static-assets/migration-guides/migrate-from-pages/);
// these kinds exist for sites that are on Pages.
//
// These types are hand-written (not generated by cmd/flaregen); `make generate manifests`
// (controller-gen) produces their deepcopy methods and CRDs.
//
// +kubebuilder:object:generate=true
// +groupName=flare.dev
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	// GroupVersion is the group version used to register these objects.
	GroupVersion = schema.GroupVersion{Group: "flare.dev", Version: "v1alpha1"}

	// SchemeBuilder registers this package's kinds (apimachinery's runtime.SchemeBuilder, as in
	// the other API packages).
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

func addKnownTypes(s *runtime.Scheme) error {
	s.AddKnownTypes(GroupVersion, &PagesProject{}, &PagesProjectList{}, &PagesDeployment{}, &PagesDeploymentList{})
	metav1.AddToGroupVersion(s, GroupVersion)
	return nil
}
