//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
	sharedv1alpha1 "flare.dev/operator/api/shared/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesBuildConfig) DeepCopyInto(out *PagesBuildConfig) {
	*out = *in
	if in.BuildCaching != nil {
		in, out := &in.BuildCaching, &out.BuildCaching
		*out = new(bool)
		**out = **in
	}
	if in.BuildCommand != nil {
		in, out := &in.BuildCommand, &out.BuildCommand
		*out = new(string)
		**out = **in
	}
	if in.DestinationDir != nil {
		in, out := &in.DestinationDir, &out.DestinationDir
		*out = new(string)
		**out = **in
	}
	if in.RootDir != nil {
		in, out := &in.RootDir, &out.RootDir
		*out = new(string)
		**out = **in
	}
	if in.WebAnalyticsTag != nil {
		in, out := &in.WebAnalyticsTag, &out.WebAnalyticsTag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesBuildConfig.
func (in *PagesBuildConfig) DeepCopy() *PagesBuildConfig {
	if in == nil {
		return nil
	}
	out := new(PagesBuildConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesD1Binding) DeepCopyInto(out *PagesD1Binding) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.D1DatabaseRef != nil {
		in, out := &in.D1DatabaseRef, &out.D1DatabaseRef
		*out = new(commonv1alpha1.LocalRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesD1Binding.
func (in *PagesD1Binding) DeepCopy() *PagesD1Binding {
	if in == nil {
		return nil
	}
	out := new(PagesD1Binding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesDeployment) DeepCopyInto(out *PagesDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesDeployment.
func (in *PagesDeployment) DeepCopy() *PagesDeployment {
	if in == nil {
		return nil
	}
	out := new(PagesDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PagesDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesDeploymentConfig) DeepCopyInto(out *PagesDeploymentConfig) {
	*out = *in
	if in.CompatibilityFlags != nil {
		in, out := &in.CompatibilityFlags, &out.CompatibilityFlags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AlwaysUseLatestCompatibilityDate != nil {
		in, out := &in.AlwaysUseLatestCompatibilityDate, &out.AlwaysUseLatestCompatibilityDate
		*out = new(bool)
		**out = **in
	}
	if in.FailOpen != nil {
		in, out := &in.FailOpen, &out.FailOpen
		*out = new(bool)
		**out = **in
	}
	if in.BuildImageMajorVersion != nil {
		in, out := &in.BuildImageMajorVersion, &out.BuildImageMajorVersion
		*out = new(int32)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PagesPlacement)
		**out = **in
	}
	if in.EnvVars != nil {
		in, out := &in.EnvVars, &out.EnvVars
		*out = make([]PagesEnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KVNamespaces != nil {
		in, out := &in.KVNamespaces, &out.KVNamespaces
		*out = make([]PagesKVBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.D1Databases != nil {
		in, out := &in.D1Databases, &out.D1Databases
		*out = make([]PagesD1Binding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.R2Buckets != nil {
		in, out := &in.R2Buckets, &out.R2Buckets
		*out = make([]PagesR2Binding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QueueProducers != nil {
		in, out := &in.QueueProducers, &out.QueueProducers
		*out = make([]PagesQueueBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]PagesServiceBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesDeploymentConfig.
func (in *PagesDeploymentConfig) DeepCopy() *PagesDeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(PagesDeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesDeploymentConfigs) DeepCopyInto(out *PagesDeploymentConfigs) {
	*out = *in
	if in.Production != nil {
		in, out := &in.Production, &out.Production
		*out = new(PagesDeploymentConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Preview != nil {
		in, out := &in.Preview, &out.Preview
		*out = new(PagesDeploymentConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesDeploymentConfigs.
func (in *PagesDeploymentConfigs) DeepCopy() *PagesDeploymentConfigs {
	if in == nil {
		return nil
	}
	out := new(PagesDeploymentConfigs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesDeploymentList) DeepCopyInto(out *PagesDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PagesDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesDeploymentList.
func (in *PagesDeploymentList) DeepCopy() *PagesDeploymentList {
	if in == nil {
		return nil
	}
	out := new(PagesDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PagesDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesDeploymentObservation) DeepCopyInto(out *PagesDeploymentObservation) {
	*out = *in
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LatestStage != nil {
		in, out := &in.LatestStage, &out.LatestStage
		*out = new(PagesStageObservation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesDeploymentObservation.
func (in *PagesDeploymentObservation) DeepCopy() *PagesDeploymentObservation {
	if in == nil {
		return nil
	}
	out := new(PagesDeploymentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesDeploymentParameters) DeepCopyInto(out *PagesDeploymentParameters) {
	*out = *in
	out.ProjectRef = in.ProjectRef
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(sharedv1alpha1.ArtifactSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesDeploymentParameters.
func (in *PagesDeploymentParameters) DeepCopy() *PagesDeploymentParameters {
	if in == nil {
		return nil
	}
	out := new(PagesDeploymentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesDeploymentSpec) DeepCopyInto(out *PagesDeploymentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesDeploymentSpec.
func (in *PagesDeploymentSpec) DeepCopy() *PagesDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(PagesDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesDeploymentStatus) DeepCopyInto(out *PagesDeploymentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(sharedv1alpha1.ArtifactStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesDeploymentStatus.
func (in *PagesDeploymentStatus) DeepCopy() *PagesDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(PagesDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesEnvVar) DeepCopyInto(out *PagesEnvVar) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(PagesSecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesEnvVar.
func (in *PagesEnvVar) DeepCopy() *PagesEnvVar {
	if in == nil {
		return nil
	}
	out := new(PagesEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesKVBinding) DeepCopyInto(out *PagesKVBinding) {
	*out = *in
	if in.NamespaceID != nil {
		in, out := &in.NamespaceID, &out.NamespaceID
		*out = new(string)
		**out = **in
	}
	if in.KVNamespaceRef != nil {
		in, out := &in.KVNamespaceRef, &out.KVNamespaceRef
		*out = new(commonv1alpha1.LocalRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesKVBinding.
func (in *PagesKVBinding) DeepCopy() *PagesKVBinding {
	if in == nil {
		return nil
	}
	out := new(PagesKVBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesPlacement) DeepCopyInto(out *PagesPlacement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesPlacement.
func (in *PagesPlacement) DeepCopy() *PagesPlacement {
	if in == nil {
		return nil
	}
	out := new(PagesPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesProject) DeepCopyInto(out *PagesProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesProject.
func (in *PagesProject) DeepCopy() *PagesProject {
	if in == nil {
		return nil
	}
	out := new(PagesProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PagesProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesProjectList) DeepCopyInto(out *PagesProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PagesProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesProjectList.
func (in *PagesProjectList) DeepCopy() *PagesProjectList {
	if in == nil {
		return nil
	}
	out := new(PagesProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PagesProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesProjectObservation) DeepCopyInto(out *PagesProjectObservation) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProductionEnvVars != nil {
		in, out := &in.ProductionEnvVars, &out.ProductionEnvVars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreviewEnvVars != nil {
		in, out := &in.PreviewEnvVars, &out.PreviewEnvVars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesProjectObservation.
func (in *PagesProjectObservation) DeepCopy() *PagesProjectObservation {
	if in == nil {
		return nil
	}
	out := new(PagesProjectObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesProjectParameters) DeepCopyInto(out *PagesProjectParameters) {
	*out = *in
	if in.BuildConfig != nil {
		in, out := &in.BuildConfig, &out.BuildConfig
		*out = new(PagesBuildConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentConfigs != nil {
		in, out := &in.DeploymentConfigs, &out.DeploymentConfigs
		*out = new(PagesDeploymentConfigs)
		(*in).DeepCopyInto(*out)
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(PagesSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesProjectParameters.
func (in *PagesProjectParameters) DeepCopy() *PagesProjectParameters {
	if in == nil {
		return nil
	}
	out := new(PagesProjectParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesProjectSpec) DeepCopyInto(out *PagesProjectSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.ForProvider != nil {
		in, out := &in.ForProvider, &out.ForProvider
		*out = new(PagesProjectParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesProjectSpec.
func (in *PagesProjectSpec) DeepCopy() *PagesProjectSpec {
	if in == nil {
		return nil
	}
	out := new(PagesProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesProjectStatus) DeepCopyInto(out *PagesProjectStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesProjectStatus.
func (in *PagesProjectStatus) DeepCopy() *PagesProjectStatus {
	if in == nil {
		return nil
	}
	out := new(PagesProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesQueueBinding) DeepCopyInto(out *PagesQueueBinding) {
	*out = *in
	if in.QueueName != nil {
		in, out := &in.QueueName, &out.QueueName
		*out = new(string)
		**out = **in
	}
	if in.QueueRef != nil {
		in, out := &in.QueueRef, &out.QueueRef
		*out = new(commonv1alpha1.LocalRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesQueueBinding.
func (in *PagesQueueBinding) DeepCopy() *PagesQueueBinding {
	if in == nil {
		return nil
	}
	out := new(PagesQueueBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesR2Binding) DeepCopyInto(out *PagesR2Binding) {
	*out = *in
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesR2Binding.
func (in *PagesR2Binding) DeepCopy() *PagesR2Binding {
	if in == nil {
		return nil
	}
	out := new(PagesR2Binding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesSecretKeyRef) DeepCopyInto(out *PagesSecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesSecretKeyRef.
func (in *PagesSecretKeyRef) DeepCopy() *PagesSecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(PagesSecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesServiceBinding) DeepCopyInto(out *PagesServiceBinding) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(commonv1alpha1.LocalRef)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Entrypoint != nil {
		in, out := &in.Entrypoint, &out.Entrypoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesServiceBinding.
func (in *PagesServiceBinding) DeepCopy() *PagesServiceBinding {
	if in == nil {
		return nil
	}
	out := new(PagesServiceBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesSource) DeepCopyInto(out *PagesSource) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesSource.
func (in *PagesSource) DeepCopy() *PagesSource {
	if in == nil {
		return nil
	}
	out := new(PagesSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesSourceConfig) DeepCopyInto(out *PagesSourceConfig) {
	*out = *in
	if in.PRCommentsEnabled != nil {
		in, out := &in.PRCommentsEnabled, &out.PRCommentsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProductionDeploymentsEnabled != nil {
		in, out := &in.ProductionDeploymentsEnabled, &out.ProductionDeploymentsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PreviewBranchIncludes != nil {
		in, out := &in.PreviewBranchIncludes, &out.PreviewBranchIncludes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreviewBranchExcludes != nil {
		in, out := &in.PreviewBranchExcludes, &out.PreviewBranchExcludes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PathIncludes != nil {
		in, out := &in.PathIncludes, &out.PathIncludes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PathExcludes != nil {
		in, out := &in.PathExcludes, &out.PathExcludes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesSourceConfig.
func (in *PagesSourceConfig) DeepCopy() *PagesSourceConfig {
	if in == nil {
		return nil
	}
	out := new(PagesSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagesStageObservation) DeepCopyInto(out *PagesStageObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagesStageObservation.
func (in *PagesStageObservation) DeepCopy() *PagesStageObservation {
	if in == nil {
		return nil
	}
	out := new(PagesStageObservation)
	in.DeepCopyInto(out)
	return out
}
