//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactKeyToPath) DeepCopyInto(out *ArtifactKeyToPath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactKeyToPath.
func (in *ArtifactKeyToPath) DeepCopy() *ArtifactKeyToPath {
	if in == nil {
		return nil
	}
	out := new(ArtifactKeyToPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactSecretRef) DeepCopyInto(out *ArtifactSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactSecretRef.
func (in *ArtifactSecretRef) DeepCopy() *ArtifactSecretRef {
	if in == nil {
		return nil
	}
	out := new(ArtifactSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactSource) DeepCopyInto(out *ArtifactSource) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapArtifactSource)
		(*in).DeepCopyInto(*out)
	}
	if in.OCIRef != nil {
		in, out := &in.OCIRef, &out.OCIRef
		*out = new(OCIArtifactSource)
		(*in).DeepCopyInto(*out)
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(URLArtifactSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactSource.
func (in *ArtifactSource) DeepCopy() *ArtifactSource {
	if in == nil {
		return nil
	}
	out := new(ArtifactSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactStatus) DeepCopyInto(out *ArtifactStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactStatus.
func (in *ArtifactStatus) DeepCopy() *ArtifactStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapArtifact) DeepCopyInto(out *ConfigMapArtifact) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArtifactKeyToPath, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapArtifact.
func (in *ConfigMapArtifact) DeepCopy() *ConfigMapArtifact {
	if in == nil {
		return nil
	}
	out := new(ConfigMapArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapArtifactSource) DeepCopyInto(out *ConfigMapArtifactSource) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]ConfigMapArtifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapArtifactSource.
func (in *ConfigMapArtifactSource) DeepCopy() *ConfigMapArtifactSource {
	if in == nil {
		return nil
	}
	out := new(ConfigMapArtifactSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifactSource) DeepCopyInto(out *OCIArtifactSource) {
	*out = *in
	if in.PullSecretRef != nil {
		in, out := &in.PullSecretRef, &out.PullSecretRef
		*out = new(ArtifactSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifactSource.
func (in *OCIArtifactSource) DeepCopy() *OCIArtifactSource {
	if in == nil {
		return nil
	}
	out := new(OCIArtifactSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLArtifactSource) DeepCopyInto(out *URLArtifactSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLArtifactSource.
func (in *URLArtifactSource) DeepCopy() *URLArtifactSource {
	if in == nil {
		return nil
	}
	out := new(URLArtifactSource)
	in.DeepCopyInto(out)
	return out
}
