// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
)

// QueueParameters are the configurable fields of a Queue: the request
// bodies of POST /accounts/{account_id}/queues and PATCH /accounts/{account_id}/queues/{queue_id}.
type QueueParameters struct {
	// +kubebuilder:validation:Enum="eu";"us";"fedramp"
	// +optional
	Jurisdiction *string `json:"jurisdiction,omitempty"`
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	QueueName *string `json:"queue_name,omitempty"`
	// +optional
	Settings *QueueSettingsParameters `json:"settings,omitempty"`
}

// QueueSettingsParameters is a nested object of the Cloudflare API schema.
type QueueSettingsParameters struct {
	// Number of seconds to delay delivery of all messages to consumers.
	// +optional
	DeliveryDelay *int64 `json:"delivery_delay,omitempty"`
	// Indicates if message delivery to consumers is currently paused.
	// +optional
	DeliveryPaused *bool `json:"delivery_paused,omitempty"`
	// Number of seconds after which an unconsumed message will be delayed.
	// +optional
	MessageRetentionPeriod *int64 `json:"message_retention_period,omitempty"`
}

// QueueObservation is the Queue as returned by GET /accounts/{account_id}/queues/{queue_id}.
type QueueObservation struct {
	// +optional
	Consumers []QueueConsumersObservation `json:"consumers,omitempty"`
	// +kubebuilder:validation:Type=number
	// +optional
	ConsumersTotalCount *float64 `json:"consumers_total_count,omitempty"`
	// +optional
	CreatedOn *string `json:"created_on,omitempty"`
	// +optional
	Jurisdiction *string `json:"jurisdiction,omitempty"`
	// +optional
	ModifiedOn *string `json:"modified_on,omitempty"`
	// +optional
	Producers []QueueProducersObservation `json:"producers,omitempty"`
	// +kubebuilder:validation:Type=number
	// +optional
	ProducersTotalCount *float64 `json:"producers_total_count,omitempty"`
	// +optional
	QueueID *string `json:"queue_id,omitempty"`
	// +optional
	QueueName *string `json:"queue_name,omitempty"`
	// +optional
	Settings *QueueSettingsObservation `json:"settings,omitempty"`
}

// QueueConsumersObservation is a nested object of the Cloudflare API schema.
//
// Response body representing a consumer
type QueueConsumersObservation struct {
	// A Resource identifier.
	// +optional
	ConsumerID *string `json:"consumer_id,omitempty"`
	// +optional
	CreatedOn *string `json:"created_on,omitempty"`
	// Name of the dead letter queue, or empty string if not configured
	// +optional
	DeadLetterQueue *string `json:"dead_letter_queue,omitempty"`
	// +optional
	QueueName *string `json:"queue_name,omitempty"`
	// Name of a Worker
	// +optional
	ScriptName *string `json:"script_name,omitempty"`
	// +optional
	Settings *QueueConsumersSettingsObservation `json:"settings,omitempty"`
	// +optional
	Type *string `json:"type,omitempty"`
}

// QueueConsumersSettingsObservation is a nested object of the Cloudflare API schema.
type QueueConsumersSettingsObservation struct {
	// The maximum number of messages to include in a batch.
	// +kubebuilder:validation:Type=number
	// +optional
	BatchSize *float64 `json:"batch_size,omitempty"`
	// Maximum number of concurrent consumers that may consume from this Queue. Set to `null` to automatically opt in to the platform's maximum (recommended).
	// +kubebuilder:validation:Type=number
	// +optional
	MaxConcurrency *float64 `json:"max_concurrency,omitempty"`
	// The maximum number of retries
	// +kubebuilder:validation:Type=number
	// +optional
	MaxRetries *float64 `json:"max_retries,omitempty"`
	// The number of milliseconds to wait for a batch to fill up before attempting to deliver it
	// +kubebuilder:validation:Type=number
	// +optional
	MaxWaitTimeMs *float64 `json:"max_wait_time_ms,omitempty"`
	// The number of seconds to delay before making the message available for another attempt.
	// +kubebuilder:validation:Type=number
	// +optional
	RetryDelay *float64 `json:"retry_delay,omitempty"`
	// The number of milliseconds that a message is exclusively leased. After the timeout, the message becomes available for another attempt.
	// +kubebuilder:validation:Type=number
	// +optional
	VisibilityTimeoutMs *float64 `json:"visibility_timeout_ms,omitempty"`
}

// QueueProducersObservation is a nested object of the Cloudflare API schema.
type QueueProducersObservation struct {
	// +optional
	BucketName *string `json:"bucket_name,omitempty"`
	// +optional
	Script *string `json:"script,omitempty"`
	// +optional
	Type *string `json:"type,omitempty"`
}

// QueueSettingsObservation is a nested object of the Cloudflare API schema.
type QueueSettingsObservation struct {
	// Number of seconds to delay delivery of all messages to consumers.
	// +optional
	DeliveryDelay *int64 `json:"delivery_delay,omitempty"`
	// Indicates if message delivery to consumers is currently paused.
	// +optional
	DeliveryPaused *bool `json:"delivery_paused,omitempty"`
	// Number of seconds after which an unconsumed message will be delayed.
	// +optional
	MessageRetentionPeriod *int64 `json:"message_retention_period,omitempty"`
}

// QueueSpec defines the desired state of a Queue.
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.queue_name))",message="forProvider.queue_name is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="size(self.accountRef.name) > 0 && size(self.accountRef.name) <= 253",message="accountRef.name must name a CloudflareAccount in this namespace (1-253 characters)"
type QueueSpec struct {
	commonv1alpha1.ResourceSpec `json:",inline"`
	// ForProvider holds the Cloudflare API fields, named exactly as in the API.
	ForProvider QueueParameters `json:"forProvider"`
}

// QueueStatus defines the observed state of a Queue.
type QueueStatus struct {
	commonv1alpha1.ResourceStatus `json:",inline"`
	// AtProvider is the resource as last read from the Cloudflare API.
	// +optional
	AtProvider QueueObservation `json:"atProvider,omitempty"`
}

// Queue is a Cloudflare queues (x-fern-sdk-group-name "queues").
//
// Created at /accounts/{account_id}/queues, managed at /accounts/{account_id}/queues/{id} (account scope).
// Default deletion policy: Orphan.
// Immutable fields: jurisdiction.
// Write-only fields: settings.delivery_paused.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=cfqueue;cfq,categories={cloudflare,managed,queues}
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.jurisdiction) || !has(self.spec.forProvider) || !has(self.spec.forProvider.jurisdiction) || self.spec.forProvider.jurisdiction == oldSelf.spec.forProvider.jurisdiction || (has(oldSelf.status.atProvider) && has(oldSelf.status.atProvider.jurisdiction) && oldSelf.status.atProvider.jurisdiction == self.spec.forProvider.jurisdiction)",message="forProvider.jurisdiction is immutable once the resource exists (status.id is set): recreate the object to change it, or set it to the value Cloudflare reports (status.atProvider.jurisdiction)"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="QUEUE",type="string",JSONPath=".status.atProvider.queue_name"
// +kubebuilder:printcolumn:name="CONSUMERS",type="number",JSONPath=".status.atProvider.consumers_total_count",priority=1
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type Queue struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec QueueSpec `json:"spec"`
	// +optional
	Status QueueStatus `json:"status,omitempty"`
}

// GetResourceSpec implements commonv1alpha1.Managed.
func (o *Queue) GetResourceSpec() *commonv1alpha1.ResourceSpec { return &o.Spec.ResourceSpec }

// GetResourceStatus implements commonv1alpha1.Managed.
func (o *Queue) GetResourceStatus() *commonv1alpha1.ResourceStatus { return &o.Status.ResourceStatus }

// QueueList is a list of Queue.
//
// +kubebuilder:object:root=true
type QueueList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Queue `json:"items"`
}

var _ commonv1alpha1.Managed = &Queue{}
