// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *QueueConsumersObservation) DeepCopyInto(out *QueueConsumersObservation) {
	*out = *in
	if in.ConsumerID != nil {
		in, out := &in.ConsumerID, &out.ConsumerID
		*out = new(string)
		**out = **in
	}
	if in.CreatedOn != nil {
		in, out := &in.CreatedOn, &out.CreatedOn
		*out = new(string)
		**out = **in
	}
	if in.DeadLetterQueue != nil {
		in, out := &in.DeadLetterQueue, &out.DeadLetterQueue
		*out = new(string)
		**out = **in
	}
	if in.QueueName != nil {
		in, out := &in.QueueName, &out.QueueName
		*out = new(string)
		**out = **in
	}
	if in.ScriptName != nil {
		in, out := &in.ScriptName, &out.ScriptName
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(QueueConsumersSettingsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *QueueConsumersObservation) DeepCopy() *QueueConsumersObservation {
	if in == nil {
		return nil
	}
	out := new(QueueConsumersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *QueueConsumersSettingsObservation) DeepCopyInto(out *QueueConsumersSettingsObservation) {
	*out = *in
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(float64)
		**out = **in
	}
	if in.MaxConcurrency != nil {
		in, out := &in.MaxConcurrency, &out.MaxConcurrency
		*out = new(float64)
		**out = **in
	}
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(float64)
		**out = **in
	}
	if in.MaxWaitTimeMs != nil {
		in, out := &in.MaxWaitTimeMs, &out.MaxWaitTimeMs
		*out = new(float64)
		**out = **in
	}
	if in.RetryDelay != nil {
		in, out := &in.RetryDelay, &out.RetryDelay
		*out = new(float64)
		**out = **in
	}
	if in.VisibilityTimeoutMs != nil {
		in, out := &in.VisibilityTimeoutMs, &out.VisibilityTimeoutMs
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *QueueConsumersSettingsObservation) DeepCopy() *QueueConsumersSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(QueueConsumersSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *QueueObservation) DeepCopyInto(out *QueueObservation) {
	*out = *in
	if in.Consumers != nil {
		in, out := &in.Consumers, &out.Consumers
		*out = make([]QueueConsumersObservation, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
	if in.ConsumersTotalCount != nil {
		in, out := &in.ConsumersTotalCount, &out.ConsumersTotalCount
		*out = new(float64)
		**out = **in
	}
	if in.CreatedOn != nil {
		in, out := &in.CreatedOn, &out.CreatedOn
		*out = new(string)
		**out = **in
	}
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
	if in.ModifiedOn != nil {
		in, out := &in.ModifiedOn, &out.ModifiedOn
		*out = new(string)
		**out = **in
	}
	if in.Producers != nil {
		in, out := &in.Producers, &out.Producers
		*out = make([]QueueProducersObservation, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
	if in.ProducersTotalCount != nil {
		in, out := &in.ProducersTotalCount, &out.ProducersTotalCount
		*out = new(float64)
		**out = **in
	}
	if in.QueueID != nil {
		in, out := &in.QueueID, &out.QueueID
		*out = new(string)
		**out = **in
	}
	if in.QueueName != nil {
		in, out := &in.QueueName, &out.QueueName
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(QueueSettingsObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *QueueObservation) DeepCopy() *QueueObservation {
	if in == nil {
		return nil
	}
	out := new(QueueObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *QueueParameters) DeepCopyInto(out *QueueParameters) {
	*out = *in
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(QueueSettingsParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *QueueParameters) DeepCopy() *QueueParameters {
	if in == nil {
		return nil
	}
	out := new(QueueParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *QueueProducersObservation) DeepCopyInto(out *QueueProducersObservation) {
	*out = *in
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *QueueProducersObservation) DeepCopy() *QueueProducersObservation {
	if in == nil {
		return nil
	}
	out := new(QueueProducersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *QueueSettingsObservation) DeepCopyInto(out *QueueSettingsObservation) {
	*out = *in
	if in.DeliveryDelay != nil {
		in, out := &in.DeliveryDelay, &out.DeliveryDelay
		*out = new(int64)
		**out = **in
	}
	if in.DeliveryPaused != nil {
		in, out := &in.DeliveryPaused, &out.DeliveryPaused
		*out = new(bool)
		**out = **in
	}
	if in.MessageRetentionPeriod != nil {
		in, out := &in.MessageRetentionPeriod, &out.MessageRetentionPeriod
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *QueueSettingsObservation) DeepCopy() *QueueSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(QueueSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *QueueSettingsParameters) DeepCopyInto(out *QueueSettingsParameters) {
	*out = *in
	if in.DeliveryDelay != nil {
		in, out := &in.DeliveryDelay, &out.DeliveryDelay
		*out = new(int64)
		**out = **in
	}
	if in.DeliveryPaused != nil {
		in, out := &in.DeliveryPaused, &out.DeliveryPaused
		*out = new(bool)
		**out = **in
	}
	if in.MessageRetentionPeriod != nil {
		in, out := &in.MessageRetentionPeriod, &out.MessageRetentionPeriod
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *QueueSettingsParameters) DeepCopy() *QueueSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(QueueSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *QueueSpec) DeepCopyInto(out *QueueSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *QueueSpec) DeepCopy() *QueueSpec {
	if in == nil {
		return nil
	}
	out := new(QueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *QueueStatus) DeepCopyInto(out *QueueStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *QueueStatus) DeepCopy() *QueueStatus {
	if in == nil {
		return nil
	}
	out := new(QueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *Queue) DeepCopyInto(out *Queue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of the receiver.
func (in *Queue) DeepCopy() *Queue {
	if in == nil {
		return nil
	}
	out := new(Queue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *Queue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *QueueList) DeepCopyInto(out *QueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Queue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *QueueList) DeepCopy() *QueueList {
	if in == nil {
		return nil
	}
	out := new(QueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *QueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
