package fake

// # The generic profile (UNVERIFIED)
//
// Kinds generated by cmd/flaregen that have no hand-written profile can be emulated by one
// stateful CRUD store driven by their Descriptor fields (GenericKind) and the pinned OpenAPI
// spec. It exists so that every generated kind gets emulator coverage the day it is added to
// generator.yaml; it is a stand-in until a live recording pass (docs/generator-scaleout.md)
// replaces its guesses with recorded behavior.
//
// EVERYTHING in generic*.go is UNVERIFIED unless a line cites a recording: it follows the
// spec, and the spec is known to disagree with the real API (see the known spec defects in
// internal/generic/descriptors/emulator_test.go). Per-kind corrections that a recording backs
// live in generic_quirks.go.
//
// Behavior, per GenericKind:
//
//   - Opt-in: only kinds passed in Options.Generic are served (GeneratedGenericKinds lists the
//     generator.yaml kinds marked `emulate: generic`). New(Options{}) serves none, so the
//     conformance rule "a recording hits an emulated route no scenario replays" is unaffected.
//   - Hand-written profiles always win: a kind whose create or item route is already served
//     (kv, queues, d1, tunnels, vpc, workers, tags, tokens) is skipped (GenericSkipped).
//   - Routes are the spec's operations at the kind's paths: POST CreatePath, GET ListPath,
//     GET/PUT/PATCH/DELETE ItemPath as far as the spec defines them (singletons: GET/PUT/PATCH
//     at ItemPath). Every request is validated against the spec (DELETE without its body) and
//     a violation is answered 400/10001.
//   - Create: the stored object is the request body projected onto the item schema (the GET
//     result, else the create result): writeOnly properties and the Descriptor's WriteOnly
//     paths are dropped, absent properties get their spec default, server timestamps
//     (created*/modified*/updated*, precision from the spec example) come from the fake clock,
//     account_id is the path's account, and absent required properties get zero values. The
//     IDField is taken from the request when the client chooses it (IDField in the body, or
//     IDField == NameField), else generated in the shape the spec gives (idGenerator).
//     A NameField (or client-chosen ID) already in use → 409/10010.
//   - GET item → the stored object; unknown ID → 404/7003 (or the recorded quirk).
//   - PUT replaces: the body is shaped as on create, keeping the ID, the creation timestamps and
//     fields the PUT body cannot carry (create-only fields); modified timestamps advance.
//     PATCH merges (RFC 7386, null deletes).
//   - DELETE → result null, or the deleted object projected onto the spec's delete result, or
//     (a delete result that rejects null) the first zero value the spec accepts.
//   - Every result is shaped to satisfy the pinned spec's response schema, which strict response
//     validation checks in tests: a oneOf/anyOf is shaped by one branch that the spec accepts
//     (pickBranch in generic_schema.go: the branch keeping most of the value, then spec order).
//   - List: creation order; page/per_page pagination with the result_info fields the spec's
//     list response declares (per_page default from the spec, else 20: Hyperdrive 0153 and
//     Secrets Store 0155 answer per_page 20), cursor pagination when result_info declares a
//     cursor, no result_info and no paging when the spec has none (Vectorize, 0154).
//   - Singletons: GET returns a default object shaped from the schema (defaults, zero values)
//     until PUT/PATCH changes it.
//   - A list result that the spec declares as an object whose only member is the item array
//     (R2: {"buckets": [...]}) is answered in that shape.
//   - Per-kind extensions (GenericKind.Headers, ObservedAs, SubResources; generator.yaml
//     requestHeaders, observedAs, subResources, docs/generator-scaleout.md): a partitioning
//     header splits the kind's collection by its value (absent = its spec default) and is stored
//     in the object; an update header sets the stored field; an update route whose spec has no
//     body ignores any body; ObservedAs fields of a body are stored under their read-back name;
//     a sub-resource is a document stored with its item (GET → 404 when absent, PUT, DELETE).
//
// What it cannot model is listed in docs/generator-scaleout.md (product validation and error
// codes, async state machines, side effects on other resources, non-JSON bodies, …).

import (
	"encoding/base64"
	"fmt"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// GenericKind is the part of a generated kind's Descriptor (internal/generic.Descriptor) the
// generic profile needs. Paths use {account_id} or {zone_id} and {id}.
type GenericKind struct {
	Group, Kind string
	Scope       string // "account" | "zone"

	CreatePath, ItemPath, ListPath string
	IDField, NameField             string
	UpdateMethod                   string // informational: the spec decides which update routes exist
	WriteOnly                      []string
	Singleton                      bool

	// Headers, ObservedAs and SubResources mirror internal/generic.Extension (generator.yaml
	// requestHeaders, observedAs, subResources); see the package comment above.
	Headers      []GenericHeader
	ObservedAs   map[string]string
	SubResources []GenericSubResource
}

// GenericHeader is a forProvider field the kind sends as a request header
// (internal/generic.HeaderField). Update=false: the header partitions the collection (a
// resource made with one value is invisible with another; absent means Default) and is stored in
// the object's Field when the item schema has it. Update=true: an update request's header sets
// the object's Field (or its ObservedAs name).
type GenericHeader struct {
	Header, Field string
	Update        bool
	Default       string
}

// GenericSubResource is a fixed sub-path of the item served as its own stored document
// (internal/generic.SubResource).
type GenericSubResource struct {
	Field, Path string
	// Delete mirrors generic.SubResource.Delete (the spec has a DELETE at the path); the
	// emulator serves DELETE whenever the spec has one.
	Delete bool
}

// GeneratedGenericKinds returns the generator.yaml kinds marked `emulate: generic`
// (zz_generated_generic.go).
func GeneratedGenericKinds() []GenericKind {
	return append([]GenericKind(nil), generatedGenericKinds...)
}

// Error codes of the generic profile. UNVERIFIED: every product has its own (KV 10013,
// Queues 11000, Hyperdrive 2006 …); a recorded one goes into generic_quirks.go.
const (
	genericNotFoundCode   = 7003
	genericConflictCode   = 10010
	genericViolationCode  = 10001 // as RejectSchemaViolations
	genericDefaultPerPage = 20    // 0153, 0155
)

type genericProfile struct {
	models  []*genericModel
	skipped []string
	err     error // loading the spec failed: every generic route answers 500
	state   map[string]*genericCollection
}

type genericObject struct {
	obj     map[string]any
	seq     int64
	created time.Time
	// subs holds the item's sub-resource documents (GenericSubResource), keyed by Field.
	subs map[string]map[string]any
}

// genericSub is one GenericSubResource of a model with its spec operations.
type genericSub struct {
	res           GenericSubResource
	get, put, del *openapi3.Operation
	doc           *gSchema // GET result: the stored document's shape
	putRes        *gSchema
	delRes        *gSchema
}

// genericCollection holds one kind's objects in one account (or zone).
type genericCollection struct {
	items            map[string]*genericObject
	singleton        map[string]any
	singletonCreated time.Time
}

type genericModel struct {
	kind  GenericKind
	spec  *Spec
	quirk genericQuirk

	create, list, get, put, patch, del *openapi3.Operation

	item      *gSchema // shape of the stored object
	createRes *gSchema // create result, when it is an object schema
	putBody   *gSchema
	listInfo  *gSchema
	delRes    *gSchema // delete result, when it is an object schema with properties
	delResult *gSchema // delete result schema, whatever it is
	perPage   int
	cursor    bool
	idGen     func(time.Time) string
	clientID  bool // the client chooses the ID (IDField in the create body, or IDField == NameField)
	// listWrap is the property of the list result object that holds the items, when the spec's
	// list result is an object with exactly one array property (R2: {"buckets": [...]}).
	listWrap string
	subs     []*genericSub
}

// GenericSkipped returns the Options.Generic kinds that are not served because a hand-written
// profile already serves their routes, or because the spec has no operation for them.
func (s *Server) GenericSkipped() []string {
	if s.generic == nil {
		return nil
	}
	return append([]string(nil), s.generic.skipped...)
}

// registerGeneric registers the generic profile's routes for opts.Generic. It runs after the
// hand-written profiles, which therefore take precedence.
func (s *Server) registerGeneric() {
	if len(s.opts.Generic) == 0 {
		return
	}
	g := &genericProfile{state: map[string]*genericCollection{}}
	s.generic = g
	spec := s.opts.Spec
	if spec == nil {
		spec, g.err = LoadDefaultSpec()
	}
	for _, k := range s.opts.Generic {
		if g.err != nil {
			s.registerGenericBroken(k)
			continue
		}
		m, why := newGenericModel(k, spec)
		if why == "" {
			why = s.genericConflict(m)
		}
		if why != "" {
			g.skipped = append(g.skipped, k.Group+"/"+k.Kind+": "+why)
			continue
		}
		g.models = append(g.models, m)
		s.registerGenericModel(m)
	}
}

func (g *genericProfile) reset() {
	if g != nil {
		g.state = map[string]*genericCollection{}
	}
}

func (s *Server) registerGenericBroken(k GenericKind) {
	h := func(c *reqCtx) response {
		return fail(http.StatusInternalServerError, 1000, "flarefake: the generic profile needs the pinned spec: "+s.generic.err.Error())
	}
	for _, p := range []string{k.CreatePath, k.ItemPath} {
		if p != "" {
			for _, m := range []string{http.MethodGet, http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete} {
				s.handle(m, p, h)
			}
		}
	}
}

// newGenericModel reads the kind's operations and schemas from the spec. A non-empty reason
// means the kind cannot be served.
func newGenericModel(k GenericKind, spec *Spec) (*genericModel, string) {
	m := &genericModel{kind: k, spec: spec, quirk: genericQuirks[k.Group+"/"+k.Kind]}
	itemPI := specPathItem(spec.Doc, k.ItemPath)
	if itemPI == nil {
		return nil, "no spec path for " + k.ItemPath
	}
	m.get, m.put, m.patch, m.del = itemPI.Get, itemPI.Put, itemPI.Patch, itemPI.Delete
	if !k.Singleton {
		if pi := specPathItem(spec.Doc, k.CreatePath); pi != nil {
			m.create = pi.Post
		}
		if pi := specPathItem(spec.Doc, k.ListPath); pi != nil {
			m.list = pi.Get
		}
		if m.create == nil || k.IDField == "" {
			return nil, "no create operation or IDField"
		}
	} else {
		m.del = nil
	}
	if m.get != nil {
		m.item, _ = responseResult(m.get)
	}
	if res, _ := responseResult(m.create); res != nil && res.typ == "object" {
		m.createRes = res
		if m.item == nil || len(m.item.props) == 0 {
			m.item = res
		}
	}
	if m.item == nil {
		m.item = &gSchema{typ: "object"}
	}
	m.putBody = requestBodySchema(m.put)
	if m.del != nil {
		m.delResult, _ = responseResult(m.del)
		if res := m.delResult; res != nil && len(res.props) > 0 {
			m.delRes = res
		}
	}
	if m.list != nil {
		var listRes *gSchema
		listRes, m.listInfo = responseResult(m.list)
		if listRes != nil && listRes.typ == "object" && len(listRes.props) == 1 {
			for name, p := range listRes.props {
				if p.typ == "array" {
					m.listWrap = name
				}
			}
		}
		m.perPage = queryDefault(m.list, "per_page")
		if m.perPage == 0 {
			m.perPage = genericDefaultPerPage
		}
		if m.listInfo != nil {
			_, c1 := m.listInfo.props["cursor"]
			_, c2 := m.listInfo.props["cursors"]
			m.cursor = c1 || c2
		}
	}
	if !k.Singleton {
		createBody := requestBodySchema(m.create)
		_, inBody := createBody.propsOrNil()[k.IDField]
		m.clientID = inBody || (k.NameField != "" && k.IDField == k.NameField)
		idSchema := m.item.props[k.IDField]
		if idSchema == nil {
			idSchema = &gSchema{}
		}
		m.idGen = idGenerator(idSchema)
	}
	for _, sr := range k.SubResources {
		pi := specPathItem(spec.Doc, k.ItemPath+sr.Path)
		if pi == nil || pi.Get == nil || pi.Put == nil {
			return nil, "no spec GET and PUT for " + k.ItemPath + sr.Path
		}
		sub := &genericSub{res: sr, get: pi.Get, put: pi.Put, del: pi.Delete}
		sub.doc, _ = responseResult(pi.Get)
		if sub.doc == nil {
			sub.doc = &gSchema{typ: "object"}
		}
		sub.putRes, _ = responseResult(pi.Put)
		sub.delRes, _ = responseResult(pi.Delete)
		m.subs = append(m.subs, sub)
	}
	return m, ""
}

func (s *gSchema) propsOrNil() map[string]*gSchema {
	if s == nil {
		return nil
	}
	return s.props
}

// genericConflict reports an already registered route (a hand-written profile, or an earlier
// generic kind) that could serve a request for the kind: segment by segment, either side is a
// parameter or the literals are equal. Such a kind is skipped rather than half-shadowed.
func (s *Server) genericConflict(m *genericModel) string {
	for _, p := range []string{m.kind.CreatePath, m.kind.ItemPath} {
		if p == "" {
			continue
		}
		segs := strings.Split(strings.Trim(p, "/"), "/")
		for _, rt := range s.routes {
			if len(rt.segments) != len(segs) {
				continue
			}
			overlap := true
			for i, a := range rt.segments {
				pa, pb := strings.HasPrefix(a, "{"), strings.HasPrefix(segs[i], "{")
				if !pa && !pb && a != segs[i] {
					overlap = false
					break
				}
			}
			if overlap {
				return "a hand-written profile (or an earlier kind) serves " + p + " as /" + strings.Join(rt.segments, "/")
			}
		}
	}
	return ""
}

func (s *Server) registerGenericModel(m *genericModel) {
	k := m.kind
	if k.Singleton {
		s.handle(http.MethodGet, k.ItemPath, m.singletonGet)
		if m.put != nil {
			s.handle(http.MethodPut, k.ItemPath, m.singletonUpdate(false))
		}
		if m.patch != nil {
			s.handle(http.MethodPatch, k.ItemPath, m.singletonUpdate(true))
		}
		return
	}
	s.handle(http.MethodPost, k.CreatePath, m.createH)
	if m.list != nil {
		s.handle(http.MethodGet, k.ListPath, m.listH)
	}
	if m.get != nil {
		s.handle(http.MethodGet, k.ItemPath, m.getH)
	}
	if m.put != nil {
		s.handle(http.MethodPut, k.ItemPath, m.updateH(false))
	}
	if m.patch != nil {
		s.handle(http.MethodPatch, k.ItemPath, m.updateH(true))
	}
	if m.del != nil {
		s.handle(http.MethodDelete, k.ItemPath, m.deleteH)
	}
	for _, sub := range m.subs {
		p := k.ItemPath + sub.res.Path
		s.handle(http.MethodGet, p, m.subGetH(sub))
		s.handle(http.MethodPut, p, m.subPutH(sub))
		if sub.del != nil {
			s.handle(http.MethodDelete, p, m.subDeleteH(sub))
		}
	}
}

// ---- handlers --------------------------------------------------------------------------------

func (m *genericModel) scopeID(c *reqCtx) string {
	if m.kind.Scope == "zone" {
		return "zone:" + c.params["zone_id"]
	}
	return "account:" + c.params["account_id"]
}

// partition renders the values of the kind's partitioning headers (GenericHeader, Update=false)
// for a collection key: "" for a kind without them. get returns a header's request value.
func (m *genericModel) partition(get func(string) string) string {
	var b strings.Builder
	for _, h := range m.kind.Headers {
		if !h.Update {
			fmt.Fprintf(&b, "|%s=%s", strings.ToLower(h.Header), m.headerValue(h, get))
		}
	}
	return b.String()
}

// headerValue is a partitioning header's value: the request's, else its default.
func (m *genericModel) headerValue(h GenericHeader, get func(string) string) string {
	if v := get(h.Header); v != "" {
		return v
	}
	return h.Default
}

func (m *genericModel) coll(c *reqCtx) *genericCollection {
	key := m.kind.Group + "/" + m.kind.Kind + "@" + m.scopeID(c) + m.partition(c.r.Header.Get)
	g := c.s.generic
	col, ok := g.state[key]
	if !ok {
		col = &genericCollection{items: map[string]*genericObject{}}
		g.state[key] = col
	}
	return col
}

func (m *genericModel) ctx(c *reqCtx, created time.Time, fill bool) shapeCtx {
	return shapeCtx{now: c.now, created: created, accountID: c.params["account_id"], fill: fill}
}

// check validates the request against the spec and decodes a JSON object body.
func (m *genericModel) check(c *reqCtx, withBody bool) (map[string]any, *response) {
	if err := m.spec.validate(c.r, c.body, !withBody); err != nil {
		r := fail(http.StatusBadRequest, genericViolationCode, "flarefake(generic): request does not match the pinned OpenAPI spec: "+err.Error())
		return nil, &r
	}
	if !withBody {
		return nil, nil
	}
	body := map[string]any{}
	if len(strings.TrimSpace(string(c.body))) > 0 {
		if r := c.decodeJSON(&body); r != nil {
			return nil, r
		}
	}
	return body, nil
}

func (m *genericModel) notFound(id string) response {
	if q := m.quirk.notFound; q != nil {
		return fail(http.StatusNotFound, q.Code, q.Message)
	}
	return fail(http.StatusNotFound, genericNotFoundCode, fmt.Sprintf("flarefake(generic): %s %q not found", m.kind.Kind, id))
}

func (m *genericModel) conflict(field, v string) response {
	return fail(http.StatusConflict, genericConflictCode, fmt.Sprintf("flarefake(generic): a %s with %s %q already exists", m.kind.Kind, field, v))
}

// finish drops the Descriptor's write-only paths (never read back, per the generator or a
// recording) from a stored object.
func (m *genericModel) finish(obj map[string]any) map[string]any {
	for _, p := range m.kind.WriteOnly {
		deletePath(obj, p)
	}
	return obj
}

func (m *genericModel) nameTaken(col *genericCollection, name any, exceptID string) bool {
	if m.kind.NameField == "" || name == nil {
		return false
	}
	for id, o := range col.items {
		if id != exceptID && o.obj[m.kind.NameField] == name {
			return true
		}
	}
	return false
}

func (m *genericModel) createH(c *reqCtx) response {
	body, r := m.check(c, true)
	if r != nil {
		return *r
	}
	col := m.coll(c)
	k := m.kind
	var id string
	if m.clientID {
		id, _ = body[k.IDField].(string)
		if id == "" && k.NameField != "" {
			id, _ = body[k.NameField].(string)
		}
		if id == "" {
			return fail(http.StatusBadRequest, genericViolationCode, "flarefake(generic): "+k.IDField+" is required")
		}
		if _, dup := col.items[id]; dup {
			return m.conflict(k.IDField, id)
		}
	} else {
		id = c.s.ids.next(func() string { return m.idGen(c.now) })
	}
	if k.NameField != "" && k.NameField != k.IDField && m.nameTaken(col, body[k.NameField], "") {
		return m.conflict(k.NameField, fmt.Sprint(body[k.NameField]))
	}
	obj := shapeTop(m.item, m.renamed(body), m.ctx(c, c.now, true))
	m.setHeaderFields(c, obj, false)
	obj[k.IDField] = id
	m.finish(obj)
	col.items[id] = &genericObject{obj: obj, seq: c.s.nextSeq(), created: c.now}
	if m.createRes != nil && m.createRes != m.item {
		return ok(m.finish(shapeTop(m.createRes, obj, m.ctx(c, c.now, false))))
	}
	return ok(deepCopyJSON(obj))
}

func (m *genericModel) getH(c *reqCtx) response {
	if _, r := m.check(c, false); r != nil {
		return *r
	}
	id := c.params["id"]
	o, found := m.coll(c).items[id]
	if !found {
		return m.notFound(id)
	}
	return ok(deepCopyJSON(o.obj))
}

func (m *genericModel) updateH(merge bool) handler {
	op := m.put
	if merge {
		op = m.patch
	}
	bodyless := requestBodySchema(op) == nil // R2's PATCH: headers only
	return func(c *reqCtx) response {
		body, r := m.check(c, true)
		if r != nil {
			return *r
		}
		if bodyless {
			body = map[string]any{} // the spec defines no body: whatever was sent changes nothing
		}
		col := m.coll(c)
		id := c.params["id"]
		o, found := col.items[id]
		if !found {
			return m.notFound(id)
		}
		k := m.kind
		if name, set := body[k.NameField]; set && k.NameField != k.IDField && m.nameTaken(col, name, id) {
			return m.conflict(k.NameField, fmt.Sprint(name))
		}
		next := m.updated(c, o.obj, m.renamed(body), o.created, merge)
		m.setHeaderFields(c, next, true)
		next[k.IDField] = id
		o.obj = m.finish(next)
		return ok(deepCopyJSON(o.obj))
	}
}

// updated returns the object after a PUT (replace) or PATCH (merge) with body.
func (m *genericModel) updated(c *reqCtx, cur, body map[string]any, created time.Time, merge bool) map[string]any {
	if merge {
		next := deepCopyJSON(cur).(map[string]any)
		mergePatch(next, shapeTop(m.item, body, m.ctx(c, created, false)))
		// Refresh server timestamps only (fill=true over the merged object keeps its values).
		return shapeTop(m.item, next, m.ctx(c, created, true))
	}
	in := deepCopyJSON(body).(map[string]any)
	// Fields the PUT body cannot carry (create-only fields, server-set values) survive; the
	// ones it can carry are replaced, and reset to their defaults when omitted (as Queues' PUT
	// does, 0033).
	for f, v := range cur {
		if _, carried := m.putBody.propsOrNil()[f]; carried {
			continue
		}
		if _, set := in[f]; !set {
			in[f] = deepCopyJSON(v)
		}
	}
	return shapeTop(m.item, in, m.ctx(c, created, true))
}

func (m *genericModel) deleteH(c *reqCtx) response {
	if _, r := m.check(c, false); r != nil {
		return *r
	}
	col := m.coll(c)
	id := c.params["id"]
	o, found := col.items[id]
	if !found {
		return m.notFound(id)
	}
	delete(col.items, id)
	if m.delRes != nil {
		return ok(shapeTop(m.delRes, o.obj, m.ctx(c, o.created, false)))
	}
	// result null, unless the spec's delete result rejects null: then the first zero value it
	// accepts (Vectorize v2's delete result is anyOf object/array/string → {}). UNVERIFIED: no
	// recording deletes a generically emulated kind.
	if res := m.delResult; res != nil && !res.accepts(nil) {
		return ok(zeroValue(res, m.ctx(c, o.created, true)))
	}
	return ok(nil)
}

func (m *genericModel) listH(c *reqCtx) response {
	if _, r := m.check(c, false); r != nil {
		return *r
	}
	col := m.coll(c)
	items := make([]*genericObject, 0, len(col.items))
	for _, o := range col.items {
		items = append(items, o)
	}
	sort.Slice(items, func(i, j int) bool { return items[i].seq < items[j].seq })
	all := make([]any, 0, len(items))
	for _, o := range items {
		all = append(all, deepCopyJSON(o.obj))
	}
	if m.listInfo == nil {
		return ok(m.wrap(all)) // no result_info, no paging (0154)
	}
	perPage := c.intQuery("per_page", m.perPage)
	if perPage <= 0 {
		perPage = m.perPage
	}
	if perPage > maxPerPage {
		perPage = maxPerPage
	}
	if cur := c.query.Get("cursor"); m.cursor && (cur != "" || !m.hasPage()) {
		start := decodeCursor(cur)
		if start > len(all) {
			start = len(all)
		}
		end := start + perPage
		if end > len(all) {
			end = len(all)
		}
		next := ""
		if end < len(all) {
			next = encodeCursor(end)
		}
		return okList(m.wrap(all[start:end]), m.info(map[string]any{
			"count": end - start, "per_page": perPage, "total_count": len(all),
			"cursor": next, "cursors": map[string]any{"after": next},
		}))
	}
	page := c.intQuery("page", 1)
	out, page, perPage, totalPages := paginate(all, page, perPage, m.perPage)
	return okList(m.wrap(out), m.info(map[string]any{
		"page": page, "per_page": perPage, "count": len(out), "total_count": len(all), "total_pages": totalPages,
	}))
}

func (m *genericModel) hasPage() bool { return hasQueryParam(m.list, "page") }

// wrap puts a list page into the list result object when the spec wraps it (listWrap).
func (m *genericModel) wrap(items []any) any {
	if m.listWrap == "" {
		return items
	}
	return map[string]any{m.listWrap: items}
}

// renamed returns a request body with the kind's ObservedAs fields under their stored names
// (R2: the create body's storageClass is stored as storage_class). The body is not modified.
func (m *genericModel) renamed(body map[string]any) map[string]any {
	if len(m.kind.ObservedAs) == 0 {
		return body
	}
	out := make(map[string]any, len(body))
	for k, v := range body {
		out[k] = v
	}
	for from, to := range m.kind.ObservedAs {
		if v, ok := out[from]; ok {
			delete(out, from)
			if _, set := out[to]; !set {
				out[to] = v
			}
		}
	}
	return out
}

// setHeaderFields stores header values in obj where the item schema has the field: on create,
// the partitioning headers (R2: the bucket's jurisdiction; absent → the default); on update,
// the update headers that the request sends (R2: cf-r2-storage-class → storage_class).
func (m *genericModel) setHeaderFields(c *reqCtx, obj map[string]any, update bool) {
	for _, h := range m.kind.Headers {
		field := h.Field
		if to, ok := m.kind.ObservedAs[field]; ok {
			field = to
		}
		if _, stored := m.item.props[field]; !stored {
			continue
		}
		switch {
		case !h.Update && !update:
			obj[field] = m.headerValue(h, c.r.Header.Get)
		case h.Update && update:
			if v := c.r.Header.Get(h.Header); v != "" {
				obj[field] = v
			}
		}
	}
}

// ---- sub-resources (GenericSubResource) --------------------------------------------------------
//
// UNVERIFIED throughout (spec only): a sub-resource is a document stored with its item. GET of an
// item without one → 404 with the generic not-found code (the real code for R2 CORS is not
// known; the kind's item quirk code would claim "the item is missing"), PUT replaces it (the body shaped by the GET result schema), DELETE
// removes it. PUT and DELETE answer the spec's result: {} for a free-form object result.

func (m *genericModel) subItem(c *reqCtx) (*genericObject, *response) {
	id := c.params["id"]
	o, found := m.coll(c).items[id]
	if !found {
		r := m.notFound(id)
		return nil, &r
	}
	return o, nil
}

// subResult is the answer of a sub-resource write whose spec result is res.
func subResult(res *gSchema, stored map[string]any, ctx shapeCtx) any {
	switch {
	case res == nil:
		return nil
	case len(res.props) > 0 && stored != nil:
		return shapeTop(res, stored, ctx)
	default:
		return zeroValue(res, ctx)
	}
}

func (m *genericModel) subGetH(sub *genericSub) handler {
	return func(c *reqCtx) response {
		if _, r := m.check(c, false); r != nil {
			return *r
		}
		o, r := m.subItem(c)
		if r != nil {
			return *r
		}
		doc, found := o.subs[sub.res.Field]
		if !found {
			// UNVERIFIED: the generic not-found code, not the kind's item quirk (R2's 10006
			// means "the bucket does not exist" to wrangler; a missing CORS policy is not that).
			code := genericNotFoundCode
			return fail(http.StatusNotFound, code, fmt.Sprintf("flarefake(generic): %s %q has no %s", m.kind.Kind, c.params["id"], sub.res.Field))
		}
		return ok(deepCopyJSON(doc))
	}
}

func (m *genericModel) subPutH(sub *genericSub) handler {
	return func(c *reqCtx) response {
		body, r := m.check(c, true)
		if r != nil {
			return *r
		}
		o, r := m.subItem(c)
		if r != nil {
			return *r
		}
		ctx := m.ctx(c, o.created, false)
		doc := shapeTop(sub.doc, body, ctx)
		if o.subs == nil {
			o.subs = map[string]map[string]any{}
		}
		o.subs[sub.res.Field] = doc
		return ok(subResult(sub.putRes, doc, ctx))
	}
}

func (m *genericModel) subDeleteH(sub *genericSub) handler {
	return func(c *reqCtx) response {
		if _, r := m.check(c, false); r != nil {
			return *r
		}
		o, r := m.subItem(c)
		if r != nil {
			return *r
		}
		doc := o.subs[sub.res.Field]
		delete(o.subs, sub.res.Field)
		return ok(subResult(sub.delRes, doc, m.ctx(c, o.created, false)))
	}
}

// info keeps the result_info fields the spec's list response declares, minus those the real
// API is recorded to omit (quirks).
func (m *genericModel) info(v map[string]any) map[string]any {
	out := map[string]any{}
	for k, val := range v {
		if _, declared := m.listInfo.props[k]; !declared {
			continue
		}
		omit := false
		for _, o := range m.quirk.resultInfoOmit {
			omit = omit || o == k
		}
		if !omit {
			out[k] = val
		}
	}
	return out
}

func encodeCursor(offset int) string {
	return base64.RawURLEncoding.EncodeToString([]byte("flarefake:" + strconv.Itoa(offset)))
}

func decodeCursor(s string) int {
	b, err := base64.RawURLEncoding.DecodeString(s)
	if err != nil {
		return 0
	}
	n, err := strconv.Atoi(strings.TrimPrefix(string(b), "flarefake:"))
	if err != nil || n < 0 {
		return 0
	}
	return n
}

func (m *genericModel) singletonObj(c *reqCtx) map[string]any {
	col := m.coll(c)
	if col.singleton == nil {
		col.singletonCreated = c.now
		col.singleton = m.finish(shapeTop(m.item, map[string]any{}, m.ctx(c, c.now, true)))
	}
	return col.singleton
}

func (m *genericModel) singletonGet(c *reqCtx) response {
	if _, r := m.check(c, false); r != nil {
		return *r
	}
	return ok(deepCopyJSON(m.singletonObj(c)))
}

func (m *genericModel) singletonUpdate(merge bool) handler {
	return func(c *reqCtx) response {
		body, r := m.check(c, true)
		if r != nil {
			return *r
		}
		cur := m.singletonObj(c)
		col := m.coll(c)
		next := m.finish(m.updated(c, cur, body, col.singletonCreated, merge))
		col.singleton = next
		return ok(deepCopyJSON(next))
	}
}

// GenericObject returns a copy of a stored generic-profile object (nil when absent), for tests.
func (s *Server) GenericObject(group, kind, accountID, id string) map[string]any {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.generic == nil {
		return nil
	}
	part := ""
	for _, m := range s.generic.models {
		if m.kind.Group == group && m.kind.Kind == kind {
			part = m.partition(func(string) string { return "" }) // partitioning headers at their defaults
		}
	}
	col, ok := s.generic.state[group+"/"+kind+"@account:"+accountID+part]
	if !ok {
		return nil
	}
	o, ok := col.items[id]
	if !ok {
		return nil
	}
	return deepCopyJSON(o.obj).(map[string]any)
}
