// Code generated by flaregen. DO NOT EDIT.

package fake

// generatedGenericKinds are the generator.yaml kinds marked `emulate: generic`. flarefake
// emulates them with the descriptor-driven generic profile (generic.go) when they are passed in
// Options.Generic; GeneratedGenericKinds returns a copy.
var generatedGenericKinds = []GenericKind{
	{
		Group: "aigateway.cloudflare.flare.dev", Kind: "AIGateway", Scope: "account",
		CreatePath:   "/accounts/{account_id}/ai-gateway/gateways",
		ItemPath:     "/accounts/{account_id}/ai-gateway/gateways/{id}",
		ListPath:     "/accounts/{account_id}/ai-gateway/gateways",
		IDField:      "id",
		UpdateMethod: "PUT",
	},
	{
		Group: "secretsstore.cloudflare.flare.dev", Kind: "SecretsStore", Scope: "account",
		CreatePath: "/accounts/{account_id}/secrets_store/stores",
		ItemPath:   "/accounts/{account_id}/secrets_store/stores/{id}",
		ListPath:   "/accounts/{account_id}/secrets_store/stores",
		IDField:    "id",
		NameField:  "name",
	},
	{
		Group: "vectorize.cloudflare.flare.dev", Kind: "VectorizeIndex", Scope: "account",
		CreatePath: "/accounts/{account_id}/vectorize/v2/indexes",
		ItemPath:   "/accounts/{account_id}/vectorize/v2/indexes/{id}",
		ListPath:   "/accounts/{account_id}/vectorize/v2/indexes",
		IDField:    "name",
		NameField:  "name",
	},
}
