// Code generated by flaregen. DO NOT EDIT.

package fake

// generatedGenericKinds are the generator.yaml kinds marked `emulate: generic`. flarefake
// emulates them with the descriptor-driven generic profile (generic.go) when they are passed in
// Options.Generic; GeneratedGenericKinds returns a copy.
var generatedGenericKinds = []GenericKind{
	{
		Group: "flare.dev", Kind: "AIGateway", Scope: "account",
		CreatePath:   "/accounts/{account_id}/ai-gateway/gateways",
		ItemPath:     "/accounts/{account_id}/ai-gateway/gateways/{id}",
		ListPath:     "/accounts/{account_id}/ai-gateway/gateways",
		IDField:      "id",
		UpdateMethod: "PUT",
	},
	{
		Group: "flare.dev", Kind: "R2Bucket", Scope: "account",
		CreatePath:   "/accounts/{account_id}/r2/buckets",
		ItemPath:     "/accounts/{account_id}/r2/buckets/{id}",
		ListPath:     "/accounts/{account_id}/r2/buckets",
		IDField:      "name",
		UpdateMethod: "PATCH",
		WriteOnly:    []string{"locationHint"},
		Headers: []GenericHeader{
			{Header: "cf-r2-jurisdiction", Field: "jurisdiction", Update: false, Default: "default"},
			{Header: "cf-r2-storage-class", Field: "storageClass", Update: true, Default: ""},
		},
		ObservedAs: map[string]string{"storageClass": "storage_class"},
		SubResources: []GenericSubResource{
			{Field: "cors", Path: "/cors", Delete: true},
		},
	},
	{
		Group: "flare.dev", Kind: "SecretsStore", Scope: "account",
		CreatePath: "/accounts/{account_id}/secrets_store/stores",
		ItemPath:   "/accounts/{account_id}/secrets_store/stores/{id}",
		ListPath:   "/accounts/{account_id}/secrets_store/stores",
		IDField:    "id",
		NameField:  "name",
	},
	{
		Group: "flare.dev", Kind: "VectorizeIndex", Scope: "account",
		CreatePath: "/accounts/{account_id}/vectorize/v2/indexes",
		ItemPath:   "/accounts/{account_id}/vectorize/v2/indexes/{id}",
		ListPath:   "/accounts/{account_id}/vectorize/v2/indexes",
		IDField:    "name",
		NameField:  "name",
		WriteOnly:  []string{"config.preset"},
	},
}
