// Package routespec reads the path templates of the pinned OpenAPI spec and renders
// internal/cfclient/zz_generated_routes.go (used by cmd genroutes and by the test that keeps the
// generated file in step with spec/openapi.json.gz).
package routespec

import (
	"bytes"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
)

// SpecPaths returns the sorted path templates of the gzipped spec.
func SpecPaths(file string) ([]string, error) {
	f, err := os.Open(file)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	zr, err := gzip.NewReader(f)
	if err != nil {
		return nil, err
	}
	var doc struct {
		Paths map[string]json.RawMessage `json:"paths"`
	}
	if err := json.NewDecoder(zr).Decode(&doc); err != nil {
		return nil, err
	}
	out := make([]string, 0, len(doc.Paths))
	for p := range doc.Paths {
		out = append(out, p)
	}
	sort.Strings(out)
	return out, nil
}

// Render returns the generated Go source listing paths.
func Render(paths []string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/cfclient/internal/genroutes from spec/openapi.json.gz. DO NOT EDIT.\n\n")
	b.WriteString("package cfclient\n\n")
	b.WriteString("// specRoutes are the path templates of the pinned OpenAPI spec (see routes.go).\n")
	b.WriteString("var specRoutes = []string{\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "\t%q,\n", p)
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}
