package flaregen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// GeneratedHeader marks every file flaregen owns; stale files carrying it are removed.
const GeneratedHeader = "Code generated by flaregen. DO NOT EDIT."

type gtKind int

const (
	gtScalar gtKind = iota
	gtStruct
	gtJSON
	gtSlice
	gtMap
	gtPtr
)

// goType is the Go shape of a Type as a field, slice element or map value.
type goType struct {
	kind gtKind
	name string // scalar Go type or struct name
	elem *goType
}

func (g *goType) String() string {
	switch g.kind {
	case gtScalar, gtStruct:
		return g.name
	case gtJSON:
		return "apiextensionsv1.JSON"
	case gtSlice:
		return "[]" + g.elem.String()
	case gtMap:
		return "map[string]" + g.elem.String()
	case gtPtr:
		return "*" + g.elem.String()
	}
	panic("unreachable")
}

// needsDeepCopy reports whether a plain assignment is not a deep copy.
func (g *goType) needsDeepCopy() bool { return g.kind != gtScalar }

type goField struct {
	GoName string
	Field  *Field
	GT     *goType
}

type goStruct struct {
	Name   string
	Doc    string
	Type   *Type
	Fields []goField
	// createRequired marks forProvider fields required only when the object may create.
	createRequired map[string]bool
}

// goPkg collects the struct definitions of one API package.
type goPkg struct {
	used    map[string]bool
	structs []*goStruct
	json    bool // imports apiextensionsv1
}

func newGoPkg() *goPkg { return &goPkg{used: map[string]bool{}} }

func (p *goPkg) uniqueName(n string) string {
	name := n
	for i := 2; p.used[name]; i++ {
		name = n + strconv.Itoa(i)
	}
	p.used[name] = true
	return name
}

// addStruct registers an object Type as a Go struct named base+suffix and
// recursively registers nested objects.
func (p *goPkg) addStruct(t *Type, base, suffix, doc string) *goStruct {
	s := &goStruct{Name: p.uniqueName(base + suffix), Type: t, Doc: doc}
	p.structs = append(p.structs, s)
	names := map[string]bool{}
	for _, f := range t.Fields {
		gn := GoName(f.JSONName)
		for i := 2; names[gn]; i++ {
			gn = GoName(f.JSONName) + strconv.Itoa(i)
		}
		names[gn] = true
		gt := p.fieldType(f.Type, base+GoName(f.JSONName), suffix, f.Required)
		s.Fields = append(s.Fields, goField{GoName: gn, Field: f, GT: gt})
	}
	return s
}

func scalarGo(k Kind) string {
	return map[Kind]string{KString: "string", KInteger: "int64", KNumber: "float64", KBool: "bool"}[k]
}

func (p *goPkg) fieldType(t *Type, base, suffix string, required bool) *goType {
	v := p.valueType(t, base, suffix)
	if required || v.kind == gtSlice || v.kind == gtMap {
		return v
	}
	return &goType{kind: gtPtr, elem: v}
}

func (p *goPkg) valueType(t *Type, base, suffix string) *goType {
	switch t.Kind {
	case KString, KInteger, KNumber, KBool:
		return &goType{kind: gtScalar, name: scalarGo(t.Kind)}
	case KObject:
		s := p.addStruct(t, base, suffix, "")
		return &goType{kind: gtStruct, name: s.Name}
	case KArray:
		return &goType{kind: gtSlice, elem: p.valueType(t.Elem, base, suffix)}
	case KMap:
		return &goType{kind: gtMap, elem: p.valueType(t.Elem, base, suffix)}
	default:
		p.json = true
		return &goType{kind: gtJSON}
	}
}

// commentLines renders a description as Go comment lines.
func commentLines(b *bytes.Buffer, indent, text string) {
	text = strings.TrimSpace(text)
	if text == "" {
		return
	}
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimRight(line, " \t\r")
		if strings.HasPrefix(strings.TrimSpace(line), "+") {
			line = "(+)" + strings.TrimPrefix(strings.TrimSpace(line), "+") // never a marker
		}
		if line == "" {
			fmt.Fprintf(b, "%s//\n", indent)
		} else {
			fmt.Fprintf(b, "%s// %s\n", indent, line)
		}
	}
}

func enumMarker(vals []any) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		switch x := v.(type) {
		case string:
			parts[i] = strconv.Quote(x)
		default:
			bs, _ := json.Marshal(x)
			parts[i] = string(bs)
		}
	}
	return strings.Join(parts, ";")
}

// markers returns kubebuilder validation markers for a field's value type.
// They document the CRD flaregen emits (flaregen does not read them back).
func markers(t *Type, prefix string) []string {
	var out []string
	add := func(format string, args ...any) {
		out = append(out, "+kubebuilder:validation:"+prefix+fmt.Sprintf(format, args...))
	}
	switch t.Kind {
	case KAny:
		out = append(out, "+kubebuilder:pruning:PreserveUnknownFields")
		if t.AnyObject {
			add("Type=object")
		} else {
			add("Schemaless")
		}
	case KArray:
		if t.MinItems != nil {
			add("MinItems=%d", *t.MinItems)
		}
		if t.MaxItems != nil {
			add("MaxItems=%d", *t.MaxItems)
		}
		if t.Elem.Kind.scalar() {
			out = append(out, markers(t.Elem, "items:")...)
		}
	case KNumber:
		add("Type=number")
	}
	if len(t.Enum) > 0 {
		add("Enum=%s", enumMarker(t.Enum))
	}
	if t.Pattern != "" {
		if strings.Contains(t.Pattern, "`") {
			add("Pattern=%s", strconv.Quote(t.Pattern))
		} else {
			add("Pattern=`%s`", t.Pattern)
		}
	}
	if t.MinLength != nil {
		add("MinLength=%d", *t.MinLength)
	}
	if t.MaxLength != nil {
		add("MaxLength=%d", *t.MaxLength)
	}
	if t.Minimum != nil {
		add("Minimum=%s", strconv.FormatFloat(*t.Minimum, 'f', -1, 64))
		if t.ExclusiveMinimum {
			add("ExclusiveMinimum=true")
		}
	}
	if t.Maximum != nil {
		add("Maximum=%s", strconv.FormatFloat(*t.Maximum, 'f', -1, 64))
		if t.ExclusiveMaximum {
			add("ExclusiveMaximum=true")
		}
	}
	return out
}

func writeStruct(b *bytes.Buffer, s *goStruct) {
	if s.Doc != "" {
		commentLines(b, "", s.Doc)
	} else {
		fmt.Fprintf(b, "// %s is a nested object of the Cloudflare API schema.\n", s.Name)
		if s.Type.Description != "" {
			b.WriteString("//\n")
			commentLines(b, "", s.Type.Description)
		}
	}
	fmt.Fprintf(b, "type %s struct {\n", s.Name)
	for _, f := range s.Fields {
		desc := f.Field.Description
		if desc == "" {
			desc = f.Field.Type.Description
		}
		commentLines(b, "\t", desc)
		if f.Field.Deprecated {
			b.WriteString("\t// (deprecated in the Cloudflare API)\n")
		}
		for _, m := range markers(f.Field.Type, "") {
			fmt.Fprintf(b, "\t// %s\n", m)
		}
		if s.createRequired[f.Field.JSONName] {
			b.WriteString("\t// Required unless managementPolicies exclude Create (CEL rule on the spec).\n")
		}
		tag := f.Field.JSONName
		if f.Field.Required {
			b.WriteString("\t// +kubebuilder:validation:Required\n")
		} else {
			b.WriteString("\t// +optional\n")
			tag += ",omitempty"
		}
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", f.GoName, f.GT, tag)
	}
	b.WriteString("}\n\n")
}

// kindGo is the per-kind part of an API package.
type kindGo struct {
	m      *KindModel
	params *goStruct
	obs    *goStruct
}

// emitTypesFile renders <kind>_types.go.
func emitTypesFile(module string, k *kindGo, structs []*goStruct) ([]byte, error) {
	m := k.m
	var b bytes.Buffer
	fmt.Fprintf(&b, "// %s\n\npackage %s\n\n", GeneratedHeader, m.Version)
	b.WriteString("import (\n")
	if usesJSON(structs) {
		b.WriteString("\tapiextensionsv1 \"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1\"\n")
	}
	b.WriteString("\tmetav1 \"k8s.io/apimachinery/pkg/apis/meta/v1\"\n\n")
	fmt.Fprintf(&b, "\tcommonv1alpha1 %q\n)\n\n", module+"/api/common/v1alpha1")

	k.params.createRequired = map[string]bool{}
	for _, f := range m.CreateRequired {
		k.params.createRequired[f] = true
	}
	for _, s := range structs {
		writeStruct(&b, s)
	}
	r := m.Resource
	d := m.Descriptor
	fmt.Fprintf(&b, "// %sSpec defines the desired state of a %s.\n", m.Kind, m.Kind)
	for _, f := range m.CreateRequired {
		if CELAccessible(f) {
			r := createRequiredRules([]string{f})[0]
			fmt.Fprintf(&b, "// +kubebuilder:validation:XValidation:rule=%q,message=%q\n", r.Rule, r.Message)
		}
	}
	for _, r := range specRules(m) {
		fmt.Fprintf(&b, "// +kubebuilder:validation:XValidation:rule=%q,message=%q\n", r.Rule, r.Message)
	}
	fmt.Fprintf(&b, "type %sSpec struct {\n\tcommonv1alpha1.ResourceSpec `json:\",inline\"`\n", m.Kind)
	b.WriteString("\t// ForProvider holds the Cloudflare API fields, named exactly as in the API.\n")
	fmt.Fprintf(&b, "\tForProvider %s `json:\"forProvider\"`\n}\n\n", k.params.Name)
	fmt.Fprintf(&b, "// %sStatus defines the observed state of a %s.\n", m.Kind, m.Kind)
	fmt.Fprintf(&b, "type %sStatus struct {\n\tcommonv1alpha1.ResourceStatus `json:\",inline\"`\n", m.Kind)
	b.WriteString("\t// AtProvider is the resource as last read from the Cloudflare API.\n\t// +optional\n")
	fmt.Fprintf(&b, "\tAtProvider %s `json:\"atProvider,omitempty\"`\n}\n\n", k.obs.Name)

	fmt.Fprintf(&b, "// %s is a Cloudflare %s (x-fern-sdk-group-name %q).\n", m.Kind, strings.ReplaceAll(r.FernGroup, ".", " "), r.FernGroup)
	b.WriteString("//\n")
	if r.Singleton {
		fmt.Fprintf(&b, "// Singleton settings object at %s (%s scope).\n", d.ItemPath, d.Scope)
	} else {
		fmt.Fprintf(&b, "// Created at %s, managed at %s (%s scope).\n", d.CreatePath, d.ItemPath, d.Scope)
	}
	fmt.Fprintf(&b, "// Default deletion policy: %s.\n", d.DefaultDeletionPolicy)
	if len(d.Immutable) > 0 {
		fmt.Fprintf(&b, "// Immutable fields: %s.\n", strings.Join(d.Immutable, ", "))
	}
	if len(d.WriteOnly) > 0 {
		fmt.Fprintf(&b, "// Write-only fields: %s.\n", strings.Join(d.WriteOnly, ", "))
	}
	b.WriteString("//\n// +kubebuilder:object:root=true\n// +kubebuilder:subresource:status\n")
	res := "// +kubebuilder:resource:scope=Namespaced"
	if len(m.ShortNames) > 0 {
		res += ",shortName=" + strings.Join(m.ShortNames, ";")
	}
	fmt.Fprintf(&b, "%s,categories={%s}\n", res, strings.Join(categories(m), ","))
	for _, r := range rootRules(m) {
		fmt.Fprintf(&b, "// +kubebuilder:validation:XValidation:rule=%q,message=%q\n", r.Rule, r.Message)
	}
	for _, c := range printerColumns(m) {
		fmt.Fprintf(&b, "// +kubebuilder:printcolumn:name=%q,type=%q,JSONPath=%q", c.Name, c.Type, c.JSONPath)
		if c.Priority != 0 {
			fmt.Fprintf(&b, ",priority=%d", c.Priority)
		}
		if c.Description != "" {
			fmt.Fprintf(&b, ",description=%q", c.Description)
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "type %s struct {\n\tmetav1.TypeMeta   `json:\",inline\"`\n\tmetav1.ObjectMeta `json:\"metadata,omitempty\"`\n\n", m.Kind)
	fmt.Fprintf(&b, "\tSpec   %sSpec   `json:\"spec\"`\n\t// +optional\n\tStatus %sStatus `json:\"status,omitempty\"`\n}\n\n", m.Kind, m.Kind)
	fmt.Fprintf(&b, "// GetResourceSpec implements commonv1alpha1.Managed.\nfunc (o *%s) GetResourceSpec() *commonv1alpha1.ResourceSpec { return &o.Spec.ResourceSpec }\n\n", m.Kind)
	fmt.Fprintf(&b, "// GetResourceStatus implements commonv1alpha1.Managed.\nfunc (o *%s) GetResourceStatus() *commonv1alpha1.ResourceStatus { return &o.Status.ResourceStatus }\n\n", m.Kind)
	fmt.Fprintf(&b, "// %sList is a list of %s.\n//\n// +kubebuilder:object:root=true\n", m.Kind, m.Kind)
	fmt.Fprintf(&b, "type %sList struct {\n\tmetav1.TypeMeta `json:\",inline\"`\n\tmetav1.ListMeta `json:\"metadata,omitempty\"`\n\tItems []%s `json:\"items\"`\n}\n\n", m.Kind, m.Kind)
	fmt.Fprintf(&b, "var _ commonv1alpha1.Managed = &%s{}\n", m.Kind)
	return formatGo(b.Bytes())
}

func usesJSON(structs []*goStruct) bool {
	var has func(g *goType) bool
	has = func(g *goType) bool {
		return g.kind == gtJSON || (g.elem != nil && has(g.elem))
	}
	for _, s := range structs {
		for _, f := range s.Fields {
			if has(f.GT) {
				return true
			}
		}
	}
	return false
}

func formatGo(src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("gofmt generated code: %w\n%s", err, src)
	}
	return out, nil
}

// emitGroupVersion renders groupversion_info.go.
func emitGroupVersion(product, group, version string, fernGroups, kinds []string) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// %s\n\n", GeneratedHeader)
	sort.Strings(kinds)
	fmt.Fprintf(&b, "// Package %s contains the %s kinds of the %s API group (product %s),\n", version, strings.Join(kinds, ", "), group, product)
	fmt.Fprintf(&b, "// generated by cmd/flaregen from the Cloudflare OpenAPI operations with\n// x-fern-sdk-group-name %s.\n", strings.Join(fernGroups, ", "))
	b.WriteString("//\n// Every flare-operator kind shares the API group; other packages under api/ register\n// their kinds in the same GroupVersion.\n")
	b.WriteString("//\n// flaregen emits the deepcopy functions and the CRD YAML itself (make generate-crds);\n")
	b.WriteString("// controller-gen must not be run over this package, and the package markers keep\n// it out of controller-gen's CRD and object generators.\n//\n")
	b.WriteString("// +kubebuilder:skip\n// +kubebuilder:object:generate=false\n")
	fmt.Fprintf(&b, "// +groupName=%s\npackage %s\n\n", group, version)
	b.WriteString("import (\n\tmetav1 \"k8s.io/apimachinery/pkg/apis/meta/v1\"\n\t\"k8s.io/apimachinery/pkg/runtime\"\n\t\"k8s.io/apimachinery/pkg/runtime/schema\"\n)\n\n")
	b.WriteString("var (\n\t// GroupVersion is the API group and version of this package.\n")
	fmt.Fprintf(&b, "\tGroupVersion = schema.GroupVersion{Group: %q, Version: %q}\n\n", group, version)
	b.WriteString("\t// SchemeBuilder registers this package's kinds.\n\tSchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)\n\n")
	b.WriteString("\t// AddToScheme adds this package's kinds to a scheme.\n\tAddToScheme = SchemeBuilder.AddToScheme\n)\n\n")
	b.WriteString("func addKnownTypes(s *runtime.Scheme) error {\n\ts.AddKnownTypes(GroupVersion")
	sort.Strings(kinds)
	for _, k := range kinds {
		fmt.Fprintf(&b, ",\n\t\t&%s{}, &%sList{}", k, k)
	}
	b.WriteString(",\n\t)\n\tmetav1.AddToGroupVersion(s, GroupVersion)\n\treturn nil\n}\n")
	return formatGo(b.Bytes())
}

// emitDeepCopy renders zz_generated.deepcopy.go for all structs and kinds of a package.
func emitDeepCopy(version string, structs []*goStruct, kinds []string) ([]byte, error) {
	var b bytes.Buffer
	sorted := append([]*goStruct(nil), structs...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	for _, s := range sorted {
		fmt.Fprintf(&b, "// DeepCopyInto copies the receiver into out. in must be non-nil.\nfunc (in *%s) DeepCopyInto(out *%s) {\n\t*out = *in\n", s.Name, s.Name)
		for _, f := range s.Fields {
			if f.GT.needsDeepCopy() {
				copyStmt(&b, f.GT, "in."+f.GoName, "out."+f.GoName, 0)
			}
		}
		b.WriteString("}\n\n")
		deepCopyFunc(&b, s.Name)
	}
	sort.Strings(kinds)
	for _, k := range kinds {
		fmt.Fprintf(&b, "// DeepCopyInto copies the receiver into out. in must be non-nil.\nfunc (in *%sSpec) DeepCopyInto(out *%sSpec) {\n\t*out = *in\n", k, k)
		b.WriteString("\tin.ResourceSpec.DeepCopyInto(&out.ResourceSpec)\n\tin.ForProvider.DeepCopyInto(&out.ForProvider)\n}\n\n")
		deepCopyFunc(&b, k+"Spec")
		fmt.Fprintf(&b, "// DeepCopyInto copies the receiver into out. in must be non-nil.\nfunc (in *%sStatus) DeepCopyInto(out *%sStatus) {\n\t*out = *in\n", k, k)
		b.WriteString("\tin.ResourceStatus.DeepCopyInto(&out.ResourceStatus)\n\tin.AtProvider.DeepCopyInto(&out.AtProvider)\n}\n\n")
		deepCopyFunc(&b, k+"Status")
		fmt.Fprintf(&b, "// DeepCopyInto copies the receiver into out. in must be non-nil.\nfunc (in *%s) DeepCopyInto(out *%s) {\n\t*out = *in\n", k, k)
		b.WriteString("\tout.TypeMeta = in.TypeMeta\n\tin.ObjectMeta.DeepCopyInto(&out.ObjectMeta)\n\tin.Spec.DeepCopyInto(&out.Spec)\n\tin.Status.DeepCopyInto(&out.Status)\n}\n\n")
		deepCopyFunc(&b, k)
		deepCopyObject(&b, k)
		fmt.Fprintf(&b, "// DeepCopyInto copies the receiver into out. in must be non-nil.\nfunc (in *%sList) DeepCopyInto(out *%sList) {\n\t*out = *in\n", k, k)
		b.WriteString("\tout.TypeMeta = in.TypeMeta\n\tin.ListMeta.DeepCopyInto(&out.ListMeta)\n")
		fmt.Fprintf(&b, "\tif in.Items != nil {\n\t\tin, out := &in.Items, &out.Items\n\t\t*out = make([]%s, len(*in))\n\t\tfor i := range *in {\n\t\t\t(*in)[i].DeepCopyInto(&(*out)[i])\n\t\t}\n\t}\n}\n\n", k)
		deepCopyFunc(&b, k+"List")
		deepCopyObject(&b, k+"List")
	}
	// apiextensionsv1 is imported only when the copy code names it (a JSON value
	// field is copied with a method call and never names the package).
	var head bytes.Buffer
	fmt.Fprintf(&head, "// %s\n\npackage %s\n\nimport (\n", GeneratedHeader, version)
	if bytes.Contains(b.Bytes(), []byte("apiextensionsv1.")) {
		head.WriteString("\tapiextensionsv1 \"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1\"\n")
	}
	head.WriteString("\t\"k8s.io/apimachinery/pkg/runtime\"\n)\n\n")
	return formatGo(append(head.Bytes(), b.Bytes()...))
}

func deepCopyFunc(b *bytes.Buffer, name string) {
	fmt.Fprintf(b, "// DeepCopy creates a deep copy of the receiver.\nfunc (in *%s) DeepCopy() *%s {\n\tif in == nil {\n\t\treturn nil\n\t}\n\tout := new(%s)\n\tin.DeepCopyInto(out)\n\treturn out\n}\n\n", name, name, name)
}

func deepCopyObject(b *bytes.Buffer, name string) {
	fmt.Fprintf(b, "// DeepCopyObject implements runtime.Object.\nfunc (in *%s) DeepCopyObject() runtime.Object {\n\tif c := in.DeepCopy(); c != nil {\n\t\treturn c\n\t}\n\treturn nil\n}\n\n", name)
}

// copyStmt writes statements that deep-copy inExpr into outExpr (both addressable, same type g).
func copyStmt(b *bytes.Buffer, g *goType, inExpr, outExpr string, depth int) {
	idx := fmt.Sprintf("i%d", depth)
	switch g.kind {
	case gtScalar:
		fmt.Fprintf(b, "%s = %s\n", outExpr, inExpr)
	case gtStruct, gtJSON:
		fmt.Fprintf(b, "%s.DeepCopyInto(&%s)\n", inExpr, outExpr)
	case gtPtr:
		fmt.Fprintf(b, "if %s != nil {\nin, out := &%s, &%s\n*out = new(%s)\n", inExpr, inExpr, outExpr, g.elem)
		if g.elem.kind == gtScalar {
			b.WriteString("**out = **in\n")
		} else {
			b.WriteString("(*in).DeepCopyInto(*out)\n")
		}
		b.WriteString("}\n")
	case gtSlice:
		fmt.Fprintf(b, "if %s != nil {\nin, out := &%s, &%s\n*out = make(%s, len(*in))\n", inExpr, inExpr, outExpr, g)
		if g.elem.kind == gtScalar {
			b.WriteString("copy(*out, *in)\n")
		} else {
			fmt.Fprintf(b, "for %s := range *in {\n", idx)
			copyStmt(b, g.elem, "(*in)["+idx+"]", "(*out)["+idx+"]", depth+1)
			b.WriteString("}\n")
		}
		b.WriteString("}\n")
	case gtMap:
		fmt.Fprintf(b, "if %s != nil {\nin, out := &%s, &%s\n*out = make(%s, len(*in))\n", inExpr, inExpr, outExpr, g)
		key, val := fmt.Sprintf("k%d", depth), fmt.Sprintf("v%d", depth)
		if g.elem.kind == gtScalar {
			fmt.Fprintf(b, "for %s, %s := range *in {\n(*out)[%s] = %s\n}\n", key, val, key, val)
		} else {
			outVal := fmt.Sprintf("o%d", depth)
			fmt.Fprintf(b, "for %s, %s := range *in {\nvar %s %s\n", key, val, outVal, g.elem)
			copyStmt(b, g.elem, val, outVal, depth+1)
			fmt.Fprintf(b, "(*out)[%s] = %s\n}\n", key, outVal)
		}
		b.WriteString("}\n")
	}
}
