// Package v1alpha1 contains the workersvpc.cloudflare.flare.dev API group
// (x-fern-sdk-group-name "workers-vpc.services"): VPCService, a Workers VPC connectivity
// service that routes Worker traffic through a Tunnel to a private backend.
//
// These types are hand-written (not generated by cmd/flaregen); `make generate manifests`
// (controller-gen) produces their deepcopy methods and CRD.
//
// +kubebuilder:object:generate=true
// +groupName=workersvpc.cloudflare.flare.dev
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

var (
	// GroupVersion is the group version used to register these objects.
	GroupVersion = schema.GroupVersion{Group: "workersvpc.cloudflare.flare.dev", Version: "v1alpha1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme.
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)
