//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/chenhunghan/flare-operator/api/common/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCService) DeepCopyInto(out *VPCService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCService.
func (in *VPCService) DeepCopy() *VPCService {
	if in == nil {
		return nil
	}
	out := new(VPCService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCServiceHost) DeepCopyInto(out *VPCServiceHost) {
	*out = *in
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(string)
		**out = **in
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(VPCServiceNetwork)
		(*in).DeepCopyInto(*out)
	}
	if in.ResolverNetwork != nil {
		in, out := &in.ResolverNetwork, &out.ResolverNetwork
		*out = new(VPCServiceResolverNetwork)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCServiceHost.
func (in *VPCServiceHost) DeepCopy() *VPCServiceHost {
	if in == nil {
		return nil
	}
	out := new(VPCServiceHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCServiceHostObservation) DeepCopyInto(out *VPCServiceHostObservation) {
	*out = *in
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(string)
		**out = **in
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(VPCServiceNetworkObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ResolverNetwork != nil {
		in, out := &in.ResolverNetwork, &out.ResolverNetwork
		*out = new(VPCServiceNetworkObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCServiceHostObservation.
func (in *VPCServiceHostObservation) DeepCopy() *VPCServiceHostObservation {
	if in == nil {
		return nil
	}
	out := new(VPCServiceHostObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCServiceList) DeepCopyInto(out *VPCServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCServiceList.
func (in *VPCServiceList) DeepCopy() *VPCServiceList {
	if in == nil {
		return nil
	}
	out := new(VPCServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCServiceNetwork) DeepCopyInto(out *VPCServiceNetwork) {
	*out = *in
	if in.TunnelID != nil {
		in, out := &in.TunnelID, &out.TunnelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCServiceNetwork.
func (in *VPCServiceNetwork) DeepCopy() *VPCServiceNetwork {
	if in == nil {
		return nil
	}
	out := new(VPCServiceNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCServiceNetworkObservation) DeepCopyInto(out *VPCServiceNetworkObservation) {
	*out = *in
	if in.ResolverIPs != nil {
		in, out := &in.ResolverIPs, &out.ResolverIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCServiceNetworkObservation.
func (in *VPCServiceNetworkObservation) DeepCopy() *VPCServiceNetworkObservation {
	if in == nil {
		return nil
	}
	out := new(VPCServiceNetworkObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCServiceObservation) DeepCopyInto(out *VPCServiceObservation) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(VPCServiceHostObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(int32)
		**out = **in
	}
	if in.HTTPSPort != nil {
		in, out := &in.HTTPSPort, &out.HTTPSPort
		*out = new(int32)
		**out = **in
	}
	if in.TCPPort != nil {
		in, out := &in.TCPPort, &out.TCPPort
		*out = new(int32)
		**out = **in
	}
	if in.AppProtocol != nil {
		in, out := &in.AppProtocol, &out.AppProtocol
		*out = new(string)
		**out = **in
	}
	if in.TLSSettings != nil {
		in, out := &in.TLSSettings, &out.TLSSettings
		*out = new(VPCServiceTLSSettings)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCServiceObservation.
func (in *VPCServiceObservation) DeepCopy() *VPCServiceObservation {
	if in == nil {
		return nil
	}
	out := new(VPCServiceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCServiceParameters) DeepCopyInto(out *VPCServiceParameters) {
	*out = *in
	in.Host.DeepCopyInto(&out.Host)
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(int32)
		**out = **in
	}
	if in.HTTPSPort != nil {
		in, out := &in.HTTPSPort, &out.HTTPSPort
		*out = new(int32)
		**out = **in
	}
	if in.TCPPort != nil {
		in, out := &in.TCPPort, &out.TCPPort
		*out = new(int32)
		**out = **in
	}
	if in.AppProtocol != nil {
		in, out := &in.AppProtocol, &out.AppProtocol
		*out = new(string)
		**out = **in
	}
	if in.TLSSettings != nil {
		in, out := &in.TLSSettings, &out.TLSSettings
		*out = new(VPCServiceTLSSettings)
		**out = **in
	}
	if in.TunnelRef != nil {
		in, out := &in.TunnelRef, &out.TunnelRef
		*out = new(commonv1alpha1.LocalRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCServiceParameters.
func (in *VPCServiceParameters) DeepCopy() *VPCServiceParameters {
	if in == nil {
		return nil
	}
	out := new(VPCServiceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCServiceResolverNetwork) DeepCopyInto(out *VPCServiceResolverNetwork) {
	*out = *in
	if in.TunnelID != nil {
		in, out := &in.TunnelID, &out.TunnelID
		*out = new(string)
		**out = **in
	}
	if in.ResolverIPs != nil {
		in, out := &in.ResolverIPs, &out.ResolverIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCServiceResolverNetwork.
func (in *VPCServiceResolverNetwork) DeepCopy() *VPCServiceResolverNetwork {
	if in == nil {
		return nil
	}
	out := new(VPCServiceResolverNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCServiceSpec) DeepCopyInto(out *VPCServiceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.ForProvider != nil {
		in, out := &in.ForProvider, &out.ForProvider
		*out = new(VPCServiceParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCServiceSpec.
func (in *VPCServiceSpec) DeepCopy() *VPCServiceSpec {
	if in == nil {
		return nil
	}
	out := new(VPCServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCServiceStatus) DeepCopyInto(out *VPCServiceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCServiceStatus.
func (in *VPCServiceStatus) DeepCopy() *VPCServiceStatus {
	if in == nil {
		return nil
	}
	out := new(VPCServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCServiceTLSSettings) DeepCopyInto(out *VPCServiceTLSSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCServiceTLSSettings.
func (in *VPCServiceTLSSettings) DeepCopy() *VPCServiceTLSSettings {
	if in == nil {
		return nil
	}
	out := new(VPCServiceTLSSettings)
	in.DeepCopyInto(out)
	return out
}
