// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
)

// WidgetSettingsParameters are the configurable fields of a WidgetSettings: the request
// bodies of PATCH /zones/{zone_identifier}/widget_settings.
type WidgetSettingsParameters struct {
	// Whether widgets are on.
	// +optional
	Enabled *bool `json:"enabled,omitempty"`
	// +kubebuilder:validation:Enum=1;2;3
	// +optional
	Level *int64 `json:"level,omitempty"`
}

// WidgetSettingsObservation is the WidgetSettings as returned by GET /zones/{zone_identifier}/widget_settings.
type WidgetSettingsObservation struct {
	// Whether widgets are on.
	// +optional
	Enabled *bool `json:"enabled,omitempty"`
	// +optional
	Level *int64 `json:"level,omitempty"`
	// +optional
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// WidgetSettingsSpec defines the desired state of a WidgetSettings.
// +kubebuilder:validation:XValidation:rule="size(self.accountRef.name) > 0 && size(self.accountRef.name) <= 253",message="accountRef.name must name a CloudflareAccount in this namespace (1-253 characters)"
// +kubebuilder:validation:XValidation:rule="has(self.zoneRef.id) != has(self.zoneRef.name)",message="zoneRef needs exactly one of id or name"
type WidgetSettingsSpec struct {
	commonv1alpha1.ResourceSpec `json:",inline"`
	// ForProvider holds the Cloudflare API fields, named exactly as in the API.
	ForProvider WidgetSettingsParameters `json:"forProvider"`
}

// WidgetSettingsStatus defines the observed state of a WidgetSettings.
type WidgetSettingsStatus struct {
	commonv1alpha1.ResourceStatus `json:",inline"`
	// AtProvider is the resource as last read from the Cloudflare API.
	// +optional
	AtProvider WidgetSettingsObservation `json:"atProvider,omitempty"`
}

// WidgetSettings is a Cloudflare widget_tools settings (x-fern-sdk-group-name "widget_tools.settings").
//
// Singleton settings object at /zones/{zone_id}/widget_settings (zone scope).
// Default deletion policy: Orphan.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={cloudflare,managed,widgettools}
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || self.spec.accountRef.name == oldSelf.spec.accountRef.name",message="spec.accountRef is immutable once the resource exists (status.id is set): the resource lives in that account. To move it, delete this object (deletionPolicy Orphan keeps the resource) and create a new one"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type WidgetSettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec WidgetSettingsSpec `json:"spec"`
	// +optional
	Status WidgetSettingsStatus `json:"status,omitempty"`
}

// GetResourceSpec implements commonv1alpha1.Managed.
func (o *WidgetSettings) GetResourceSpec() *commonv1alpha1.ResourceSpec { return &o.Spec.ResourceSpec }

// GetResourceStatus implements commonv1alpha1.Managed.
func (o *WidgetSettings) GetResourceStatus() *commonv1alpha1.ResourceStatus {
	return &o.Status.ResourceStatus
}

// WidgetSettingsList is a list of WidgetSettings.
//
// +kubebuilder:object:root=true
type WidgetSettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WidgetSettings `json:"items"`
}

var _ commonv1alpha1.Managed = &WidgetSettings{}
