// Package kinds registers a generic reconciler (internal/generic) for every kind generated by
// cmd/flaregen (internal/generic/descriptors) with the controller registry, plus their API
// schemes. Blank-import it from cmd/manager; tests import it to run the controllers.
//
// Controller names are the lower-case kinds (kvnamespace, queue, d1database), usable with the
// manager's --controller flag and testenv.ManagerOptions.Controllers. The RBAC markers for the
// kinds are generated into zz_generated.rbac.go.
package kinds

import (
	"strings"

	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"flare.dev/operator/internal/controller"
	"flare.dev/operator/internal/generic"
	"flare.dev/operator/internal/generic/descriptors"
	"flare.dev/operator/internal/reconcile"
)

// SchemeRegistration is the registry name of the scheme-only registration of all generated API
// groups.
const SchemeRegistration = "generated-kinds-schemes"

func init() {
	controller.Register(controller.Registration{Name: SchemeRegistration, AddToScheme: descriptors.AddToScheme})
	for _, e := range descriptors.Entries() {
		e := e
		controller.Register(controller.Registration{
			Name: Name(e),
			Setup: func(mgr ctrl.Manager, d controller.Deps) error {
				return NewReconciler(e, mgr.GetClient(), d).SetupWithManager(mgr, Name(e))
			},
		})
	}
}

// Name is the controller (and registration) name of a generated kind.
func Name(e descriptors.Entry) string { return strings.ToLower(e.Kind) }

// Names returns the controller names of every generated kind.
func Names() []string {
	var out []string
	for _, e := range descriptors.Entries() {
		out = append(out, Name(e))
	}
	return out
}

// NewReconciler builds the generic reconciler of a generated kind from the shared runtime.
func NewReconciler(e descriptors.Entry, c client.Client, d controller.Deps) *generic.Reconciler {
	return &generic.Reconciler{
		Client:      c,
		Accounts:    d.Accounts,
		Tagger:      d.Tagger,
		ClusterName: d.ClusterName,
		// 0 → generic.DefaultPollInterval
		PollInterval: d.PollInterval,
		Descriptor:   e.Descriptor,
		New: func() reconcile.ManagedObject {
			return e.New().(reconcile.ManagedObject)
		},
		NewList: func() client.ObjectList {
			return e.NewList().(client.ObjectList)
		},
	}
}
