// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
)

// SecretsStoreParameters are the configurable fields of a SecretsStore: the request
// bodies of POST /accounts/{account_id}/secrets_store/stores.
type SecretsStoreParameters struct {
	// The name of the store.
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	Name *string `json:"name,omitempty"`
}

// SecretsStoreObservation is the SecretsStore as returned by GET /accounts/{account_id}/secrets_store/stores/{store_id}.
type SecretsStoreObservation struct {
	// Account Identifier.
	// +optional
	AccountID *string `json:"account_id,omitempty"`
	// When the secret was created.
	// +optional
	Created *string `json:"created,omitempty"`
	// Store Identifier.
	// +optional
	ID *string `json:"id,omitempty"`
	// When the secret was modified.
	// +optional
	Modified *string `json:"modified,omitempty"`
	// The name of the store.
	// +optional
	Name *string `json:"name,omitempty"`
}

// SecretsStoreSpec defines the desired state of a SecretsStore.
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.name))",message="forProvider.name is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="size(self.accountRef.name) > 0 && size(self.accountRef.name) <= 253",message="accountRef.name must name a CloudflareAccount in this namespace (1-253 characters)"
type SecretsStoreSpec struct {
	commonv1alpha1.ResourceSpec `json:",inline"`
	// ForProvider holds the Cloudflare API fields, named exactly as in the API.
	ForProvider SecretsStoreParameters `json:"forProvider"`
}

// SecretsStoreStatus defines the observed state of a SecretsStore.
type SecretsStoreStatus struct {
	commonv1alpha1.ResourceStatus `json:",inline"`
	// AtProvider is the resource as last read from the Cloudflare API.
	// +optional
	AtProvider SecretsStoreObservation `json:"atProvider,omitempty"`
}

// SecretsStore is a Cloudflare secrets-store stores (x-fern-sdk-group-name "secrets-store.stores").
//
// Created at /accounts/{account_id}/secrets_store/stores, managed at /accounts/{account_id}/secrets_store/stores/{id} (account scope).
// Default deletion policy: Delete.
// Immutable fields: name.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=cfstore,categories={cloudflare,managed,secretsstore}
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || self.spec.accountRef.name == oldSelf.spec.accountRef.name",message="spec.accountRef is immutable once the resource exists (status.id is set): the resource lives in that account. To move it, delete this object (deletionPolicy Orphan keeps the resource) and create a new one"
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.name) || !has(self.spec.forProvider) || !has(self.spec.forProvider.name) || self.spec.forProvider.name == oldSelf.spec.forProvider.name || (has(oldSelf.status.atProvider) && has(oldSelf.status.atProvider.name) && oldSelf.status.atProvider.name == self.spec.forProvider.name)",message="forProvider.name is immutable once the resource exists (status.id is set): recreate the object to change it, or set it to the value Cloudflare reports (status.atProvider.name)"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="STORE",type="string",JSONPath=".status.atProvider.name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type SecretsStore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec SecretsStoreSpec `json:"spec"`
	// +optional
	Status SecretsStoreStatus `json:"status,omitempty"`
}

// GetResourceSpec implements commonv1alpha1.Managed.
func (o *SecretsStore) GetResourceSpec() *commonv1alpha1.ResourceSpec { return &o.Spec.ResourceSpec }

// GetResourceStatus implements commonv1alpha1.Managed.
func (o *SecretsStore) GetResourceStatus() *commonv1alpha1.ResourceStatus {
	return &o.Status.ResourceStatus
}

// SecretsStoreList is a list of SecretsStore.
//
// +kubebuilder:object:root=true
type SecretsStoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecretsStore `json:"items"`
}

var _ commonv1alpha1.Managed = &SecretsStore{}
