// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SecretsStoreObservation) DeepCopyInto(out *SecretsStoreObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Modified != nil {
		in, out := &in.Modified, &out.Modified
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *SecretsStoreObservation) DeepCopy() *SecretsStoreObservation {
	if in == nil {
		return nil
	}
	out := new(SecretsStoreObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SecretsStoreParameters) DeepCopyInto(out *SecretsStoreParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *SecretsStoreParameters) DeepCopy() *SecretsStoreParameters {
	if in == nil {
		return nil
	}
	out := new(SecretsStoreParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SecretsStoreSpec) DeepCopyInto(out *SecretsStoreSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *SecretsStoreSpec) DeepCopy() *SecretsStoreSpec {
	if in == nil {
		return nil
	}
	out := new(SecretsStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SecretsStoreStatus) DeepCopyInto(out *SecretsStoreStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *SecretsStoreStatus) DeepCopy() *SecretsStoreStatus {
	if in == nil {
		return nil
	}
	out := new(SecretsStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SecretsStore) DeepCopyInto(out *SecretsStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of the receiver.
func (in *SecretsStore) DeepCopy() *SecretsStore {
	if in == nil {
		return nil
	}
	out := new(SecretsStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *SecretsStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SecretsStoreList) DeepCopyInto(out *SecretsStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretsStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *SecretsStoreList) DeepCopy() *SecretsStoreList {
	if in == nil {
		return nil
	}
	out := new(SecretsStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *SecretsStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
