// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
)

// KVNamespaceParameters are the configurable fields of a KVNamespace: the request
// bodies of POST /accounts/{account_id}/storage/kv/namespaces and PUT /accounts/{account_id}/storage/kv/namespaces/{namespace_id}.
type KVNamespaceParameters struct {
	// Specify the jurisdiction to restrict the KV namespace to durably store data within. Can only be set at namespace creation time.
	// +kubebuilder:validation:Enum="eu";"fedramp";"us"
	// +optional
	Jurisdiction *string `json:"jurisdiction,omitempty"`
	// Human-readable string name for a Workers KV namespace.
	// +kubebuilder:validation:MaxLength=512
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	Title *string `json:"title,omitempty"`
}

// KVNamespaceObservation is the KVNamespace as returned by GET /accounts/{account_id}/storage/kv/namespaces/{namespace_id}.
type KVNamespaceObservation struct {
	// ID of the Workers KV namespace.
	// +optional
	ID *string `json:"id,omitempty"`
	// Specify the jurisdiction to restrict the KV namespace to durably store data within. Can only be set at namespace creation time.
	// +optional
	Jurisdiction *string `json:"jurisdiction,omitempty"`
	// True if keys written on the URL will be URL-decoded before storing. For example, if set to "true", a key written on the URL as "%3F" will be stored as "?".
	// +optional
	SupportsURLEncoding *bool `json:"supports_url_encoding,omitempty"`
	// Human-readable string name for a Workers KV namespace.
	// +optional
	Title *string `json:"title,omitempty"`
}

// KVNamespaceSpec defines the desired state of a KVNamespace.
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.title))",message="forProvider.title is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="size(self.accountRef.name) > 0 && size(self.accountRef.name) <= 253",message="accountRef.name must name a CloudflareAccount in this namespace (1-253 characters)"
type KVNamespaceSpec struct {
	commonv1alpha1.ResourceSpec `json:",inline"`
	// ForProvider holds the Cloudflare API fields, named exactly as in the API.
	ForProvider KVNamespaceParameters `json:"forProvider"`
}

// KVNamespaceStatus defines the observed state of a KVNamespace.
type KVNamespaceStatus struct {
	commonv1alpha1.ResourceStatus `json:",inline"`
	// AtProvider is the resource as last read from the Cloudflare API.
	// +optional
	AtProvider KVNamespaceObservation `json:"atProvider,omitempty"`
}

// KVNamespace is a Cloudflare kv namespaces (x-fern-sdk-group-name "kv.namespaces").
//
// Created at /accounts/{account_id}/storage/kv/namespaces, managed at /accounts/{account_id}/storage/kv/namespaces/{id} (account scope).
// Default deletion policy: Orphan.
// Immutable fields: jurisdiction.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=cfkv,categories={cloudflare,managed,kv}
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.jurisdiction) || !has(self.spec.forProvider) || !has(self.spec.forProvider.jurisdiction) || self.spec.forProvider.jurisdiction == oldSelf.spec.forProvider.jurisdiction || (has(oldSelf.status.atProvider) && has(oldSelf.status.atProvider.jurisdiction) && oldSelf.status.atProvider.jurisdiction == self.spec.forProvider.jurisdiction)",message="forProvider.jurisdiction is immutable once the resource exists (status.id is set): recreate the object to change it, or set it to the value Cloudflare reports (status.atProvider.jurisdiction)"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="TITLE",type="string",JSONPath=".status.atProvider.title"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type KVNamespace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec KVNamespaceSpec `json:"spec"`
	// +optional
	Status KVNamespaceStatus `json:"status,omitempty"`
}

// GetResourceSpec implements commonv1alpha1.Managed.
func (o *KVNamespace) GetResourceSpec() *commonv1alpha1.ResourceSpec { return &o.Spec.ResourceSpec }

// GetResourceStatus implements commonv1alpha1.Managed.
func (o *KVNamespace) GetResourceStatus() *commonv1alpha1.ResourceStatus {
	return &o.Status.ResourceStatus
}

// KVNamespaceList is a list of KVNamespace.
//
// +kubebuilder:object:root=true
type KVNamespaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KVNamespace `json:"items"`
}

var _ commonv1alpha1.Managed = &KVNamespace{}
