// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *KVNamespaceObservation) DeepCopyInto(out *KVNamespaceObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
	if in.SupportsURLEncoding != nil {
		in, out := &in.SupportsURLEncoding, &out.SupportsURLEncoding
		*out = new(bool)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *KVNamespaceObservation) DeepCopy() *KVNamespaceObservation {
	if in == nil {
		return nil
	}
	out := new(KVNamespaceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *KVNamespaceParameters) DeepCopyInto(out *KVNamespaceParameters) {
	*out = *in
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *KVNamespaceParameters) DeepCopy() *KVNamespaceParameters {
	if in == nil {
		return nil
	}
	out := new(KVNamespaceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *KVNamespaceSpec) DeepCopyInto(out *KVNamespaceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *KVNamespaceSpec) DeepCopy() *KVNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(KVNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *KVNamespaceStatus) DeepCopyInto(out *KVNamespaceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *KVNamespaceStatus) DeepCopy() *KVNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(KVNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *KVNamespace) DeepCopyInto(out *KVNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of the receiver.
func (in *KVNamespace) DeepCopy() *KVNamespace {
	if in == nil {
		return nil
	}
	out := new(KVNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *KVNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *KVNamespaceList) DeepCopyInto(out *KVNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KVNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *KVNamespaceList) DeepCopy() *KVNamespaceList {
	if in == nil {
		return nil
	}
	out := new(KVNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *KVNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
