// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
)

// D1DatabaseParameters are the configurable fields of a D1Database: the request
// bodies of POST /accounts/{account_id}/d1/database and PATCH /accounts/{account_id}/d1/database/{database_id}.
type D1DatabaseParameters struct {
	// Specify the location to restrict the D1 database to run and store data. If this option is present, the location hint is ignored.
	// +kubebuilder:validation:Enum="eu";"fedramp";"us"
	// +optional
	Jurisdiction *string `json:"jurisdiction,omitempty"`
	// D1 database name.
	// +kubebuilder:validation:Pattern=`^[a-zA-Z0-9][a-zA-Z0-9_-]*$`
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	Name *string `json:"name,omitempty"`
	// Specify the region to create the D1 primary, if available. If this option is omitted, the D1 will be created as close as possible to the current user.
	// +kubebuilder:validation:Enum="WNAM";"ENAM";"WEUR";"EEUR";"APAC";"OC"
	// +optional
	PrimaryLocationHint *string `json:"primary_location_hint,omitempty"`
	// Configuration for D1 read replication.
	// +optional
	ReadReplication *D1DatabaseReadReplicationParameters `json:"read_replication,omitempty"`
}

// D1DatabaseReadReplicationParameters is a nested object of the Cloudflare API schema.
//
// Configuration for D1 read replication.
type D1DatabaseReadReplicationParameters struct {
	// The read replication mode for the database. Use 'auto' to create replicas and allow D1 automatically place them around the world, or 'disabled' to not use any database replicas (it can take a few hours for all replicas to be deleted).
	// +kubebuilder:validation:Enum="auto";"disabled"
	// +kubebuilder:validation:Required
	Mode string `json:"mode"`
}

// D1DatabaseObservation is the D1Database as returned by GET /accounts/{account_id}/d1/database/{database_id}.
type D1DatabaseObservation struct {
	// Specifies the timestamp the resource was created as an ISO8601 string.
	// +optional
	CreatedAt *string `json:"created_at,omitempty"`
	// The D1 database's size, in bytes.
	// +kubebuilder:validation:Type=number
	// +optional
	FileSize *float64 `json:"file_size,omitempty"`
	// Specify the location to restrict the D1 database to run and store data. If this option is present, the location hint is ignored.
	// +optional
	Jurisdiction *string `json:"jurisdiction,omitempty"`
	// D1 database name.
	// +optional
	Name *string `json:"name,omitempty"`
	// The number of tables in the D1 database. This count is no longer accurate and should not be relied upon.
	// (deprecated in the Cloudflare API)
	// +kubebuilder:validation:Type=number
	// +optional
	NumTables *float64 `json:"num_tables,omitempty"`
	// Configuration for D1 read replication.
	// +optional
	ReadReplication *D1DatabaseReadReplicationObservation `json:"read_replication,omitempty"`
	// D1 database identifier (UUID).
	// +optional
	UUID *string `json:"uuid,omitempty"`
	// +optional
	Version *string `json:"version,omitempty"`
}

// D1DatabaseReadReplicationObservation is a nested object of the Cloudflare API schema.
//
// Configuration for D1 read replication.
type D1DatabaseReadReplicationObservation struct {
	// The read replication mode for the database. Mode 'auto' denotes that D1 creates replicas and automatically places them around the world. Mode 'disabled' denotes that no database replicas are used.
	// +optional
	Mode *string `json:"mode,omitempty"`
}

// D1DatabaseSpec defines the desired state of a D1Database.
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.name))",message="forProvider.name is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="size(self.accountRef.name) > 0 && size(self.accountRef.name) <= 253",message="accountRef.name must name a CloudflareAccount in this namespace (1-253 characters)"
type D1DatabaseSpec struct {
	commonv1alpha1.ResourceSpec `json:",inline"`
	// ForProvider holds the Cloudflare API fields, named exactly as in the API.
	ForProvider D1DatabaseParameters `json:"forProvider"`
}

// D1DatabaseStatus defines the observed state of a D1Database.
type D1DatabaseStatus struct {
	commonv1alpha1.ResourceStatus `json:",inline"`
	// AtProvider is the resource as last read from the Cloudflare API.
	// +optional
	AtProvider D1DatabaseObservation `json:"atProvider,omitempty"`
}

// D1Database is a Cloudflare d1 (x-fern-sdk-group-name "d1").
//
// Created at /accounts/{account_id}/d1/database, managed at /accounts/{account_id}/d1/database/{id} (account scope).
// Default deletion policy: Orphan.
// Immutable fields: jurisdiction, name, primary_location_hint.
// Write-only fields: primary_location_hint.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=cfd1,categories={cloudflare,managed,d1}
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || self.spec.accountRef.name == oldSelf.spec.accountRef.name",message="spec.accountRef is immutable once the resource exists (status.id is set): the resource lives in that account. To move it, delete this object (deletionPolicy Orphan keeps the resource) and create a new one"
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.jurisdiction) || !has(self.spec.forProvider) || !has(self.spec.forProvider.jurisdiction) || self.spec.forProvider.jurisdiction == oldSelf.spec.forProvider.jurisdiction || (has(oldSelf.status.atProvider) && has(oldSelf.status.atProvider.jurisdiction) && oldSelf.status.atProvider.jurisdiction == self.spec.forProvider.jurisdiction)",message="forProvider.jurisdiction is immutable once the resource exists (status.id is set): recreate the object to change it, or set it to the value Cloudflare reports (status.atProvider.jurisdiction)"
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.name) || !has(self.spec.forProvider) || !has(self.spec.forProvider.name) || self.spec.forProvider.name == oldSelf.spec.forProvider.name || (has(oldSelf.status.atProvider) && has(oldSelf.status.atProvider.name) && oldSelf.status.atProvider.name == self.spec.forProvider.name)",message="forProvider.name is immutable once the resource exists (status.id is set): recreate the object to change it, or set it to the value Cloudflare reports (status.atProvider.name)"
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.primary_location_hint) || !has(self.spec.forProvider) || !has(self.spec.forProvider.primary_location_hint) || self.spec.forProvider.primary_location_hint == oldSelf.spec.forProvider.primary_location_hint",message="forProvider.primary_location_hint is immutable once the resource exists (status.id is set): recreate the object to change it"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="DATABASE",type="string",JSONPath=".status.atProvider.name"
// +kubebuilder:printcolumn:name="VERSION",type="string",JSONPath=".status.atProvider.version",priority=1
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type D1Database struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec D1DatabaseSpec `json:"spec"`
	// +optional
	Status D1DatabaseStatus `json:"status,omitempty"`
}

// GetResourceSpec implements commonv1alpha1.Managed.
func (o *D1Database) GetResourceSpec() *commonv1alpha1.ResourceSpec { return &o.Spec.ResourceSpec }

// GetResourceStatus implements commonv1alpha1.Managed.
func (o *D1Database) GetResourceStatus() *commonv1alpha1.ResourceStatus {
	return &o.Status.ResourceStatus
}

// D1DatabaseList is a list of D1Database.
//
// +kubebuilder:object:root=true
type D1DatabaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []D1Database `json:"items"`
}

var _ commonv1alpha1.Managed = &D1Database{}
