// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *D1DatabaseObservation) DeepCopyInto(out *D1DatabaseObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.FileSize != nil {
		in, out := &in.FileSize, &out.FileSize
		*out = new(float64)
		**out = **in
	}
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NumTables != nil {
		in, out := &in.NumTables, &out.NumTables
		*out = new(float64)
		**out = **in
	}
	if in.ReadReplication != nil {
		in, out := &in.ReadReplication, &out.ReadReplication
		*out = new(D1DatabaseReadReplicationObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *D1DatabaseObservation) DeepCopy() *D1DatabaseObservation {
	if in == nil {
		return nil
	}
	out := new(D1DatabaseObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *D1DatabaseParameters) DeepCopyInto(out *D1DatabaseParameters) {
	*out = *in
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PrimaryLocationHint != nil {
		in, out := &in.PrimaryLocationHint, &out.PrimaryLocationHint
		*out = new(string)
		**out = **in
	}
	if in.ReadReplication != nil {
		in, out := &in.ReadReplication, &out.ReadReplication
		*out = new(D1DatabaseReadReplicationParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *D1DatabaseParameters) DeepCopy() *D1DatabaseParameters {
	if in == nil {
		return nil
	}
	out := new(D1DatabaseParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *D1DatabaseReadReplicationObservation) DeepCopyInto(out *D1DatabaseReadReplicationObservation) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *D1DatabaseReadReplicationObservation) DeepCopy() *D1DatabaseReadReplicationObservation {
	if in == nil {
		return nil
	}
	out := new(D1DatabaseReadReplicationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *D1DatabaseReadReplicationParameters) DeepCopyInto(out *D1DatabaseReadReplicationParameters) {
	*out = *in
}

// DeepCopy creates a deep copy of the receiver.
func (in *D1DatabaseReadReplicationParameters) DeepCopy() *D1DatabaseReadReplicationParameters {
	if in == nil {
		return nil
	}
	out := new(D1DatabaseReadReplicationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *D1DatabaseSpec) DeepCopyInto(out *D1DatabaseSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *D1DatabaseSpec) DeepCopy() *D1DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(D1DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *D1DatabaseStatus) DeepCopyInto(out *D1DatabaseStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *D1DatabaseStatus) DeepCopy() *D1DatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(D1DatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *D1Database) DeepCopyInto(out *D1Database) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of the receiver.
func (in *D1Database) DeepCopy() *D1Database {
	if in == nil {
		return nil
	}
	out := new(D1Database)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *D1Database) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *D1DatabaseList) DeepCopyInto(out *D1DatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]D1Database, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *D1DatabaseList) DeepCopy() *D1DatabaseList {
	if in == nil {
		return nil
	}
	out := new(D1DatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *D1DatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
