package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"sigs.k8s.io/yaml"
)

const testRole = `---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flare-operator-manager
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - kv.cloudflare.flare.dev
  resources:
  - '*'
  verbs:
  - list
`

const testCRD = `# Code generated by flaregen. DO NOT EDIT.
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kvnamespaces.kv.cloudflare.flare.dev
spec:
  group: kv.cloudflare.flare.dev
  names:
    kind: KVNamespace
    plural: kvnamespaces
`

func writeRepo(t *testing.T, role string, crds map[string]string) string {
	t.Helper()
	root := t.TempDir()
	must := func(err error) {
		t.Helper()
		if err != nil {
			t.Fatal(err)
		}
	}
	must(os.MkdirAll(filepath.Join(root, crdSrcDir), 0o755))
	must(os.MkdirAll(filepath.Join(root, "config/rbac"), 0o755))
	must(os.WriteFile(filepath.Join(root, roleSrc), []byte(role), 0o644))
	for name, body := range crds {
		must(os.WriteFile(filepath.Join(root, crdSrcDir, name), []byte(body), 0o644))
	}
	return root
}

func TestSyncThenCheck(t *testing.T) {
	root := writeRepo(t, testRole, map[string]string{"kv.yaml": testCRD})
	want, err := Render(root)
	if err != nil {
		t.Fatal(err)
	}
	diffs, err := Diff(root, want)
	if err != nil {
		t.Fatal(err)
	}
	if len(diffs) != 3 { // one CRD, the manager role, the aggregate roles: all missing
		t.Fatalf("diffs before sync = %v, want 3 missing", diffs)
	}
	if err := Apply(root, want); err != nil {
		t.Fatal(err)
	}
	if diffs, _ := Diff(root, want); len(diffs) != 0 {
		t.Fatalf("diffs after sync = %v", diffs)
	}

	// Chart CRDs are protected from Argo CD deletion and pruning, and still parse.
	crd := want[filepath.Join(crdDstDir, "kv.yaml")]
	var obj struct {
		Metadata struct{ Annotations map[string]string }
	}
	if err := yaml.Unmarshal(splitDocs(crd)[0], &obj); err != nil {
		t.Fatal(err)
	}
	if got := obj.Metadata.Annotations["argocd.argoproj.io/sync-options"]; got != "Delete=false,Prune=false" {
		t.Errorf("chart CRD sync-options annotation %q:\n%s", got, crd)
	}
	withAnn := strings.Replace(testCRD, "metadata:\n", "metadata:\n  annotations:\n    a: b\n", 1)
	pb, err := protectCRD([]byte(withAnn))
	if err != nil || !strings.Contains(string(pb), "  annotations:\n    "+ArgoCDSyncOptions+"\n    a: b\n") {
		t.Errorf("protectCRD with annotations: %v\n%s", err, pb)
	}

	role := string(want[roleDst])
	for _, s := range []string{
		"{{- if .Values.rbac.create }}",
		`name: {{ include "flare-operator.fullname" . }}-manager`,
		"- apiGroups:\n  - \"\"\n  resources:\n  - secrets\n  verbs:\n  - get\n",
		"- '*'",
	} {
		if !strings.Contains(role, s) {
			t.Errorf("manager role missing %q:\n%s", s, role)
		}
	}
	agg := string(want[aggregateTo])
	for _, s := range []string{"aggregate-to-view: \"true\"", "  - kvnamespaces/status\n", "  - deletecollection\n"} {
		if !strings.Contains(agg, s) {
			t.Errorf("aggregate roles missing %q:\n%s", s, agg)
		}
	}
}

func TestCheckDetectsDrift(t *testing.T) {
	root := writeRepo(t, testRole, map[string]string{"kv.yaml": testCRD})
	want, _ := Render(root)
	if err := Apply(root, want); err != nil {
		t.Fatal(err)
	}

	// A CRD removed from config/ leaves a stale copy in the chart; a changed role differs.
	if err := os.Remove(filepath.Join(root, crdSrcDir, "kv.yaml")); err != nil {
		t.Fatal(err)
	}
	other := strings.Replace(testCRD, "kvnamespaces", "queues", -1)
	other = strings.Replace(other, "kv.cloudflare", "queues.cloudflare", -1)
	if err := os.WriteFile(filepath.Join(root, crdSrcDir, "q.yaml"), []byte(other), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, roleSrc), []byte(strings.Replace(testRole, "  - get\n", "  - get\n  - watch\n", 1)), 0o644); err != nil {
		t.Fatal(err)
	}
	want, err := Render(root)
	if err != nil {
		t.Fatal(err)
	}
	diffs, _ := Diff(root, want)
	got := strings.Join(diffs, "\n")
	for _, s := range []string{"missing: " + crdDstDir + "/q.yaml", "stale:   " + crdDstDir + "/kv.yaml", "differs: " + roleDst, "differs: " + aggregateTo} {
		if !strings.Contains(got, s) {
			t.Errorf("diffs missing %q; got:\n%s", s, got)
		}
	}
	if err := Apply(root, want); err != nil {
		t.Fatal(err)
	}
	if diffs, _ := Diff(root, want); len(diffs) != 0 {
		t.Fatalf("diffs after re-sync = %v", diffs)
	}
}

func TestRejectsNamespacedRole(t *testing.T) {
	role := testRole + "---\napiVersion: rbac.authorization.k8s.io/v1\nkind: Role\nmetadata:\n  name: x\n  namespace: y\nrules: []\n"
	root := writeRepo(t, role, map[string]string{"kv.yaml": testCRD})
	if _, err := Render(root); err == nil || !strings.Contains(err.Error(), `"Role"`) {
		t.Fatalf("Render error = %v, want unsupported kind Role", err)
	}
}
