---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flare-operator-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.flare.dev
  resources:
  - cloudflareaccounts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.flare.dev
  resources:
  - cloudflareaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - d1.cloudflare.flare.dev
  - kv.cloudflare.flare.dev
  - queues.cloudflare.flare.dev
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
