// Code generated by flaregen. DO NOT EDIT.

package descriptors

import (
	"k8s.io/apimachinery/pkg/runtime"

	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
	widgetsv1alpha1 "flare.dev/operator/api/widgets/v1alpha1"
	widgettoolsv1alpha1 "flare.dev/operator/api/widgettools/v1alpha1"
	"flare.dev/operator/internal/generic"
)

var generated = []Entry{
	{
		Descriptor: generic.Descriptor{
			Group: "widgets.cloudflare.flare.dev", Version: "v1alpha1", Kind: "Widget",
			Scope:                 "account",
			CreatePath:            "/accounts/{account_id}/widgets",
			ItemPath:              "/accounts/{account_id}/widgets/{id}",
			ListPath:              "/accounts/{account_id}/widgets",
			IDField:               "id",
			NameField:             "name",
			UpdateMethod:          "PATCH",
			Immutable:             []string{"region"},
			WriteOnly:             []string{"region", "secret"},
			ListOrder:             "informational",
			CreateFields:          []string{"combo", "kind", "labels", "lookahead", "meta", "mode", "name", "note", "origin", "region", "secret", "tags", "target", "tree", "ttl"},
			UpdateFields:          []string{"combo", "kind", "labels", "lookahead", "meta", "mode", "name", "note", "origin", "secret", "tags", "target", "tree", "ttl"},
			DefaultDeletionPolicy: "Delete",
		},
		FernGroup: "widgets.gadgets",
		New:       func() commonv1alpha1.Managed { return &widgetsv1alpha1.Widget{} },
		NewList:   func() runtime.Object { return &widgetsv1alpha1.WidgetList{} },
	},
	{
		Descriptor: generic.Descriptor{
			Group: "widgettools.cloudflare.flare.dev", Version: "v1alpha1", Kind: "WidgetSettings",
			Scope:                 "zone",
			ItemPath:              "/zones/{zone_id}/widget_settings",
			UpdateMethod:          "PATCH",
			Singleton:             true,
			UpdateFields:          []string{"enabled", "level"},
			DefaultDeletionPolicy: "Orphan",
		},
		FernGroup: "widget_tools.settings",
		New:       func() commonv1alpha1.Managed { return &widgettoolsv1alpha1.WidgetSettings{} },
		NewList:   func() runtime.Object { return &widgettoolsv1alpha1.WidgetSettingsList{} },
	},
}

var schemeBuilder = runtime.SchemeBuilder{
	widgetsv1alpha1.AddToScheme,
	widgettoolsv1alpha1.AddToScheme,
}
