// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
)

// WidgetParameters are the configurable fields of a Widget: the request
// bodies of POST /accounts/{account_id}/widgets and PATCH /accounts/{account_id}/widgets/{widget_id}.
type WidgetParameters struct {
	// +optional
	Combo *WidgetComboParameters `json:"combo,omitempty"`
	// +kubebuilder:validation:Enum="a";"b"
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`
	// +optional
	Labels map[string]string `json:"labels,omitempty"`
	// +optional
	Lookahead *string `json:"lookahead,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	// +kubebuilder:validation:Type=object
	// +optional
	Meta *apiextensionsv1.JSON `json:"meta,omitempty"`
	// +kubebuilder:validation:Enum="x";"y"
	// +optional
	Mode *string `json:"mode,omitempty"`
	// Widget name.
	// +kubebuilder:validation:Pattern=`^[a-z][a-z0-9-]*$`
	// +kubebuilder:validation:MaxLength=64
	// +kubebuilder:validation:Required
	Name string `json:"name"`
	// +optional
	Note *string `json:"note,omitempty"`
	// +optional
	Origin *WidgetOriginParameters `json:"origin,omitempty"`
	// Create-only and never read back.
	// +optional
	Region *string `json:"region,omitempty"`
	// +optional
	Secret *string `json:"secret,omitempty"`
	// +kubebuilder:validation:MaxItems=5
	// +kubebuilder:validation:items:MaxLength=16
	// +optional
	Tags []string `json:"tags,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	// +kubebuilder:validation:Schemaless
	// +optional
	Target *apiextensionsv1.JSON `json:"target,omitempty"`
	// A tree node (recursive).
	// +optional
	Tree *WidgetTreeParameters `json:"tree,omitempty"`
	// +kubebuilder:validation:Type=number
	// +optional
	TTL *float64 `json:"ttl,omitempty"`
}

// WidgetComboParameters is a nested object of the Cloudflare API schema.
type WidgetComboParameters struct {
	// +optional
	Extra *bool `json:"extra,omitempty"`
	// +kubebuilder:validation:Required
	Name string `json:"name"`
	// +kubebuilder:validation:Type=number
	// +optional
	Weight *float64 `json:"weight,omitempty"`
}

// WidgetOriginParameters is a nested object of the Cloudflare API schema.
type WidgetOriginParameters struct {
	// +optional
	Bucket *string `json:"bucket,omitempty"`
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=60
	// +optional
	Timeout *int64 `json:"timeout,omitempty"`
	// +kubebuilder:validation:Enum="http";"s3"
	// +kubebuilder:validation:Required
	Type string `json:"type"`
	// Origin URL.
	// +optional
	URL *string `json:"url,omitempty"`
}

// WidgetTreeParameters is a nested object of the Cloudflare API schema.
//
// A tree node (recursive).
type WidgetTreeParameters struct {
	// +optional
	Children []apiextensionsv1.JSON `json:"children,omitempty"`
	// +optional
	Value *string `json:"value,omitempty"`
}

// WidgetObservation is the Widget as returned by GET /accounts/{account_id}/widgets/{widget_id}.
type WidgetObservation struct {
	// +optional
	Combo *WidgetComboObservation `json:"combo,omitempty"`
	// +optional
	CreatedOn *string `json:"created_on,omitempty"`
	// Widget identifier.
	// +optional
	ID *string `json:"id,omitempty"`
	// +optional
	Kind *string `json:"kind,omitempty"`
	// +optional
	Labels map[string]string `json:"labels,omitempty"`
	// +optional
	Lookahead *string `json:"lookahead,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	// +kubebuilder:validation:Type=object
	// +optional
	Meta *apiextensionsv1.JSON `json:"meta,omitempty"`
	// +optional
	Mode *string `json:"mode,omitempty"`
	// Widget name.
	// +optional
	Name *string `json:"name,omitempty"`
	// +optional
	Note *string `json:"note,omitempty"`
	// +optional
	Origin *WidgetOriginObservation `json:"origin,omitempty"`
	// +optional
	Tags []string `json:"tags,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	// +kubebuilder:validation:Schemaless
	// +optional
	Target *apiextensionsv1.JSON `json:"target,omitempty"`
	// A tree node (recursive).
	// +optional
	Tree *WidgetTreeObservation `json:"tree,omitempty"`
	// +kubebuilder:validation:Type=number
	// +optional
	TTL *float64 `json:"ttl,omitempty"`
}

// WidgetComboObservation is a nested object of the Cloudflare API schema.
type WidgetComboObservation struct {
	// +optional
	Extra *bool `json:"extra,omitempty"`
	// +optional
	Name *string `json:"name,omitempty"`
	// +kubebuilder:validation:Type=number
	// +optional
	Weight *float64 `json:"weight,omitempty"`
}

// WidgetOriginObservation is a nested object of the Cloudflare API schema.
type WidgetOriginObservation struct {
	// +optional
	Bucket *string `json:"bucket,omitempty"`
	// +optional
	Timeout *int64 `json:"timeout,omitempty"`
	// +optional
	Type *string `json:"type,omitempty"`
	// Origin URL.
	// +optional
	URL *string `json:"url,omitempty"`
}

// WidgetTreeObservation is a nested object of the Cloudflare API schema.
//
// A tree node (recursive).
type WidgetTreeObservation struct {
	// +optional
	Children []apiextensionsv1.JSON `json:"children,omitempty"`
	// +optional
	Value *string `json:"value,omitempty"`
}

// WidgetSpec defines the desired state of a Widget.
type WidgetSpec struct {
	commonv1alpha1.ResourceSpec `json:",inline"`
	// ForProvider holds the Cloudflare API fields, named exactly as in the API.
	ForProvider WidgetParameters `json:"forProvider"`
}

// WidgetStatus defines the observed state of a Widget.
type WidgetStatus struct {
	commonv1alpha1.ResourceStatus `json:",inline"`
	// AtProvider is the resource as last read from the Cloudflare API.
	// +optional
	AtProvider WidgetObservation `json:"atProvider,omitempty"`
}

// Widget is a Cloudflare widgets gadgets (x-fern-sdk-group-name "widgets.gadgets").
//
// Created at /accounts/{account_id}/widgets, managed at /accounts/{account_id}/widgets/{id} (account scope).
// Default deletion policy: Delete.
// Immutable fields: region.
// Write-only fields: region, secret.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={cloudflare,widgets}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type Widget struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec WidgetSpec `json:"spec"`
	// +optional
	Status WidgetStatus `json:"status,omitempty"`
}

// GetResourceSpec implements commonv1alpha1.Managed.
func (o *Widget) GetResourceSpec() *commonv1alpha1.ResourceSpec { return &o.Spec.ResourceSpec }

// GetResourceStatus implements commonv1alpha1.Managed.
func (o *Widget) GetResourceStatus() *commonv1alpha1.ResourceStatus { return &o.Status.ResourceStatus }

// WidgetList is a list of Widget.
//
// +kubebuilder:object:root=true
type WidgetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Widget `json:"items"`
}

var _ commonv1alpha1.Managed = &Widget{}
