// Command assetmime writes internal/controller/workerscript/assets_mime.go: the extension to
// Content-Type table wrangler serves static assets with. wrangler's getContentType
// (packages/workers-shared/utils/helpers.ts) is mime.getType of the npm mime package bundled in
// wrangler-dist/cli.js; this reads that bundle's mime types/standard.js and types/other.js
// object literals and applies Mime.define's rules (types and extensions lower-cased, a *starred
// extension maps to no type, a second definition of an extension must agree with the first).
// Run it (make asset-mime) after moving the differential tests' wrangler
// pin; it needs the pinned wrangler installed (make differential-tools).
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"regexp"
	"sort"
	"strings"
)

func main() {
	cli := flag.String("cli", "", "path of the pinned wrangler's wrangler-dist/cli.js")
	version := flag.String("wrangler", "", "the pinned wrangler version (for the generated comment)")
	out := flag.String("out", "internal/controller/workerscript/assets_mime.go", "file to write")
	flag.Parse()
	if *cli == "" || *version == "" {
		log.Fatal("assetmime: -cli and -wrangler are required")
	}
	src, err := os.ReadFile(*cli)
	if err != nil {
		log.Fatal(err)
	}
	mimeVersion := regexp.MustCompile(`node_modules/\.pnpm/mime@([0-9.]+)/node_modules/mime/dist/types/standard\.js`).FindSubmatch(src)
	if mimeVersion == nil {
		log.Fatal("assetmime: no mime types/standard.js module in the bundle")
	}
	// mime's index.js: new Mime(standard, other), defined in that order.
	table := map[string]string{}
	for _, mod := range []string{"standard", "other"} {
		types := moduleTypes(src, mod)
		names := make([]string, 0, len(types))
		for t := range types {
			names = append(names, t)
		}
		// Object.entries order is insertion order; a conflict throws in mime whatever the order,
		// so sorting only makes the error deterministic.
		sort.Strings(names)
		for _, t := range names {
			lt := strings.ToLower(t)
			for _, ext := range types[t] {
				ext = strings.ToLower(ext)
				if strings.HasPrefix(ext, "*") {
					continue
				}
				if cur, ok := table[ext]; ok && cur != lt {
					log.Fatalf("assetmime: %s -> %s conflicts with %s", lt, ext, cur)
				}
				table[ext] = lt
			}
		}
	}
	exts := make([]string, 0, len(table))
	for e := range table {
		exts = append(exts, e)
	}
	sort.Strings(exts)
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by hack/assetmime from wrangler@%s wrangler-dist/cli.js (mime@%s types/standard.js\n", *version, mimeVersion[1])
	b.WriteString("// and types/other.js). DO NOT EDIT; run make asset-mime.\n\npackage workerscript\n\n")
	b.WriteString("// wranglerMimeTypes maps a lower-case extension (without its dot) to the type mime.getType gives it.\n")
	b.WriteString("var wranglerMimeTypes = map[string]string{\n")
	for _, e := range exts {
		fmt.Fprintf(&b, "\t%q: %q,\n", e, table[e])
	}
	b.WriteString("}\n")
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("assetmime: %d extensions -> %s\n", len(exts), *out)
}

// moduleTypes parses the `types… = {…};` object literal of mime's dist/types/<mod>.js module.
func moduleTypes(src []byte, mod string) map[string][]string {
	marker := []byte("mime/dist/types/" + mod + `.js"() {`)
	i := bytes.Index(src, marker)
	if i < 0 {
		log.Fatalf("assetmime: no mime types/%s.js module in the bundle", mod)
	}
	rest := src[i:]
	start := bytes.Index(rest, []byte(" = {"))
	end := bytes.Index(rest, []byte("\n    };"))
	if start < 0 || end < start {
		log.Fatalf("assetmime: types/%s.js: no object literal", mod)
	}
	var types map[string][]string
	if err := json.Unmarshal(rest[start+3:end+6], &types); err != nil {
		log.Fatalf("assetmime: types/%s.js: %v", mod, err)
	}
	return types
}
