// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
)

// VectorizeIndexParameters are the configurable fields of a VectorizeIndex: the request
// bodies of POST /accounts/{account_id}/vectorize/v2/indexes.
type VectorizeIndexParameters struct {
	// Specifies the type of configuration to use for the index.
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	Config *VectorizeIndexConfigParameters `json:"config,omitempty"`
	// Specifies the description of the index.
	// +optional
	Description *string `json:"description,omitempty"`
	// +kubebuilder:validation:Pattern=`^([a-z]+[a-z0-9_-]*[a-z0-9]+)$`
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	Name *string `json:"name,omitempty"`
}

// VectorizeIndexConfigParameters is a nested object of the Cloudflare API schema.
//
// Specifies the type of configuration to use for the index.
type VectorizeIndexConfigParameters struct {
	// Specifies the number of dimensions for the index
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=1536
	// +optional
	Dimensions *int64 `json:"dimensions,omitempty"`
	// Specifies the type of metric to use calculating distance.
	// +kubebuilder:validation:Enum="cosine";"euclidean";"dot-product"
	// +optional
	Metric *string `json:"metric,omitempty"`
	// Specifies the preset to use for the index.
	// +kubebuilder:validation:Enum="@cf/baai/bge-small-en-v1.5";"@cf/baai/bge-base-en-v1.5";"@cf/baai/bge-large-en-v1.5";"openai/text-embedding-ada-002";"cohere/embed-multilingual-v2.0"
	// +optional
	Preset *string `json:"preset,omitempty"`
}

// VectorizeIndexObservation is the VectorizeIndex as returned by GET /accounts/{account_id}/vectorize/v2/indexes/{index_name}.
type VectorizeIndexObservation struct {
	// +optional
	Config *VectorizeIndexConfigObservation `json:"config,omitempty"`
	// Specifies the timestamp the resource was created as an ISO8601 string.
	// +optional
	CreatedOn *string `json:"created_on,omitempty"`
	// Specifies the description of the index.
	// +optional
	Description *string `json:"description,omitempty"`
	// Specifies the timestamp the resource was modified as an ISO8601 string.
	// +optional
	ModifiedOn *string `json:"modified_on,omitempty"`
	// +optional
	Name *string `json:"name,omitempty"`
}

// VectorizeIndexConfigObservation is a nested object of the Cloudflare API schema.
type VectorizeIndexConfigObservation struct {
	// Specifies the number of dimensions for the index
	// +optional
	Dimensions *int64 `json:"dimensions,omitempty"`
	// Specifies the type of metric to use calculating distance.
	// +optional
	Metric *string `json:"metric,omitempty"`
}

// VectorizeIndexSpec defines the desired state of a VectorizeIndex.
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.config))",message="forProvider.config is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.name))",message="forProvider.name is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="size(self.accountRef.name) > 0 && size(self.accountRef.name) <= 253",message="accountRef.name must name a CloudflareAccount in this namespace (1-253 characters)"
type VectorizeIndexSpec struct {
	commonv1alpha1.ResourceSpec `json:",inline"`
	// ForProvider holds the Cloudflare API fields, named exactly as in the API.
	ForProvider VectorizeIndexParameters `json:"forProvider"`
}

// VectorizeIndexStatus defines the observed state of a VectorizeIndex.
type VectorizeIndexStatus struct {
	commonv1alpha1.ResourceStatus `json:",inline"`
	// AtProvider is the resource as last read from the Cloudflare API.
	// +optional
	AtProvider VectorizeIndexObservation `json:"atProvider,omitempty"`
}

// VectorizeIndex is a Cloudflare vectorize (x-fern-sdk-group-name "vectorize").
//
// Created at /accounts/{account_id}/vectorize/v2/indexes, managed at /accounts/{account_id}/vectorize/v2/indexes/{id} (account scope).
// Default deletion policy: Delete.
// Immutable fields: config, description, name.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=cfvec,categories={cloudflare,managed,vectorize}
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || self.spec.accountRef.name == oldSelf.spec.accountRef.name",message="spec.accountRef is immutable once the resource exists (status.id is set): the resource lives in that account. To move it, delete this object (deletionPolicy Orphan keeps the resource) and create a new one"
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.config) || !has(self.spec.forProvider) || !has(self.spec.forProvider.config) || self.spec.forProvider.config == oldSelf.spec.forProvider.config",message="forProvider.config is immutable once the resource exists (status.id is set): recreate the object to change it"
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.description) || !has(self.spec.forProvider) || !has(self.spec.forProvider.description) || self.spec.forProvider.description == oldSelf.spec.forProvider.description || (has(oldSelf.status.atProvider) && has(oldSelf.status.atProvider.description) && oldSelf.status.atProvider.description == self.spec.forProvider.description)",message="forProvider.description is immutable once the resource exists (status.id is set): recreate the object to change it, or set it to the value Cloudflare reports (status.atProvider.description)"
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.name) || !has(self.spec.forProvider) || !has(self.spec.forProvider.name) || self.spec.forProvider.name == oldSelf.spec.forProvider.name || (has(oldSelf.status.atProvider) && has(oldSelf.status.atProvider.name) && oldSelf.status.atProvider.name == self.spec.forProvider.name)",message="forProvider.name is immutable once the resource exists (status.id is set): recreate the object to change it, or set it to the value Cloudflare reports (status.atProvider.name)"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="DIMENSIONS",type="integer",JSONPath=".status.atProvider.config.dimensions"
// +kubebuilder:printcolumn:name="METRIC",type="string",JSONPath=".status.atProvider.config.metric"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type VectorizeIndex struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec VectorizeIndexSpec `json:"spec"`
	// +optional
	Status VectorizeIndexStatus `json:"status,omitempty"`
}

// GetResourceSpec implements commonv1alpha1.Managed.
func (o *VectorizeIndex) GetResourceSpec() *commonv1alpha1.ResourceSpec { return &o.Spec.ResourceSpec }

// GetResourceStatus implements commonv1alpha1.Managed.
func (o *VectorizeIndex) GetResourceStatus() *commonv1alpha1.ResourceStatus {
	return &o.Status.ResourceStatus
}

// VectorizeIndexList is a list of VectorizeIndex.
//
// +kubebuilder:object:root=true
type VectorizeIndexList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VectorizeIndex `json:"items"`
}

var _ commonv1alpha1.Managed = &VectorizeIndex{}
