// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *VectorizeIndexConfigObservation) DeepCopyInto(out *VectorizeIndexConfigObservation) {
	*out = *in
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = new(int64)
		**out = **in
	}
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *VectorizeIndexConfigObservation) DeepCopy() *VectorizeIndexConfigObservation {
	if in == nil {
		return nil
	}
	out := new(VectorizeIndexConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *VectorizeIndexConfigParameters) DeepCopyInto(out *VectorizeIndexConfigParameters) {
	*out = *in
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = new(int64)
		**out = **in
	}
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(string)
		**out = **in
	}
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *VectorizeIndexConfigParameters) DeepCopy() *VectorizeIndexConfigParameters {
	if in == nil {
		return nil
	}
	out := new(VectorizeIndexConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *VectorizeIndexObservation) DeepCopyInto(out *VectorizeIndexObservation) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(VectorizeIndexConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.CreatedOn != nil {
		in, out := &in.CreatedOn, &out.CreatedOn
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ModifiedOn != nil {
		in, out := &in.ModifiedOn, &out.ModifiedOn
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *VectorizeIndexObservation) DeepCopy() *VectorizeIndexObservation {
	if in == nil {
		return nil
	}
	out := new(VectorizeIndexObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *VectorizeIndexParameters) DeepCopyInto(out *VectorizeIndexParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(VectorizeIndexConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *VectorizeIndexParameters) DeepCopy() *VectorizeIndexParameters {
	if in == nil {
		return nil
	}
	out := new(VectorizeIndexParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *VectorizeIndexSpec) DeepCopyInto(out *VectorizeIndexSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *VectorizeIndexSpec) DeepCopy() *VectorizeIndexSpec {
	if in == nil {
		return nil
	}
	out := new(VectorizeIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *VectorizeIndexStatus) DeepCopyInto(out *VectorizeIndexStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *VectorizeIndexStatus) DeepCopy() *VectorizeIndexStatus {
	if in == nil {
		return nil
	}
	out := new(VectorizeIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *VectorizeIndex) DeepCopyInto(out *VectorizeIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of the receiver.
func (in *VectorizeIndex) DeepCopy() *VectorizeIndex {
	if in == nil {
		return nil
	}
	out := new(VectorizeIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *VectorizeIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *VectorizeIndexList) DeepCopyInto(out *VectorizeIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VectorizeIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *VectorizeIndexList) DeepCopy() *VectorizeIndexList {
	if in == nil {
		return nil
	}
	out := new(VectorizeIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *VectorizeIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
