// Code generated by flaregen. DO NOT EDIT.

package fake

// generatedGenericKinds are the generator.yaml kinds marked `emulate: generic`. flarefake
// emulates them with the descriptor-driven generic profile (generic.go) when they are passed in
// Options.Generic; GeneratedGenericKinds returns a copy.
var generatedGenericKinds = []GenericKind{
	{
		Group: "widgets.cloudflare.flare.dev", Kind: "Widget", Scope: "account",
		CreatePath:   "/accounts/{account_id}/widgets",
		ItemPath:     "/accounts/{account_id}/widgets/{id}",
		ListPath:     "/accounts/{account_id}/widgets",
		IDField:      "id",
		NameField:    "name",
		UpdateMethod: "PATCH",
		WriteOnly:    []string{"region", "secret"},
	},
	{
		Group: "widgettools.cloudflare.flare.dev", Kind: "WidgetSettings", Scope: "zone",
		ItemPath:     "/zones/{zone_id}/widget_settings",
		UpdateMethod: "PATCH",
		Singleton:    true,
	},
}
