// Command apidocs renders docs/api-reference.md from the CRDs in config/crd/bases (generated by
// controller-gen and cmd/flaregen) and the condition and event reasons in
// hack/apidocs/reasons.yaml. Nothing in the reference is written by hand, so it cannot drift
// from the schemas the API server enforces.
//
//	go run ./hack/apidocs          # write docs/api-reference.md (make api-docs)
//	go run ./hack/apidocs -check   # exit 1 when it is out of date (make api-docs-check, part of make ci)
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"
)

const (
	crdDir      = "config/crd/bases"
	reasonsFile = "hack/apidocs/reasons.yaml"
	outFile     = "docs/api-reference.md"
)

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "write nothing; exit 1 if "+outFile+" is out of date")
	flag.Parse()
	want, err := Render(*root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "apidocs:", err)
		os.Exit(2)
	}
	dst := filepath.Join(*root, outFile)
	if *check {
		got, err := os.ReadFile(dst)
		if err != nil || !bytes.Equal(got, want) {
			fmt.Fprintf(os.Stderr, "apidocs: %s is out of date (run `make api-docs`)\n", outFile)
			os.Exit(1)
		}
		fmt.Println("api reference up to date")
		return
	}
	if err := os.WriteFile(dst, want, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "apidocs:", err)
		os.Exit(2)
	}
	fmt.Println("wrote", outFile)
}

// Reasons is hack/apidocs/reasons.yaml.
type Reasons struct {
	Conditions []ConditionReason `json:"conditions"`
	Events     []EventReason     `json:"events"`
}

// ConditionReason documents one reason of the Ready or Synced condition.
type ConditionReason struct {
	Reason    string `json:"reason"`
	Condition string `json:"condition"` // Ready, Synced or "Ready, Synced"
	Status    string `json:"status"`    // True, False or "True/False"
	Kinds     string `json:"kinds"`
	Meaning   string `json:"meaning"`
}

// EventReason documents the reason of one Kubernetes Event the controllers record.
type EventReason struct {
	Reason  string `json:"reason"`
	Type    string `json:"type"`
	Kinds   string `json:"kinds"`
	Meaning string `json:"meaning"`
}

// LoadReasons reads reasons.yaml under root.
func LoadReasons(root string) (*Reasons, error) {
	b, err := os.ReadFile(filepath.Join(root, reasonsFile))
	if err != nil {
		return nil, err
	}
	var r Reasons
	if err := yaml.UnmarshalStrict(b, &r); err != nil {
		return nil, fmt.Errorf("%s: %w", reasonsFile, err)
	}
	return &r, nil
}

// LoadCRDs reads every CRD of config/crd/bases, CloudflareAccount first, then by kind.
func LoadCRDs(root string) ([]*apiextensionsv1.CustomResourceDefinition, error) {
	files, err := filepath.Glob(filepath.Join(root, crdDir, "*.yaml"))
	if err != nil {
		return nil, err
	}
	var out []*apiextensionsv1.CustomResourceDefinition
	for _, f := range files {
		b, err := os.ReadFile(f)
		if err != nil {
			return nil, err
		}
		var crd apiextensionsv1.CustomResourceDefinition
		if err := yaml.Unmarshal(b, &crd); err != nil {
			return nil, fmt.Errorf("%s: %w", f, err)
		}
		out = append(out, &crd)
	}
	sort.Slice(out, func(i, j int) bool {
		a, b := out[i].Spec.Names.Kind, out[j].Spec.Names.Kind
		if (a == "CloudflareAccount") != (b == "CloudflareAccount") {
			return a == "CloudflareAccount"
		}
		return a < b
	})
	return out, nil
}

// Managed reports whether a CRD is a managed resource (it is in the managed category).
func Managed(crd *apiextensionsv1.CustomResourceDefinition) bool {
	for _, c := range crd.Spec.Names.Categories {
		if c == "managed" {
			return true
		}
	}
	return false
}

// Render returns the content of docs/api-reference.md.
func Render(root string) ([]byte, error) {
	crds, err := LoadCRDs(root)
	if err != nil {
		return nil, err
	}
	reasons, err := LoadReasons(root)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }
	p("# API reference\n\n")
	p("<!-- Generated by hack/apidocs from %s and %s. DO NOT EDIT: run `make api-docs`. -->\n\n", crdDir, reasonsFile)
	p("Every kind is namespaced and served at version `v1alpha1` (see [api-versioning.md](api-versioning.md) for the path to `v1beta1`).\n")
	p("Managed kinds share one shape, Crossplane-style: `spec.accountRef`, `spec.forProvider` (Cloudflare API fields, named exactly as in the API), ")
	p("`spec.deletionPolicy`, `spec.managementPolicies`; `status.id` (the Cloudflare ID), `status.conditions` (`Ready`, `Synced`), ")
	p("`status.observedGeneration` and `status.atProvider` (the resource as last read from Cloudflare). ")
	p("An existing resource is adopted by setting the `cloudflare.flare.dev/external-id` annotation to its ID.\n\n")

	p("## Kinds\n\n")
	p("| Kind | API version | Short names | Categories | Default `deletionPolicy` |\n|---|---|---|---|---|\n")
	for _, crd := range crds {
		n := crd.Spec.Names
		dp := "—"
		if Managed(crd) {
			dp = "Delete"
			if s := schema(crd).Properties["spec"].Properties["deletionPolicy"]; s.Default != nil {
				dp = strings.Trim(string(s.Default.Raw), `"`)
			}
		}
		p("| [%s](#%s) | `%s/%s` | %s | %s | %s |\n", n.Kind, strings.ToLower(n.Kind), crd.Spec.Group, crd.Spec.Versions[0].Name,
			codeList(n.ShortNames), codeList(n.Categories), dp)
	}
	p("\n## kubectl\n\n")
	p("- `kubectl get cloudflare` lists every flare-operator object in the namespace, `kubectl get managed` every managed resource ")
	p("(together with those of Crossplane providers, which use the same category). Each kind is also in the category of its product, e.g. `kubectl get queues`.\n")
	p("- Short names all start with `cf`, so they do not collide with core Kubernetes short names (`po`, `svc`, `ns`, ...) or those of common CRDs.\n")
	p("- Every kind prints `READY`, `SYNCED`, `EXTERNAL-ID` (`status.id`), its own columns, then `AGE`. Columns marked *wide* appear only with `-o wide`.\n\n")
	p("| Kind | Columns |\n|---|---|\n")
	for _, crd := range crds {
		var cols []string
		for _, c := range crd.Spec.Versions[0].AdditionalPrinterColumns {
			s := fmt.Sprintf("`%s` (`%s`)", c.Name, c.JSONPath)
			if c.Priority > 0 {
				s += " *wide*"
			}
			cols = append(cols, s)
		}
		p("| %s | %s |\n", crd.Spec.Names.Kind, cell(strings.Join(cols, ", ")))
	}

	p("\n## Conditions\n\n")
	p("Every kind reports two conditions. `Ready` says whether the Cloudflare resource exists and is usable; `Synced` whether the last ")
	p("reconcile applied `spec` (or, for an observe-only object, read the resource). Both carry `observedGeneration`; `status.observedGeneration` ")
	p("is the generation last fully reconciled. The API server's validation (below, per kind) rejects many errors before they reach a controller; ")
	p("the controllers still check everything themselves (e.g. `Synced=False`, reason `Immutable`).\n\n")
	p("| Reason | Condition | Status | Kinds | Meaning |\n|---|---|---|---|---|\n")
	for _, r := range reasons.Conditions {
		p("| `%s` | %s | %s | %s | %s |\n", r.Reason, r.Condition, r.Status, cell(r.Kinds), cell(r.Meaning))
	}
	p("\n### Events\n\n| Reason | Type | Kinds | Meaning |\n|---|---|---|---|\n")
	for _, r := range reasons.Events {
		p("| `%s` | %s | %s | %s |\n", r.Reason, r.Type, cell(r.Kinds), cell(r.Meaning))
	}

	for _, crd := range crds {
		renderKind(&b, crd)
	}
	return b.Bytes(), nil
}

func schema(crd *apiextensionsv1.CustomResourceDefinition) *apiextensionsv1.JSONSchemaProps {
	return crd.Spec.Versions[0].Schema.OpenAPIV3Schema
}

func renderKind(b *bytes.Buffer, crd *apiextensionsv1.CustomResourceDefinition) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format, args...) }
	s := schema(crd)
	n := crd.Spec.Names
	p("\n## %s\n\n", n.Kind)
	p("`%s/%s`, kind `%s`, resource `%s`", crd.Spec.Group, crd.Spec.Versions[0].Name, n.Kind, n.Plural)
	if fg := crd.Annotations["flare.dev/fern-group"]; fg != "" {
		p(", generated by flaregen from the Cloudflare API operations with `x-fern-sdk-group-name` `%s`", fg)
	}
	p(".\n\n%s\n\n", text(s.Description))

	var rules []ruleRow
	collectRules(&rules, "", s)
	if len(rules) > 0 {
		p("### Validation rules\n\nCEL rules (`x-kubernetes-validations`) the API server enforces on create and update")
		p(" (rules that use `oldSelf` apply to updates only):\n\n| Field | Message | Rule |\n|---|---|---|\n")
		for _, r := range rules {
			p("| %s | %s | %s |\n", r.where, cell(r.message), code(r.rule))
		}
		p("\n")
	}
	p("### Fields\n\n| Field | Type | Description | Validation |\n|---|---|---|---|\n")
	for _, top := range []string{"spec", "status"} {
		prop, ok := s.Properties[top]
		if !ok {
			continue
		}
		walk(b, top, prop, contains(s.Required, top))
	}
}

type ruleRow struct{ where, message, rule string }

func collectRules(out *[]ruleRow, path string, s *apiextensionsv1.JSONSchemaProps) {
	where := "(object)"
	if path != "" {
		where = "`" + path + "`"
	}
	for _, r := range s.XValidations {
		msg := r.Message
		if msg == "" {
			msg = r.MessageExpression
		}
		w := where
		if r.FieldPath != "" {
			w = "`" + strings.TrimPrefix(join(path, strings.TrimPrefix(r.FieldPath, ".")), ".") + "`"
		}
		*out = append(*out, ruleRow{where: w, message: msg, rule: r.Rule})
	}
	for _, k := range sortedProps(s) {
		if path == "" && (k == "metadata" || k == "apiVersion" || k == "kind") {
			continue
		}
		child := s.Properties[k]
		collectRules(out, join(path, k), &child)
	}
	if s.Items != nil && s.Items.Schema != nil {
		collectRules(out, path+"[]", s.Items.Schema)
	}
	if s.AdditionalProperties != nil && s.AdditionalProperties.Schema != nil {
		collectRules(out, path+"[key]", s.AdditionalProperties.Schema)
	}
}

func walk(b *bytes.Buffer, path string, s apiextensionsv1.JSONSchemaProps, required bool) {
	desc := text(s.Description)
	if required {
		desc = strings.TrimSpace("**Required.** " + desc)
	}
	fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", path, typeOf(s), cell(desc), cell(validation(s)))
	if path == "status.conditions" {
		return // metav1.Condition: type, status, reason, message, lastTransitionTime, observedGeneration
	}
	for _, k := range sortedProps(&s) {
		walk(b, path+"."+k, s.Properties[k], contains(s.Required, k))
	}
	if s.Items != nil && s.Items.Schema != nil && len(s.Items.Schema.Properties) > 0 {
		for _, k := range sortedProps(s.Items.Schema) {
			walk(b, path+"[]."+k, s.Items.Schema.Properties[k], contains(s.Items.Schema.Required, k))
		}
	}
	if s.AdditionalProperties != nil && s.AdditionalProperties.Schema != nil && len(s.AdditionalProperties.Schema.Properties) > 0 {
		ap := s.AdditionalProperties.Schema
		for _, k := range sortedProps(ap) {
			walk(b, path+"[key]."+k, ap.Properties[k], contains(ap.Required, k))
		}
	}
}

func typeOf(s apiextensionsv1.JSONSchemaProps) string {
	switch {
	case s.XIntOrString:
		return "int or string"
	case s.XPreserveUnknownFields != nil && *s.XPreserveUnknownFields && s.Type == "":
		return "any"
	case s.Type == "array" && s.Items != nil && s.Items.Schema != nil:
		if s.Items.Schema.Type == "object" && len(s.Items.Schema.Properties) > 0 {
			return "[]object"
		}
		return "[]" + typeOf(*s.Items.Schema)
	case s.Type == "object" && s.AdditionalProperties != nil && s.AdditionalProperties.Schema != nil:
		return "map[string]" + typeOf(*s.AdditionalProperties.Schema)
	case s.Type == "string" && s.Format != "":
		return "string (" + s.Format + ")"
	case s.Type == "":
		return "any"
	}
	return s.Type
}

func validation(s apiextensionsv1.JSONSchemaProps) string {
	var out []string
	if len(s.Enum) > 0 {
		var vs []string
		for _, e := range s.Enum {
			vs = append(vs, "`"+strings.Trim(string(e.Raw), `"`)+"`")
		}
		out = append(out, "one of "+strings.Join(vs, ", "))
	}
	if s.Default != nil {
		out = append(out, "default `"+string(s.Default.Raw)+"`")
	}
	if s.Pattern != "" {
		out = append(out, "pattern "+code(s.Pattern))
	}
	lenRange := func(what string, lo, hi *int64) {
		switch {
		case lo != nil && hi != nil:
			out = append(out, fmt.Sprintf("%s %d–%d", what, *lo, *hi))
		case lo != nil:
			out = append(out, fmt.Sprintf("%s ≥ %d", what, *lo))
		case hi != nil:
			out = append(out, fmt.Sprintf("%s ≤ %d", what, *hi))
		}
	}
	lenRange("length", s.MinLength, s.MaxLength)
	lenRange("items", s.MinItems, s.MaxItems)
	lenRange("properties", s.MinProperties, s.MaxProperties)
	if s.Minimum != nil || s.Maximum != nil {
		lo, hi := "", ""
		if s.Minimum != nil {
			op := "≥"
			if s.ExclusiveMinimum {
				op = ">"
			}
			lo = fmt.Sprintf("%s %v", op, *s.Minimum)
		}
		if s.Maximum != nil {
			op := "≤"
			if s.ExclusiveMaximum {
				op = "<"
			}
			hi = fmt.Sprintf("%s %v", op, *s.Maximum)
		}
		out = append(out, strings.TrimSpace("value "+strings.TrimSpace(lo+" "+hi)))
	}
	if s.Items != nil && s.Items.Schema != nil && s.Items.Schema.Type != "object" {
		if v := validation(*s.Items.Schema); v != "" {
			out = append(out, "each item: "+v)
		}
	}
	if s.XListType != nil && *s.XListType != "atomic" {
		lt := "list type " + *s.XListType
		if len(s.XListMapKeys) > 0 {
			lt += " (key " + strings.Join(s.XListMapKeys, ", ") + ")"
		}
		out = append(out, lt)
	}
	if len(s.XValidations) > 0 {
		out = append(out, "CEL rules: see above")
	}
	return strings.Join(out, "; ")
}

var spaceRe = regexp.MustCompile(`\s+`)

// text is a description on one line, with HTML-significant characters escaped.
func text(s string) string {
	s = strings.TrimSpace(spaceRe.ReplaceAllString(s, " "))
	return strings.NewReplacer("<", "&lt;", ">", "&gt;").Replace(s)
}

// cell makes s safe inside a Markdown table cell.
func cell(s string) string { return strings.ReplaceAll(strings.ReplaceAll(s, "\n", " "), "|", `\|`) }

// code renders s as an inline code span inside a table cell.
func code(s string) string {
	s = strings.ReplaceAll(spaceRe.ReplaceAllString(s, " "), "|", `\|`)
	fence := "`"
	for strings.Contains(s, fence) {
		fence += "`"
	}
	return fence + " " + s + " " + fence
}

func codeList(ss []string) string {
	if len(ss) == 0 {
		return "—"
	}
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = "`" + s + "`"
	}
	return strings.Join(out, ", ")
}

func sortedProps(s *apiextensionsv1.JSONSchemaProps) []string {
	keys := make([]string, 0, len(s.Properties))
	for k := range s.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func contains(ss []string, s string) bool {
	for _, x := range ss {
		if x == s {
			return true
		}
	}
	return false
}

func join(a, b string) string {
	if a == "" {
		return b
	}
	return a + "." + b
}
