// Package descriptors is the registry of kinds generated by cmd/flaregen.
// The data lives in zz_generated.go (make generate-crds); this file is the
// hand-written accessor API.
package descriptors

import (
	"k8s.io/apimachinery/pkg/runtime"

	commonv1alpha1 "github.com/chenhunghan/flare-operator/api/common/v1alpha1"
	"github.com/chenhunghan/flare-operator/internal/generic"
)

// Entry binds a generated Descriptor to its Go types.
type Entry struct {
	generic.Descriptor

	// FernGroup is the x-fern-sdk-group-name the kind was generated from.
	FernGroup string

	// Extension is the per-kind behavior Descriptor cannot express (generator.yaml
	// requestHeaders, observedAs, subResources; see generic.Extension).
	Extension generic.Extension

	// New returns an empty object of the kind; NewList an empty list.
	New     func() commonv1alpha1.Managed
	NewList func() runtime.Object
}

// All returns every generated Descriptor, ordered by group and kind.
func All() []generic.Descriptor {
	out := make([]generic.Descriptor, len(generated))
	for i, e := range generated {
		out[i] = e.Descriptor
	}
	return out
}

// Entries returns every generated kind, ordered by group and kind.
func Entries() []Entry { return append([]Entry(nil), generated...) }

// Lookup finds a generated kind by API group and kind.
func Lookup(group, kind string) (Entry, bool) {
	for _, e := range generated {
		if e.Group == group && e.Kind == kind {
			return e, true
		}
	}
	return Entry{}, false
}

// AddToScheme registers every generated API group.
func AddToScheme(s *runtime.Scheme) error { return schemeBuilder.AddToScheme(s) }
