// Code generated by flaregen. DO NOT EDIT.

package descriptors

import (
	"k8s.io/apimachinery/pkg/runtime"

	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
	d1v1alpha1 "flare.dev/operator/api/d1/v1alpha1"
	kvv1alpha1 "flare.dev/operator/api/kv/v1alpha1"
	queuesv1alpha1 "flare.dev/operator/api/queues/v1alpha1"
	"flare.dev/operator/internal/generic"
)

var generated = []Entry{
	{
		Descriptor: generic.Descriptor{
			Group: "d1.cloudflare.flare.dev", Version: "v1alpha1", Kind: "D1Database",
			Scope:                 "account",
			CreatePath:            "/accounts/{account_id}/d1/database",
			ItemPath:              "/accounts/{account_id}/d1/database/{id}",
			ListPath:              "/accounts/{account_id}/d1/database",
			IDField:               "uuid",
			NameField:             "name",
			UpdateMethod:          "PATCH",
			Immutable:             []string{"jurisdiction", "name", "primary_location_hint"},
			WriteOnly:             []string{"primary_location_hint"},
			DefaultDeletionPolicy: "Orphan",
		},
		FernGroup:    "d1",
		CreateFields: []string{"jurisdiction", "name", "primary_location_hint", "read_replication"},
		UpdateFields: []string{"read_replication"},
		New:          func() commonv1alpha1.Managed { return &d1v1alpha1.D1Database{} },
		NewList:      func() runtime.Object { return &d1v1alpha1.D1DatabaseList{} },
	},
	{
		Descriptor: generic.Descriptor{
			Group: "kv.cloudflare.flare.dev", Version: "v1alpha1", Kind: "KVNamespace",
			Scope:                 "account",
			CreatePath:            "/accounts/{account_id}/storage/kv/namespaces",
			ItemPath:              "/accounts/{account_id}/storage/kv/namespaces/{id}",
			ListPath:              "/accounts/{account_id}/storage/kv/namespaces",
			IDField:               "id",
			NameField:             "title",
			UpdateMethod:          "PUT",
			Immutable:             []string{"jurisdiction"},
			ListOrder:             "id ascending by default; order=title and direction=asc|desc supported",
			DefaultDeletionPolicy: "Orphan",
		},
		FernGroup:    "kv.namespaces",
		CreateFields: []string{"jurisdiction", "title"},
		UpdateFields: []string{"title"},
		New:          func() commonv1alpha1.Managed { return &kvv1alpha1.KVNamespace{} },
		NewList:      func() runtime.Object { return &kvv1alpha1.KVNamespaceList{} },
	},
	{
		Descriptor: generic.Descriptor{
			Group: "queues.cloudflare.flare.dev", Version: "v1alpha1", Kind: "Queue",
			Scope:                 "account",
			CreatePath:            "/accounts/{account_id}/queues",
			ItemPath:              "/accounts/{account_id}/queues/{id}",
			ListPath:              "/accounts/{account_id}/queues",
			IDField:               "queue_id",
			NameField:             "queue_name",
			UpdateMethod:          "PATCH",
			Immutable:             []string{"jurisdiction"},
			DefaultDeletionPolicy: "Orphan",
		},
		FernGroup:    "queues",
		CreateFields: []string{"jurisdiction", "queue_name"},
		UpdateFields: []string{"queue_name", "settings"},
		New:          func() commonv1alpha1.Managed { return &queuesv1alpha1.Queue{} },
		NewList:      func() runtime.Object { return &queuesv1alpha1.QueueList{} },
	},
}

var schemeBuilder = runtime.SchemeBuilder{
	d1v1alpha1.AddToScheme,
	kvv1alpha1.AddToScheme,
	queuesv1alpha1.AddToScheme,
}
