// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
)

// AIGatewayParameters are the configurable fields of a AIGateway: the request
// bodies of POST /accounts/{account_id}/ai-gateway/gateways and PUT /accounts/{account_id}/ai-gateway/gateways/{id}.
type AIGatewayParameters struct {
	// +optional
	Authentication *bool `json:"authentication,omitempty"`
	// Requires customer-provided provider credentials and prevents fallback to Unified Billing.
	// +optional
	ByokOnly *bool `json:"byok_only,omitempty"`
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	CacheInvalidateOnUpdate *bool `json:"cache_invalidate_on_update,omitempty"`
	// +kubebuilder:validation:Minimum=0
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	CacheTTL *int64 `json:"cache_ttl,omitempty"`
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	CollectLogs *bool `json:"collect_logs,omitempty"`
	// +optional
	Dlp *AIGatewayDlpParameters `json:"dlp,omitempty"`
	// +optional
	Guardrails *AIGatewayGuardrailsParameters `json:"guardrails,omitempty"`
	// Unique identifier of the AI Gateway within the account.
	// +kubebuilder:validation:Pattern=`^[a-z0-9_]+(?:-[a-z0-9_]+)*$`
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=64
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	ID *string `json:"id,omitempty"`
	// +optional
	LogClassification *bool `json:"log_classification,omitempty"`
	// +kubebuilder:validation:Minimum=10000
	// +kubebuilder:validation:Maximum=10000000
	// +optional
	LogManagement *int64 `json:"log_management,omitempty"`
	// +kubebuilder:validation:Enum="STOP_INSERTING";"DELETE_OLDEST"
	// +optional
	LogManagementStrategy *string `json:"log_management_strategy,omitempty"`
	// +optional
	Logpush *bool `json:"logpush,omitempty"`
	// +kubebuilder:validation:MinLength=16
	// +kubebuilder:validation:MaxLength=1024
	// +optional
	LogpushPublicKey *string `json:"logpush_public_key,omitempty"`
	// +kubebuilder:validation:MaxItems=5
	// +optional
	Otel []AIGatewayOtelParameters `json:"otel,omitempty"`
	// +kubebuilder:validation:Minimum=0
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	RateLimitingInterval *int64 `json:"rate_limiting_interval,omitempty"`
	// +kubebuilder:validation:Minimum=0
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	RateLimitingLimit *int64 `json:"rate_limiting_limit,omitempty"`
	// +kubebuilder:validation:Enum="fixed";"sliding"
	// +optional
	RateLimitingTechnique *string `json:"rate_limiting_technique,omitempty"`
	// Backoff strategy for retry delays
	// +kubebuilder:validation:Enum="constant";"linear";"exponential"
	// +optional
	RetryBackoff *string `json:"retry_backoff,omitempty"`
	// Delay between retry attempts in milliseconds (0-60000)
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=60000
	// +optional
	RetryDelay *int64 `json:"retry_delay,omitempty"`
	// Maximum number of retry attempts for failed requests (1-5)
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=5
	// +optional
	RetryMaxAttempts *int64 `json:"retry_max_attempts,omitempty"`
	// +optional
	SpendLimits *AIGatewaySpendLimitsParameters `json:"spend_limits,omitempty"`
	// +optional
	StoreID *string `json:"store_id,omitempty"`
	// +optional
	Stripe *AIGatewayStripeParameters `json:"stripe,omitempty"`
	// Controls how Workers AI inference calls routed through this gateway are billed. 'postpaid' bills the account directly through Workers AI; 'unified' deducts credits via AI Gateway using neuron-based pricing and delegates billing to AI Gateway.
	// +kubebuilder:validation:Enum="postpaid";"unified"
	// +optional
	WorkersAiBillingMode *string `json:"workers_ai_billing_mode,omitempty"`
	// +optional
	Zdr *bool `json:"zdr,omitempty"`
}

// AIGatewayDlpParameters is a nested object of the Cloudflare API schema.
type AIGatewayDlpParameters struct {
	// +kubebuilder:validation:Enum="BLOCK";"FLAG"
	// +optional
	Action *string `json:"action,omitempty"`
	// +kubebuilder:validation:Required
	Enabled bool `json:"enabled"`
	// +optional
	Policies []AIGatewayDlpPoliciesParameters `json:"policies,omitempty"`
	// +optional
	Profiles []string `json:"profiles,omitempty"`
}

// AIGatewayDlpPoliciesParameters is a nested object of the Cloudflare API schema.
type AIGatewayDlpPoliciesParameters struct {
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +kubebuilder:validation:Required
	Action string `json:"action"`
	// +kubebuilder:validation:items:Enum="REQUEST";"RESPONSE"
	// +kubebuilder:validation:Required
	Check []string `json:"check"`
	// +kubebuilder:validation:Required
	Enabled bool `json:"enabled"`
	// +kubebuilder:validation:Required
	ID string `json:"id"`
	// +kubebuilder:validation:Required
	Profiles []string `json:"profiles"`
}

// AIGatewayGuardrailsParameters is a nested object of the Cloudflare API schema.
type AIGatewayGuardrailsParameters struct {
	// +kubebuilder:validation:Required
	Prompt AIGatewayGuardrailsPromptParameters `json:"prompt"`
	// +kubebuilder:validation:Required
	Response AIGatewayGuardrailsResponseParameters `json:"response"`
}

// AIGatewayGuardrailsPromptParameters is a nested object of the Cloudflare API schema.
type AIGatewayGuardrailsPromptParameters struct {
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	P1 *string `json:"P1,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S1 *string `json:"S1,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S10 *string `json:"S10,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S11 *string `json:"S11,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S12 *string `json:"S12,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S13 *string `json:"S13,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S2 *string `json:"S2,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S3 *string `json:"S3,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S4 *string `json:"S4,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S5 *string `json:"S5,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S6 *string `json:"S6,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S7 *string `json:"S7,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S8 *string `json:"S8,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S9 *string `json:"S9,omitempty"`
}

// AIGatewayGuardrailsResponseParameters is a nested object of the Cloudflare API schema.
type AIGatewayGuardrailsResponseParameters struct {
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	P1 *string `json:"P1,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S1 *string `json:"S1,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S10 *string `json:"S10,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S11 *string `json:"S11,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S12 *string `json:"S12,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S13 *string `json:"S13,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S2 *string `json:"S2,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S3 *string `json:"S3,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S4 *string `json:"S4,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S5 *string `json:"S5,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S6 *string `json:"S6,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S7 *string `json:"S7,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S8 *string `json:"S8,omitempty"`
	// +kubebuilder:validation:Enum="FLAG";"BLOCK"
	// +optional
	S9 *string `json:"S9,omitempty"`
}

// AIGatewayOtelParameters is a nested object of the Cloudflare API schema.
type AIGatewayOtelParameters struct {
	// +kubebuilder:validation:MaxLength=256
	// +optional
	Authorization *string `json:"authorization,omitempty"`
	// +kubebuilder:validation:Enum="json";"protobuf"
	// +optional
	ContentType *string `json:"content_type,omitempty"`
	// +kubebuilder:validation:Required
	Headers map[string]string `json:"headers"`
	// +kubebuilder:validation:MaxLength=2048
	// +kubebuilder:validation:Required
	URL string `json:"url"`
}

// AIGatewaySpendLimitsParameters is a nested object of the Cloudflare API schema.
type AIGatewaySpendLimitsParameters struct {
	// +optional
	Enabled *bool `json:"enabled,omitempty"`
	// +kubebuilder:validation:MaxItems=20
	// +optional
	Rules []AIGatewaySpendLimitsRulesParameters `json:"rules,omitempty"`
}

// AIGatewaySpendLimitsRulesParameters is a nested object of the Cloudflare API schema.
type AIGatewaySpendLimitsRulesParameters struct {
	// +optional
	Enabled *bool `json:"enabled,omitempty"`
	// +kubebuilder:validation:Pattern=`^[a-zA-Z0-9_-]+$`
	// +kubebuilder:validation:MinLength=1
	// +optional
	ID *string `json:"id,omitempty"`
	// +kubebuilder:validation:Type=number
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:ExclusiveMinimum=true
	// +kubebuilder:validation:Required
	Limit float64 `json:"limit"`
	// +kubebuilder:validation:Enum="cost"
	// +kubebuilder:validation:Required
	LimitType string `json:"limitType"`
	// +optional
	Metadata map[string]AIGatewaySpendLimitsRulesMetadataParameters `json:"metadata,omitempty"`
	// +optional
	Model *AIGatewaySpendLimitsRulesModelParameters `json:"model,omitempty"`
	// +optional
	Provider *AIGatewaySpendLimitsRulesProviderParameters `json:"provider,omitempty"`
	// +kubebuilder:validation:Enum="fixed";"sliding"
	// +optional
	Technique *string `json:"technique,omitempty"`
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:ExclusiveMinimum=true
	// +kubebuilder:validation:Required
	Window int64 `json:"window"`
}

// AIGatewaySpendLimitsRulesMetadataParameters is a nested object of the Cloudflare API schema.
type AIGatewaySpendLimitsRulesMetadataParameters struct {
	// +kubebuilder:validation:Enum="partition";"filter"
	// +kubebuilder:validation:Required
	Mode string `json:"mode"`
	// +optional
	Values []string `json:"values,omitempty"`
}

// AIGatewaySpendLimitsRulesModelParameters is a nested object of the Cloudflare API schema.
type AIGatewaySpendLimitsRulesModelParameters struct {
	// +kubebuilder:validation:Enum="filter"
	// +kubebuilder:validation:Required
	Mode string `json:"mode"`
	// +kubebuilder:validation:Required
	Values []string `json:"values"`
}

// AIGatewaySpendLimitsRulesProviderParameters is a nested object of the Cloudflare API schema.
type AIGatewaySpendLimitsRulesProviderParameters struct {
	// +kubebuilder:validation:Enum="filter"
	// +kubebuilder:validation:Required
	Mode string `json:"mode"`
	// +kubebuilder:validation:Required
	Values []string `json:"values"`
}

// AIGatewayStripeParameters is a nested object of the Cloudflare API schema.
type AIGatewayStripeParameters struct {
	// +kubebuilder:validation:Required
	Authorization string `json:"authorization"`
	// +kubebuilder:validation:Required
	UsageEvents []AIGatewayStripeUsageEventsParameters `json:"usage_events"`
}

// AIGatewayStripeUsageEventsParameters is a nested object of the Cloudflare API schema.
type AIGatewayStripeUsageEventsParameters struct {
	// +kubebuilder:validation:Required
	Payload string `json:"payload"`
}

// AIGatewayObservation is the AIGateway as returned by GET /accounts/{account_id}/ai-gateway/gateways/{id}.
type AIGatewayObservation struct {
	// +optional
	Authentication *bool `json:"authentication,omitempty"`
	// Requires customer-provided provider credentials and prevents fallback to Unified Billing.
	// +optional
	ByokOnly *bool `json:"byok_only,omitempty"`
	// +optional
	CacheInvalidateOnUpdate *bool `json:"cache_invalidate_on_update,omitempty"`
	// +optional
	CacheTTL *int64 `json:"cache_ttl,omitempty"`
	// +optional
	CollectLogs *bool `json:"collect_logs,omitempty"`
	// +optional
	CreatedAt *string `json:"created_at,omitempty"`
	// +optional
	Dlp *AIGatewayDlpObservation `json:"dlp,omitempty"`
	// +optional
	Guardrails *AIGatewayGuardrailsObservation `json:"guardrails,omitempty"`
	// Unique identifier of the AI Gateway within the account.
	// +optional
	ID *string `json:"id,omitempty"`
	// +optional
	IsDefault *bool `json:"is_default,omitempty"`
	// +optional
	LogClassification *bool `json:"log_classification,omitempty"`
	// +optional
	LogManagement *int64 `json:"log_management,omitempty"`
	// +optional
	LogManagementStrategy *string `json:"log_management_strategy,omitempty"`
	// +optional
	Logpush *bool `json:"logpush,omitempty"`
	// +optional
	LogpushPublicKey *string `json:"logpush_public_key,omitempty"`
	// +optional
	ModifiedAt *string `json:"modified_at,omitempty"`
	// +optional
	Otel []AIGatewayOtelObservation `json:"otel,omitempty"`
	// +optional
	RateLimitingInterval *int64 `json:"rate_limiting_interval,omitempty"`
	// +optional
	RateLimitingLimit *int64 `json:"rate_limiting_limit,omitempty"`
	// +optional
	RateLimitingTechnique *string `json:"rate_limiting_technique,omitempty"`
	// Backoff strategy for retry delays
	// +optional
	RetryBackoff *string `json:"retry_backoff,omitempty"`
	// Delay between retry attempts in milliseconds (0-60000)
	// +optional
	RetryDelay *int64 `json:"retry_delay,omitempty"`
	// Maximum number of retry attempts for failed requests (1-5)
	// +optional
	RetryMaxAttempts *int64 `json:"retry_max_attempts,omitempty"`
	// +optional
	SpendLimits *AIGatewaySpendLimitsObservation `json:"spend_limits,omitempty"`
	// +optional
	StoreID *string `json:"store_id,omitempty"`
	// +optional
	Stripe *AIGatewayStripeObservation `json:"stripe,omitempty"`
	// Controls how Workers AI inference calls routed through this gateway are billed. 'postpaid' bills the account directly through Workers AI; 'unified' deducts credits via AI Gateway using neuron-based pricing and delegates billing to AI Gateway.
	// +optional
	WorkersAiBillingMode *string `json:"workers_ai_billing_mode,omitempty"`
	// +optional
	Zdr *bool `json:"zdr,omitempty"`
}

// AIGatewayDlpObservation is a nested object of the Cloudflare API schema.
type AIGatewayDlpObservation struct {
	// +optional
	Action *string `json:"action,omitempty"`
	// +optional
	Enabled *bool `json:"enabled,omitempty"`
	// +optional
	Policies []AIGatewayDlpPoliciesObservation `json:"policies,omitempty"`
	// +optional
	Profiles []string `json:"profiles,omitempty"`
}

// AIGatewayDlpPoliciesObservation is a nested object of the Cloudflare API schema.
type AIGatewayDlpPoliciesObservation struct {
	// +optional
	Action *string `json:"action,omitempty"`
	// +optional
	Check []string `json:"check,omitempty"`
	// +optional
	Enabled *bool `json:"enabled,omitempty"`
	// +optional
	ID *string `json:"id,omitempty"`
	// +optional
	Profiles []string `json:"profiles,omitempty"`
}

// AIGatewayGuardrailsObservation is a nested object of the Cloudflare API schema.
type AIGatewayGuardrailsObservation struct {
	// +optional
	Prompt *AIGatewayGuardrailsPromptObservation `json:"prompt,omitempty"`
	// +optional
	Response *AIGatewayGuardrailsResponseObservation `json:"response,omitempty"`
}

// AIGatewayGuardrailsPromptObservation is a nested object of the Cloudflare API schema.
type AIGatewayGuardrailsPromptObservation struct {
	// +optional
	P1 *string `json:"P1,omitempty"`
	// +optional
	S1 *string `json:"S1,omitempty"`
	// +optional
	S10 *string `json:"S10,omitempty"`
	// +optional
	S11 *string `json:"S11,omitempty"`
	// +optional
	S12 *string `json:"S12,omitempty"`
	// +optional
	S13 *string `json:"S13,omitempty"`
	// +optional
	S2 *string `json:"S2,omitempty"`
	// +optional
	S3 *string `json:"S3,omitempty"`
	// +optional
	S4 *string `json:"S4,omitempty"`
	// +optional
	S5 *string `json:"S5,omitempty"`
	// +optional
	S6 *string `json:"S6,omitempty"`
	// +optional
	S7 *string `json:"S7,omitempty"`
	// +optional
	S8 *string `json:"S8,omitempty"`
	// +optional
	S9 *string `json:"S9,omitempty"`
}

// AIGatewayGuardrailsResponseObservation is a nested object of the Cloudflare API schema.
type AIGatewayGuardrailsResponseObservation struct {
	// +optional
	P1 *string `json:"P1,omitempty"`
	// +optional
	S1 *string `json:"S1,omitempty"`
	// +optional
	S10 *string `json:"S10,omitempty"`
	// +optional
	S11 *string `json:"S11,omitempty"`
	// +optional
	S12 *string `json:"S12,omitempty"`
	// +optional
	S13 *string `json:"S13,omitempty"`
	// +optional
	S2 *string `json:"S2,omitempty"`
	// +optional
	S3 *string `json:"S3,omitempty"`
	// +optional
	S4 *string `json:"S4,omitempty"`
	// +optional
	S5 *string `json:"S5,omitempty"`
	// +optional
	S6 *string `json:"S6,omitempty"`
	// +optional
	S7 *string `json:"S7,omitempty"`
	// +optional
	S8 *string `json:"S8,omitempty"`
	// +optional
	S9 *string `json:"S9,omitempty"`
}

// AIGatewayOtelObservation is a nested object of the Cloudflare API schema.
type AIGatewayOtelObservation struct {
	// +optional
	Authorization *string `json:"authorization,omitempty"`
	// +optional
	ContentType *string `json:"content_type,omitempty"`
	// +optional
	Headers map[string]string `json:"headers,omitempty"`
	// +optional
	URL *string `json:"url,omitempty"`
}

// AIGatewaySpendLimitsObservation is a nested object of the Cloudflare API schema.
type AIGatewaySpendLimitsObservation struct {
	// +optional
	Enabled *bool `json:"enabled,omitempty"`
	// +optional
	Rules []AIGatewaySpendLimitsRulesObservation `json:"rules,omitempty"`
}

// AIGatewaySpendLimitsRulesObservation is a nested object of the Cloudflare API schema.
type AIGatewaySpendLimitsRulesObservation struct {
	// +optional
	Enabled *bool `json:"enabled,omitempty"`
	// +optional
	ID *string `json:"id,omitempty"`
	// +kubebuilder:validation:Type=number
	// +optional
	Limit *float64 `json:"limit,omitempty"`
	// +optional
	LimitType *string `json:"limitType,omitempty"`
	// +optional
	Metadata map[string]AIGatewaySpendLimitsRulesMetadataObservation `json:"metadata,omitempty"`
	// +optional
	Model *AIGatewaySpendLimitsRulesModelObservation `json:"model,omitempty"`
	// +optional
	Provider *AIGatewaySpendLimitsRulesProviderObservation `json:"provider,omitempty"`
	// +optional
	Technique *string `json:"technique,omitempty"`
	// +optional
	Window *int64 `json:"window,omitempty"`
}

// AIGatewaySpendLimitsRulesMetadataObservation is a nested object of the Cloudflare API schema.
type AIGatewaySpendLimitsRulesMetadataObservation struct {
	// +optional
	Mode *string `json:"mode,omitempty"`
	// +optional
	Values []string `json:"values,omitempty"`
}

// AIGatewaySpendLimitsRulesModelObservation is a nested object of the Cloudflare API schema.
type AIGatewaySpendLimitsRulesModelObservation struct {
	// +optional
	Mode *string `json:"mode,omitempty"`
	// +optional
	Values []string `json:"values,omitempty"`
}

// AIGatewaySpendLimitsRulesProviderObservation is a nested object of the Cloudflare API schema.
type AIGatewaySpendLimitsRulesProviderObservation struct {
	// +optional
	Mode *string `json:"mode,omitempty"`
	// +optional
	Values []string `json:"values,omitempty"`
}

// AIGatewayStripeObservation is a nested object of the Cloudflare API schema.
type AIGatewayStripeObservation struct {
	// +optional
	Authorization *string `json:"authorization,omitempty"`
	// +optional
	UsageEvents []AIGatewayStripeUsageEventsObservation `json:"usage_events,omitempty"`
}

// AIGatewayStripeUsageEventsObservation is a nested object of the Cloudflare API schema.
type AIGatewayStripeUsageEventsObservation struct {
	// +optional
	Payload *string `json:"payload,omitempty"`
}

// AIGatewaySpec defines the desired state of a AIGateway.
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.cache_invalidate_on_update))",message="forProvider.cache_invalidate_on_update is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.cache_ttl))",message="forProvider.cache_ttl is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.collect_logs))",message="forProvider.collect_logs is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.id))",message="forProvider.id is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.rate_limiting_interval))",message="forProvider.rate_limiting_interval is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.rate_limiting_limit))",message="forProvider.rate_limiting_limit is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="size(self.accountRef.name) > 0 && size(self.accountRef.name) <= 253",message="accountRef.name must name a CloudflareAccount in this namespace (1-253 characters)"
type AIGatewaySpec struct {
	commonv1alpha1.ResourceSpec `json:",inline"`
	// ForProvider holds the Cloudflare API fields, named exactly as in the API.
	ForProvider AIGatewayParameters `json:"forProvider"`
}

// AIGatewayStatus defines the observed state of a AIGateway.
type AIGatewayStatus struct {
	commonv1alpha1.ResourceStatus `json:",inline"`
	// AtProvider is the resource as last read from the Cloudflare API.
	// +optional
	AtProvider AIGatewayObservation `json:"atProvider,omitempty"`
}

// AIGateway is a Cloudflare ai-gateway gateways (x-fern-sdk-group-name "ai-gateway.gateways").
//
// Created at /accounts/{account_id}/ai-gateway/gateways, managed at /accounts/{account_id}/ai-gateway/gateways/{id} (account scope).
// Default deletion policy: Delete.
// Immutable fields: id.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=cfaigw,categories={cloudflare,managed,aigateway}
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || self.spec.accountRef.name == oldSelf.spec.accountRef.name",message="spec.accountRef is immutable once the resource exists (status.id is set): the resource lives in that account. To move it, delete this object (deletionPolicy Orphan keeps the resource) and create a new one"
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.id) || !has(self.spec.forProvider) || !has(self.spec.forProvider.id) || self.spec.forProvider.id == oldSelf.spec.forProvider.id || (has(oldSelf.status.atProvider) && has(oldSelf.status.atProvider.id) && oldSelf.status.atProvider.id == self.spec.forProvider.id)",message="forProvider.id is immutable once the resource exists (status.id is set): recreate the object to change it, or set it to the value Cloudflare reports (status.atProvider.id)"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="COLLECT-LOGS",type="boolean",JSONPath=".status.atProvider.collect_logs"
// +kubebuilder:printcolumn:name="CACHE-TTL",type="integer",JSONPath=".status.atProvider.cache_ttl",priority=1
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type AIGateway struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec AIGatewaySpec `json:"spec"`
	// +optional
	Status AIGatewayStatus `json:"status,omitempty"`
}

// GetResourceSpec implements commonv1alpha1.Managed.
func (o *AIGateway) GetResourceSpec() *commonv1alpha1.ResourceSpec { return &o.Spec.ResourceSpec }

// GetResourceStatus implements commonv1alpha1.Managed.
func (o *AIGateway) GetResourceStatus() *commonv1alpha1.ResourceStatus {
	return &o.Status.ResourceStatus
}

// AIGatewayList is a list of AIGateway.
//
// +kubebuilder:object:root=true
type AIGatewayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AIGateway `json:"items"`
}

var _ commonv1alpha1.Managed = &AIGateway{}
