// Code generated by flaregen. DO NOT EDIT.

// Package v1alpha1 contains the AIGateway kinds of the flare.dev API group (product aigateway),
// generated by cmd/flaregen from the Cloudflare OpenAPI operations with
// x-fern-sdk-group-name ai-gateway.gateways.
//
// Every flare-operator kind shares the API group; other packages under api/ register
// their kinds in the same GroupVersion.
//
// flaregen emits the deepcopy functions and the CRD YAML itself (make generate-crds);
// controller-gen must not be run over this package, and the package markers keep
// it out of controller-gen's CRD and object generators.
//
// +kubebuilder:skip
// +kubebuilder:object:generate=false
// +groupName=flare.dev
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	// GroupVersion is the API group and version of this package.
	GroupVersion = schema.GroupVersion{Group: "flare.dev", Version: "v1alpha1"}

	// SchemeBuilder registers this package's kinds.
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds this package's kinds to a scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

func addKnownTypes(s *runtime.Scheme) error {
	s.AddKnownTypes(GroupVersion,
		&AIGateway{}, &AIGatewayList{},
	)
	metav1.AddToGroupVersion(s, GroupVersion)
	return nil
}
