// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayDlpObservation) DeepCopyInto(out *AIGatewayDlpObservation) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]AIGatewayDlpPoliciesObservation, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayDlpObservation) DeepCopy() *AIGatewayDlpObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewayDlpObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayDlpParameters) DeepCopyInto(out *AIGatewayDlpParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]AIGatewayDlpPoliciesParameters, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayDlpParameters) DeepCopy() *AIGatewayDlpParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewayDlpParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayDlpPoliciesObservation) DeepCopyInto(out *AIGatewayDlpPoliciesObservation) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Check != nil {
		in, out := &in.Check, &out.Check
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayDlpPoliciesObservation) DeepCopy() *AIGatewayDlpPoliciesObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewayDlpPoliciesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayDlpPoliciesParameters) DeepCopyInto(out *AIGatewayDlpPoliciesParameters) {
	*out = *in
	if in.Check != nil {
		in, out := &in.Check, &out.Check
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayDlpPoliciesParameters) DeepCopy() *AIGatewayDlpPoliciesParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewayDlpPoliciesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayGuardrailsObservation) DeepCopyInto(out *AIGatewayGuardrailsObservation) {
	*out = *in
	if in.Prompt != nil {
		in, out := &in.Prompt, &out.Prompt
		*out = new(AIGatewayGuardrailsPromptObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(AIGatewayGuardrailsResponseObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayGuardrailsObservation) DeepCopy() *AIGatewayGuardrailsObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewayGuardrailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayGuardrailsParameters) DeepCopyInto(out *AIGatewayGuardrailsParameters) {
	*out = *in
	in.Prompt.DeepCopyInto(&out.Prompt)
	in.Response.DeepCopyInto(&out.Response)
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayGuardrailsParameters) DeepCopy() *AIGatewayGuardrailsParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewayGuardrailsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayGuardrailsPromptObservation) DeepCopyInto(out *AIGatewayGuardrailsPromptObservation) {
	*out = *in
	if in.P1 != nil {
		in, out := &in.P1, &out.P1
		*out = new(string)
		**out = **in
	}
	if in.S1 != nil {
		in, out := &in.S1, &out.S1
		*out = new(string)
		**out = **in
	}
	if in.S10 != nil {
		in, out := &in.S10, &out.S10
		*out = new(string)
		**out = **in
	}
	if in.S11 != nil {
		in, out := &in.S11, &out.S11
		*out = new(string)
		**out = **in
	}
	if in.S12 != nil {
		in, out := &in.S12, &out.S12
		*out = new(string)
		**out = **in
	}
	if in.S13 != nil {
		in, out := &in.S13, &out.S13
		*out = new(string)
		**out = **in
	}
	if in.S2 != nil {
		in, out := &in.S2, &out.S2
		*out = new(string)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(string)
		**out = **in
	}
	if in.S4 != nil {
		in, out := &in.S4, &out.S4
		*out = new(string)
		**out = **in
	}
	if in.S5 != nil {
		in, out := &in.S5, &out.S5
		*out = new(string)
		**out = **in
	}
	if in.S6 != nil {
		in, out := &in.S6, &out.S6
		*out = new(string)
		**out = **in
	}
	if in.S7 != nil {
		in, out := &in.S7, &out.S7
		*out = new(string)
		**out = **in
	}
	if in.S8 != nil {
		in, out := &in.S8, &out.S8
		*out = new(string)
		**out = **in
	}
	if in.S9 != nil {
		in, out := &in.S9, &out.S9
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayGuardrailsPromptObservation) DeepCopy() *AIGatewayGuardrailsPromptObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewayGuardrailsPromptObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayGuardrailsPromptParameters) DeepCopyInto(out *AIGatewayGuardrailsPromptParameters) {
	*out = *in
	if in.P1 != nil {
		in, out := &in.P1, &out.P1
		*out = new(string)
		**out = **in
	}
	if in.S1 != nil {
		in, out := &in.S1, &out.S1
		*out = new(string)
		**out = **in
	}
	if in.S10 != nil {
		in, out := &in.S10, &out.S10
		*out = new(string)
		**out = **in
	}
	if in.S11 != nil {
		in, out := &in.S11, &out.S11
		*out = new(string)
		**out = **in
	}
	if in.S12 != nil {
		in, out := &in.S12, &out.S12
		*out = new(string)
		**out = **in
	}
	if in.S13 != nil {
		in, out := &in.S13, &out.S13
		*out = new(string)
		**out = **in
	}
	if in.S2 != nil {
		in, out := &in.S2, &out.S2
		*out = new(string)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(string)
		**out = **in
	}
	if in.S4 != nil {
		in, out := &in.S4, &out.S4
		*out = new(string)
		**out = **in
	}
	if in.S5 != nil {
		in, out := &in.S5, &out.S5
		*out = new(string)
		**out = **in
	}
	if in.S6 != nil {
		in, out := &in.S6, &out.S6
		*out = new(string)
		**out = **in
	}
	if in.S7 != nil {
		in, out := &in.S7, &out.S7
		*out = new(string)
		**out = **in
	}
	if in.S8 != nil {
		in, out := &in.S8, &out.S8
		*out = new(string)
		**out = **in
	}
	if in.S9 != nil {
		in, out := &in.S9, &out.S9
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayGuardrailsPromptParameters) DeepCopy() *AIGatewayGuardrailsPromptParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewayGuardrailsPromptParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayGuardrailsResponseObservation) DeepCopyInto(out *AIGatewayGuardrailsResponseObservation) {
	*out = *in
	if in.P1 != nil {
		in, out := &in.P1, &out.P1
		*out = new(string)
		**out = **in
	}
	if in.S1 != nil {
		in, out := &in.S1, &out.S1
		*out = new(string)
		**out = **in
	}
	if in.S10 != nil {
		in, out := &in.S10, &out.S10
		*out = new(string)
		**out = **in
	}
	if in.S11 != nil {
		in, out := &in.S11, &out.S11
		*out = new(string)
		**out = **in
	}
	if in.S12 != nil {
		in, out := &in.S12, &out.S12
		*out = new(string)
		**out = **in
	}
	if in.S13 != nil {
		in, out := &in.S13, &out.S13
		*out = new(string)
		**out = **in
	}
	if in.S2 != nil {
		in, out := &in.S2, &out.S2
		*out = new(string)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(string)
		**out = **in
	}
	if in.S4 != nil {
		in, out := &in.S4, &out.S4
		*out = new(string)
		**out = **in
	}
	if in.S5 != nil {
		in, out := &in.S5, &out.S5
		*out = new(string)
		**out = **in
	}
	if in.S6 != nil {
		in, out := &in.S6, &out.S6
		*out = new(string)
		**out = **in
	}
	if in.S7 != nil {
		in, out := &in.S7, &out.S7
		*out = new(string)
		**out = **in
	}
	if in.S8 != nil {
		in, out := &in.S8, &out.S8
		*out = new(string)
		**out = **in
	}
	if in.S9 != nil {
		in, out := &in.S9, &out.S9
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayGuardrailsResponseObservation) DeepCopy() *AIGatewayGuardrailsResponseObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewayGuardrailsResponseObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayGuardrailsResponseParameters) DeepCopyInto(out *AIGatewayGuardrailsResponseParameters) {
	*out = *in
	if in.P1 != nil {
		in, out := &in.P1, &out.P1
		*out = new(string)
		**out = **in
	}
	if in.S1 != nil {
		in, out := &in.S1, &out.S1
		*out = new(string)
		**out = **in
	}
	if in.S10 != nil {
		in, out := &in.S10, &out.S10
		*out = new(string)
		**out = **in
	}
	if in.S11 != nil {
		in, out := &in.S11, &out.S11
		*out = new(string)
		**out = **in
	}
	if in.S12 != nil {
		in, out := &in.S12, &out.S12
		*out = new(string)
		**out = **in
	}
	if in.S13 != nil {
		in, out := &in.S13, &out.S13
		*out = new(string)
		**out = **in
	}
	if in.S2 != nil {
		in, out := &in.S2, &out.S2
		*out = new(string)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(string)
		**out = **in
	}
	if in.S4 != nil {
		in, out := &in.S4, &out.S4
		*out = new(string)
		**out = **in
	}
	if in.S5 != nil {
		in, out := &in.S5, &out.S5
		*out = new(string)
		**out = **in
	}
	if in.S6 != nil {
		in, out := &in.S6, &out.S6
		*out = new(string)
		**out = **in
	}
	if in.S7 != nil {
		in, out := &in.S7, &out.S7
		*out = new(string)
		**out = **in
	}
	if in.S8 != nil {
		in, out := &in.S8, &out.S8
		*out = new(string)
		**out = **in
	}
	if in.S9 != nil {
		in, out := &in.S9, &out.S9
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayGuardrailsResponseParameters) DeepCopy() *AIGatewayGuardrailsResponseParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewayGuardrailsResponseParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayObservation) DeepCopyInto(out *AIGatewayObservation) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(bool)
		**out = **in
	}
	if in.ByokOnly != nil {
		in, out := &in.ByokOnly, &out.ByokOnly
		*out = new(bool)
		**out = **in
	}
	if in.CacheInvalidateOnUpdate != nil {
		in, out := &in.CacheInvalidateOnUpdate, &out.CacheInvalidateOnUpdate
		*out = new(bool)
		**out = **in
	}
	if in.CacheTTL != nil {
		in, out := &in.CacheTTL, &out.CacheTTL
		*out = new(int64)
		**out = **in
	}
	if in.CollectLogs != nil {
		in, out := &in.CollectLogs, &out.CollectLogs
		*out = new(bool)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.Dlp != nil {
		in, out := &in.Dlp, &out.Dlp
		*out = new(AIGatewayDlpObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = new(AIGatewayGuardrailsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.LogClassification != nil {
		in, out := &in.LogClassification, &out.LogClassification
		*out = new(bool)
		**out = **in
	}
	if in.LogManagement != nil {
		in, out := &in.LogManagement, &out.LogManagement
		*out = new(int64)
		**out = **in
	}
	if in.LogManagementStrategy != nil {
		in, out := &in.LogManagementStrategy, &out.LogManagementStrategy
		*out = new(string)
		**out = **in
	}
	if in.Logpush != nil {
		in, out := &in.Logpush, &out.Logpush
		*out = new(bool)
		**out = **in
	}
	if in.LogpushPublicKey != nil {
		in, out := &in.LogpushPublicKey, &out.LogpushPublicKey
		*out = new(string)
		**out = **in
	}
	if in.ModifiedAt != nil {
		in, out := &in.ModifiedAt, &out.ModifiedAt
		*out = new(string)
		**out = **in
	}
	if in.Otel != nil {
		in, out := &in.Otel, &out.Otel
		*out = make([]AIGatewayOtelObservation, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
	if in.RateLimitingInterval != nil {
		in, out := &in.RateLimitingInterval, &out.RateLimitingInterval
		*out = new(int64)
		**out = **in
	}
	if in.RateLimitingLimit != nil {
		in, out := &in.RateLimitingLimit, &out.RateLimitingLimit
		*out = new(int64)
		**out = **in
	}
	if in.RateLimitingTechnique != nil {
		in, out := &in.RateLimitingTechnique, &out.RateLimitingTechnique
		*out = new(string)
		**out = **in
	}
	if in.RetryBackoff != nil {
		in, out := &in.RetryBackoff, &out.RetryBackoff
		*out = new(string)
		**out = **in
	}
	if in.RetryDelay != nil {
		in, out := &in.RetryDelay, &out.RetryDelay
		*out = new(int64)
		**out = **in
	}
	if in.RetryMaxAttempts != nil {
		in, out := &in.RetryMaxAttempts, &out.RetryMaxAttempts
		*out = new(int64)
		**out = **in
	}
	if in.SpendLimits != nil {
		in, out := &in.SpendLimits, &out.SpendLimits
		*out = new(AIGatewaySpendLimitsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.StoreID != nil {
		in, out := &in.StoreID, &out.StoreID
		*out = new(string)
		**out = **in
	}
	if in.Stripe != nil {
		in, out := &in.Stripe, &out.Stripe
		*out = new(AIGatewayStripeObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkersAiBillingMode != nil {
		in, out := &in.WorkersAiBillingMode, &out.WorkersAiBillingMode
		*out = new(string)
		**out = **in
	}
	if in.Zdr != nil {
		in, out := &in.Zdr, &out.Zdr
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayObservation) DeepCopy() *AIGatewayObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewayObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayOtelObservation) DeepCopyInto(out *AIGatewayOtelObservation) {
	*out = *in
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = new(string)
		**out = **in
	}
	if in.ContentType != nil {
		in, out := &in.ContentType, &out.ContentType
		*out = new(string)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for k0, v0 := range *in {
			(*out)[k0] = v0
		}
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayOtelObservation) DeepCopy() *AIGatewayOtelObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewayOtelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayOtelParameters) DeepCopyInto(out *AIGatewayOtelParameters) {
	*out = *in
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = new(string)
		**out = **in
	}
	if in.ContentType != nil {
		in, out := &in.ContentType, &out.ContentType
		*out = new(string)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for k0, v0 := range *in {
			(*out)[k0] = v0
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayOtelParameters) DeepCopy() *AIGatewayOtelParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewayOtelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayParameters) DeepCopyInto(out *AIGatewayParameters) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(bool)
		**out = **in
	}
	if in.ByokOnly != nil {
		in, out := &in.ByokOnly, &out.ByokOnly
		*out = new(bool)
		**out = **in
	}
	if in.CacheInvalidateOnUpdate != nil {
		in, out := &in.CacheInvalidateOnUpdate, &out.CacheInvalidateOnUpdate
		*out = new(bool)
		**out = **in
	}
	if in.CacheTTL != nil {
		in, out := &in.CacheTTL, &out.CacheTTL
		*out = new(int64)
		**out = **in
	}
	if in.CollectLogs != nil {
		in, out := &in.CollectLogs, &out.CollectLogs
		*out = new(bool)
		**out = **in
	}
	if in.Dlp != nil {
		in, out := &in.Dlp, &out.Dlp
		*out = new(AIGatewayDlpParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = new(AIGatewayGuardrailsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LogClassification != nil {
		in, out := &in.LogClassification, &out.LogClassification
		*out = new(bool)
		**out = **in
	}
	if in.LogManagement != nil {
		in, out := &in.LogManagement, &out.LogManagement
		*out = new(int64)
		**out = **in
	}
	if in.LogManagementStrategy != nil {
		in, out := &in.LogManagementStrategy, &out.LogManagementStrategy
		*out = new(string)
		**out = **in
	}
	if in.Logpush != nil {
		in, out := &in.Logpush, &out.Logpush
		*out = new(bool)
		**out = **in
	}
	if in.LogpushPublicKey != nil {
		in, out := &in.LogpushPublicKey, &out.LogpushPublicKey
		*out = new(string)
		**out = **in
	}
	if in.Otel != nil {
		in, out := &in.Otel, &out.Otel
		*out = make([]AIGatewayOtelParameters, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
	if in.RateLimitingInterval != nil {
		in, out := &in.RateLimitingInterval, &out.RateLimitingInterval
		*out = new(int64)
		**out = **in
	}
	if in.RateLimitingLimit != nil {
		in, out := &in.RateLimitingLimit, &out.RateLimitingLimit
		*out = new(int64)
		**out = **in
	}
	if in.RateLimitingTechnique != nil {
		in, out := &in.RateLimitingTechnique, &out.RateLimitingTechnique
		*out = new(string)
		**out = **in
	}
	if in.RetryBackoff != nil {
		in, out := &in.RetryBackoff, &out.RetryBackoff
		*out = new(string)
		**out = **in
	}
	if in.RetryDelay != nil {
		in, out := &in.RetryDelay, &out.RetryDelay
		*out = new(int64)
		**out = **in
	}
	if in.RetryMaxAttempts != nil {
		in, out := &in.RetryMaxAttempts, &out.RetryMaxAttempts
		*out = new(int64)
		**out = **in
	}
	if in.SpendLimits != nil {
		in, out := &in.SpendLimits, &out.SpendLimits
		*out = new(AIGatewaySpendLimitsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.StoreID != nil {
		in, out := &in.StoreID, &out.StoreID
		*out = new(string)
		**out = **in
	}
	if in.Stripe != nil {
		in, out := &in.Stripe, &out.Stripe
		*out = new(AIGatewayStripeParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkersAiBillingMode != nil {
		in, out := &in.WorkersAiBillingMode, &out.WorkersAiBillingMode
		*out = new(string)
		**out = **in
	}
	if in.Zdr != nil {
		in, out := &in.Zdr, &out.Zdr
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayParameters) DeepCopy() *AIGatewayParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewayParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewaySpendLimitsObservation) DeepCopyInto(out *AIGatewaySpendLimitsObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]AIGatewaySpendLimitsRulesObservation, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewaySpendLimitsObservation) DeepCopy() *AIGatewaySpendLimitsObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpendLimitsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewaySpendLimitsParameters) DeepCopyInto(out *AIGatewaySpendLimitsParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]AIGatewaySpendLimitsRulesParameters, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewaySpendLimitsParameters) DeepCopy() *AIGatewaySpendLimitsParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpendLimitsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewaySpendLimitsRulesMetadataObservation) DeepCopyInto(out *AIGatewaySpendLimitsRulesMetadataObservation) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewaySpendLimitsRulesMetadataObservation) DeepCopy() *AIGatewaySpendLimitsRulesMetadataObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpendLimitsRulesMetadataObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewaySpendLimitsRulesMetadataParameters) DeepCopyInto(out *AIGatewaySpendLimitsRulesMetadataParameters) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewaySpendLimitsRulesMetadataParameters) DeepCopy() *AIGatewaySpendLimitsRulesMetadataParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpendLimitsRulesMetadataParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewaySpendLimitsRulesModelObservation) DeepCopyInto(out *AIGatewaySpendLimitsRulesModelObservation) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewaySpendLimitsRulesModelObservation) DeepCopy() *AIGatewaySpendLimitsRulesModelObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpendLimitsRulesModelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewaySpendLimitsRulesModelParameters) DeepCopyInto(out *AIGatewaySpendLimitsRulesModelParameters) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewaySpendLimitsRulesModelParameters) DeepCopy() *AIGatewaySpendLimitsRulesModelParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpendLimitsRulesModelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewaySpendLimitsRulesObservation) DeepCopyInto(out *AIGatewaySpendLimitsRulesObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(float64)
		**out = **in
	}
	if in.LimitType != nil {
		in, out := &in.LimitType, &out.LimitType
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]AIGatewaySpendLimitsRulesMetadataObservation, len(*in))
		for k0, v0 := range *in {
			var o0 AIGatewaySpendLimitsRulesMetadataObservation
			v0.DeepCopyInto(&o0)
			(*out)[k0] = o0
		}
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(AIGatewaySpendLimitsRulesModelObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(AIGatewaySpendLimitsRulesProviderObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Technique != nil {
		in, out := &in.Technique, &out.Technique
		*out = new(string)
		**out = **in
	}
	if in.Window != nil {
		in, out := &in.Window, &out.Window
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewaySpendLimitsRulesObservation) DeepCopy() *AIGatewaySpendLimitsRulesObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpendLimitsRulesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewaySpendLimitsRulesParameters) DeepCopyInto(out *AIGatewaySpendLimitsRulesParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]AIGatewaySpendLimitsRulesMetadataParameters, len(*in))
		for k0, v0 := range *in {
			var o0 AIGatewaySpendLimitsRulesMetadataParameters
			v0.DeepCopyInto(&o0)
			(*out)[k0] = o0
		}
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(AIGatewaySpendLimitsRulesModelParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(AIGatewaySpendLimitsRulesProviderParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Technique != nil {
		in, out := &in.Technique, &out.Technique
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewaySpendLimitsRulesParameters) DeepCopy() *AIGatewaySpendLimitsRulesParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpendLimitsRulesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewaySpendLimitsRulesProviderObservation) DeepCopyInto(out *AIGatewaySpendLimitsRulesProviderObservation) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewaySpendLimitsRulesProviderObservation) DeepCopy() *AIGatewaySpendLimitsRulesProviderObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpendLimitsRulesProviderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewaySpendLimitsRulesProviderParameters) DeepCopyInto(out *AIGatewaySpendLimitsRulesProviderParameters) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewaySpendLimitsRulesProviderParameters) DeepCopy() *AIGatewaySpendLimitsRulesProviderParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpendLimitsRulesProviderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayStripeObservation) DeepCopyInto(out *AIGatewayStripeObservation) {
	*out = *in
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = new(string)
		**out = **in
	}
	if in.UsageEvents != nil {
		in, out := &in.UsageEvents, &out.UsageEvents
		*out = make([]AIGatewayStripeUsageEventsObservation, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayStripeObservation) DeepCopy() *AIGatewayStripeObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewayStripeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayStripeParameters) DeepCopyInto(out *AIGatewayStripeParameters) {
	*out = *in
	if in.UsageEvents != nil {
		in, out := &in.UsageEvents, &out.UsageEvents
		*out = make([]AIGatewayStripeUsageEventsParameters, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayStripeParameters) DeepCopy() *AIGatewayStripeParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewayStripeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayStripeUsageEventsObservation) DeepCopyInto(out *AIGatewayStripeUsageEventsObservation) {
	*out = *in
	if in.Payload != nil {
		in, out := &in.Payload, &out.Payload
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayStripeUsageEventsObservation) DeepCopy() *AIGatewayStripeUsageEventsObservation {
	if in == nil {
		return nil
	}
	out := new(AIGatewayStripeUsageEventsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayStripeUsageEventsParameters) DeepCopyInto(out *AIGatewayStripeUsageEventsParameters) {
	*out = *in
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayStripeUsageEventsParameters) DeepCopy() *AIGatewayStripeUsageEventsParameters {
	if in == nil {
		return nil
	}
	out := new(AIGatewayStripeUsageEventsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewaySpec) DeepCopyInto(out *AIGatewaySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewaySpec) DeepCopy() *AIGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(AIGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayStatus) DeepCopyInto(out *AIGatewayStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayStatus) DeepCopy() *AIGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(AIGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGateway) DeepCopyInto(out *AIGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGateway) DeepCopy() *AIGateway {
	if in == nil {
		return nil
	}
	out := new(AIGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AIGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *AIGatewayList) DeepCopyInto(out *AIGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *AIGatewayList) DeepCopy() *AIGatewayList {
	if in == nil {
		return nil
	}
	out := new(AIGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AIGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
