// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	commonv1alpha1 "github.com/chenhunghan/flare-operator/api/common/v1alpha1"
)

// R2BucketParameters are the configurable fields of a R2Bucket: the request
// bodies of POST /accounts/{account_id}/r2/buckets and PATCH /accounts/{account_id}/r2/buckets/{bucket_name}.
type R2BucketParameters struct {
	// cors is managed through PUT /accounts/{account_id}/r2/buckets/{bucket_name}/cors (and read with GET); unset leaves it as it is; an empty value ({}, or with empty lists only) removes it with DELETE.
	// +optional
	Cors *R2BucketCorsParameters `json:"cors,omitempty"`
	// Jurisdiction where objects in this bucket are guaranteed to be stored. Sent as the cf-r2-jurisdiction header of every request; it selects where the resource lives, so it cannot be set, changed or removed once the resource exists.
	// +kubebuilder:validation:Enum="default";"eu";"us";"fedramp";"fedramp-high"
	// +optional
	Jurisdiction *string `json:"jurisdiction,omitempty"`
	// Location of the bucket.
	// +kubebuilder:validation:Enum="apac";"eeur";"enam";"weur";"wnam";"oc"
	// +optional
	LocationHint *string `json:"locationHint,omitempty"`
	// Name of the bucket.
	// +kubebuilder:validation:Pattern=`^[a-z0-9][a-z0-9-]*[a-z0-9]`
	// +kubebuilder:validation:MinLength=3
	// +kubebuilder:validation:MaxLength=64
	// Required unless managementPolicies exclude Create (CEL rule on the spec).
	// +optional
	Name *string `json:"name,omitempty"`
	// Storage class for newly uploaded objects, unless specified otherwise.
	// +kubebuilder:validation:Enum="Standard";"InfrequentAccess"
	// +optional
	StorageClass *string `json:"storageClass,omitempty"`
}

// R2BucketCorsParameters is a nested object of the Cloudflare API schema.
//
// cors is managed through PUT /accounts/{account_id}/r2/buckets/{bucket_name}/cors (and read with GET); unset leaves it as it is; an empty value ({}, or with empty lists only) removes it with DELETE.
type R2BucketCorsParameters struct {
	// +optional
	Rules []R2BucketCorsRulesParameters `json:"rules,omitempty"`
}

// R2BucketCorsRulesParameters is a nested object of the Cloudflare API schema.
type R2BucketCorsRulesParameters struct {
	// Object specifying allowed origins, methods and headers for this CORS rule.
	// +kubebuilder:validation:Required
	Allowed R2BucketCorsRulesAllowedParameters `json:"allowed"`
	// Specifies the headers that can be exposed back, and accessed by, the JavaScript making the cross-origin request. If you need to access headers beyond the safelisted response headers, such as Content-Encoding or cf-cache-status, you must specify it here.
	// +optional
	ExposeHeaders []string `json:"exposeHeaders,omitempty"`
	// Identifier for this rule.
	// +optional
	ID *string `json:"id,omitempty"`
	// Specifies the amount of time (in seconds) browsers are allowed to cache CORS preflight responses. Browsers may limit this to 2 hours or less, even if the maximum value (86400) is specified.
	// +kubebuilder:validation:Type=number
	// +optional
	MaxAgeSeconds *float64 `json:"maxAgeSeconds,omitempty"`
}

// R2BucketCorsRulesAllowedParameters is a nested object of the Cloudflare API schema.
//
// Object specifying allowed origins, methods and headers for this CORS rule.
type R2BucketCorsRulesAllowedParameters struct {
	// Specifies the value for the Access-Control-Allow-Headers header R2 sets when requesting objects in this bucket from a browser. Cross-origin requests that include custom headers (e.g. x-user-id) should specify these headers as AllowedHeaders.
	// +optional
	Headers []string `json:"headers,omitempty"`
	// Specifies the value for the Access-Control-Allow-Methods header R2 sets when requesting objects in a bucket from a browser.
	// +kubebuilder:validation:items:Enum="GET";"PUT";"POST";"DELETE";"HEAD"
	// +kubebuilder:validation:Required
	Methods []string `json:"methods"`
	// Specifies the value for the Access-Control-Allow-Origin header R2 sets when requesting objects in a bucket from a browser.
	// +kubebuilder:validation:Required
	Origins []string `json:"origins"`
}

// R2BucketObservation is the R2Bucket as returned by GET /accounts/{account_id}/r2/buckets/{bucket_name}.
type R2BucketObservation struct {
	// cors as returned by GET /accounts/{account_id}/r2/buckets/{bucket_name}/cors (absent when not configured).
	// +optional
	Cors *R2BucketCorsObservation `json:"cors,omitempty"`
	// Creation timestamp.
	// +optional
	CreationDate *string `json:"creation_date,omitempty"`
	// Jurisdiction where objects in this bucket are guaranteed to be stored.
	// +optional
	Jurisdiction *string `json:"jurisdiction,omitempty"`
	// Location of the bucket.
	// +optional
	Location *string `json:"location,omitempty"`
	// Name of the bucket.
	// +optional
	Name *string `json:"name,omitempty"`
	// Storage class for newly uploaded objects, unless specified otherwise.
	// +optional
	StorageClass *string `json:"storage_class,omitempty"`
}

// R2BucketCorsObservation is a nested object of the Cloudflare API schema.
//
// cors as returned by GET /accounts/{account_id}/r2/buckets/{bucket_name}/cors (absent when not configured).
type R2BucketCorsObservation struct {
	// +optional
	Rules []R2BucketCorsRulesObservation `json:"rules,omitempty"`
}

// R2BucketCorsRulesObservation is a nested object of the Cloudflare API schema.
type R2BucketCorsRulesObservation struct {
	// Object specifying allowed origins, methods and headers for this CORS rule.
	// +optional
	Allowed *R2BucketCorsRulesAllowedObservation `json:"allowed,omitempty"`
	// Specifies the headers that can be exposed back, and accessed by, the JavaScript making the cross-origin request. If you need to access headers beyond the safelisted response headers, such as Content-Encoding or cf-cache-status, you must specify it here.
	// +optional
	ExposeHeaders []string `json:"exposeHeaders,omitempty"`
	// Identifier for this rule.
	// +optional
	ID *string `json:"id,omitempty"`
	// Specifies the amount of time (in seconds) browsers are allowed to cache CORS preflight responses. Browsers may limit this to 2 hours or less, even if the maximum value (86400) is specified.
	// +kubebuilder:validation:Type=number
	// +optional
	MaxAgeSeconds *float64 `json:"maxAgeSeconds,omitempty"`
}

// R2BucketCorsRulesAllowedObservation is a nested object of the Cloudflare API schema.
//
// Object specifying allowed origins, methods and headers for this CORS rule.
type R2BucketCorsRulesAllowedObservation struct {
	// Specifies the value for the Access-Control-Allow-Headers header R2 sets when requesting objects in this bucket from a browser. Cross-origin requests that include custom headers (e.g. x-user-id) should specify these headers as AllowedHeaders.
	// +optional
	Headers []string `json:"headers,omitempty"`
	// Specifies the value for the Access-Control-Allow-Methods header R2 sets when requesting objects in a bucket from a browser.
	// +optional
	Methods []string `json:"methods,omitempty"`
	// Specifies the value for the Access-Control-Allow-Origin header R2 sets when requesting objects in a bucket from a browser.
	// +optional
	Origins []string `json:"origins,omitempty"`
}

// R2BucketSpec defines the desired state of a R2Bucket.
// +kubebuilder:validation:XValidation:rule="!(!has(self.managementPolicies) || size(self.managementPolicies) == 0 || '*' in self.managementPolicies || 'Create' in self.managementPolicies) || (has(self.forProvider) && has(self.forProvider.name))",message="forProvider.name is required unless managementPolicies exclude Create (e.g. [\"Observe\"])"
// +kubebuilder:validation:XValidation:rule="size(self.accountRef.name) > 0 && size(self.accountRef.name) <= 253",message="accountRef.name must name a CloudflareAccount in this namespace (1-253 characters)"
type R2BucketSpec struct {
	commonv1alpha1.ResourceSpec `json:",inline"`
	// ForProvider holds the Cloudflare API fields, named exactly as in the API.
	ForProvider R2BucketParameters `json:"forProvider"`
}

// R2BucketStatus defines the observed state of a R2Bucket.
type R2BucketStatus struct {
	commonv1alpha1.ResourceStatus `json:",inline"`
	// AtProvider is the resource as last read from the Cloudflare API.
	// +optional
	AtProvider R2BucketObservation `json:"atProvider,omitempty"`
}

// R2Bucket is a Cloudflare r2 buckets (x-fern-sdk-group-name "r2.buckets").
//
// Created at /accounts/{account_id}/r2/buckets, managed at /accounts/{account_id}/r2/buckets/{id} (account scope).
// Default deletion policy: Orphan.
// Immutable fields: jurisdiction, locationHint, name.
// Write-only fields: locationHint.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=cfr2;cfbucket,categories={cloudflare,managed,r2}
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || self.spec.accountRef.name == oldSelf.spec.accountRef.name",message="spec.accountRef is immutable once the resource exists (status.id is set): the resource lives in that account. To move it, delete this object (deletionPolicy Orphan keeps the resource) and create a new one"
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || (has(self.spec.forProvider) && has(self.spec.forProvider.jurisdiction) ? self.spec.forProvider.jurisdiction : \"default\") == (has(oldSelf.spec.forProvider) && has(oldSelf.spec.forProvider.jurisdiction) ? oldSelf.spec.forProvider.jurisdiction : \"default\")",message="forProvider.jurisdiction is immutable once the resource exists (status.id is set): it is sent as the cf-r2-jurisdiction header and selects where the resource lives (unset means \"default\"); setting, changing or removing it is refused. Recreate the object to change it"
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.locationHint) || !has(self.spec.forProvider) || !has(self.spec.forProvider.locationHint) || self.spec.forProvider.locationHint == oldSelf.spec.forProvider.locationHint",message="forProvider.locationHint is immutable once the resource exists (status.id is set): recreate the object to change it"
// +kubebuilder:validation:XValidation:rule="!(has(oldSelf.status) && has(oldSelf.status.id) && size(oldSelf.status.id) > 0) || !has(oldSelf.spec.forProvider) || !has(oldSelf.spec.forProvider.name) || !has(self.spec.forProvider) || !has(self.spec.forProvider.name) || self.spec.forProvider.name == oldSelf.spec.forProvider.name || (has(oldSelf.status.atProvider) && has(oldSelf.status.atProvider.name) && oldSelf.status.atProvider.name == self.spec.forProvider.name)",message="forProvider.name is immutable once the resource exists (status.id is set): recreate the object to change it, or set it to the value Cloudflare reports (status.atProvider.name)"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="LOCATION",type="string",JSONPath=".status.atProvider.location"
// +kubebuilder:printcolumn:name="STORAGE-CLASS",type="string",JSONPath=".status.atProvider.storage_class"
// +kubebuilder:printcolumn:name="JURISDICTION",type="string",JSONPath=".status.atProvider.jurisdiction",priority=1
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type R2Bucket struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec R2BucketSpec `json:"spec"`
	// +optional
	Status R2BucketStatus `json:"status,omitempty"`
}

// GetResourceSpec implements commonv1alpha1.Managed.
func (o *R2Bucket) GetResourceSpec() *commonv1alpha1.ResourceSpec { return &o.Spec.ResourceSpec }

// GetResourceStatus implements commonv1alpha1.Managed.
func (o *R2Bucket) GetResourceStatus() *commonv1alpha1.ResourceStatus {
	return &o.Status.ResourceStatus
}

// R2BucketList is a list of R2Bucket.
//
// +kubebuilder:object:root=true
type R2BucketList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []R2Bucket `json:"items"`
}

var _ commonv1alpha1.Managed = &R2Bucket{}
