// Code generated by flaregen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2BucketCorsObservation) DeepCopyInto(out *R2BucketCorsObservation) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]R2BucketCorsRulesObservation, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2BucketCorsObservation) DeepCopy() *R2BucketCorsObservation {
	if in == nil {
		return nil
	}
	out := new(R2BucketCorsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2BucketCorsParameters) DeepCopyInto(out *R2BucketCorsParameters) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]R2BucketCorsRulesParameters, len(*in))
		for i0 := range *in {
			(*in)[i0].DeepCopyInto(&(*out)[i0])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2BucketCorsParameters) DeepCopy() *R2BucketCorsParameters {
	if in == nil {
		return nil
	}
	out := new(R2BucketCorsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2BucketCorsRulesAllowedObservation) DeepCopyInto(out *R2BucketCorsRulesAllowedObservation) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Origins != nil {
		in, out := &in.Origins, &out.Origins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2BucketCorsRulesAllowedObservation) DeepCopy() *R2BucketCorsRulesAllowedObservation {
	if in == nil {
		return nil
	}
	out := new(R2BucketCorsRulesAllowedObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2BucketCorsRulesAllowedParameters) DeepCopyInto(out *R2BucketCorsRulesAllowedParameters) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Origins != nil {
		in, out := &in.Origins, &out.Origins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2BucketCorsRulesAllowedParameters) DeepCopy() *R2BucketCorsRulesAllowedParameters {
	if in == nil {
		return nil
	}
	out := new(R2BucketCorsRulesAllowedParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2BucketCorsRulesObservation) DeepCopyInto(out *R2BucketCorsRulesObservation) {
	*out = *in
	if in.Allowed != nil {
		in, out := &in.Allowed, &out.Allowed
		*out = new(R2BucketCorsRulesAllowedObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ExposeHeaders != nil {
		in, out := &in.ExposeHeaders, &out.ExposeHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxAgeSeconds != nil {
		in, out := &in.MaxAgeSeconds, &out.MaxAgeSeconds
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2BucketCorsRulesObservation) DeepCopy() *R2BucketCorsRulesObservation {
	if in == nil {
		return nil
	}
	out := new(R2BucketCorsRulesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2BucketCorsRulesParameters) DeepCopyInto(out *R2BucketCorsRulesParameters) {
	*out = *in
	in.Allowed.DeepCopyInto(&out.Allowed)
	if in.ExposeHeaders != nil {
		in, out := &in.ExposeHeaders, &out.ExposeHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxAgeSeconds != nil {
		in, out := &in.MaxAgeSeconds, &out.MaxAgeSeconds
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2BucketCorsRulesParameters) DeepCopy() *R2BucketCorsRulesParameters {
	if in == nil {
		return nil
	}
	out := new(R2BucketCorsRulesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2BucketObservation) DeepCopyInto(out *R2BucketObservation) {
	*out = *in
	if in.Cors != nil {
		in, out := &in.Cors, &out.Cors
		*out = new(R2BucketCorsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = new(string)
		**out = **in
	}
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2BucketObservation) DeepCopy() *R2BucketObservation {
	if in == nil {
		return nil
	}
	out := new(R2BucketObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2BucketParameters) DeepCopyInto(out *R2BucketParameters) {
	*out = *in
	if in.Cors != nil {
		in, out := &in.Cors, &out.Cors
		*out = new(R2BucketCorsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
	if in.LocationHint != nil {
		in, out := &in.LocationHint, &out.LocationHint
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2BucketParameters) DeepCopy() *R2BucketParameters {
	if in == nil {
		return nil
	}
	out := new(R2BucketParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2BucketSpec) DeepCopyInto(out *R2BucketSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2BucketSpec) DeepCopy() *R2BucketSpec {
	if in == nil {
		return nil
	}
	out := new(R2BucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2BucketStatus) DeepCopyInto(out *R2BucketStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2BucketStatus) DeepCopy() *R2BucketStatus {
	if in == nil {
		return nil
	}
	out := new(R2BucketStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2Bucket) DeepCopyInto(out *R2Bucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2Bucket) DeepCopy() *R2Bucket {
	if in == nil {
		return nil
	}
	out := new(R2Bucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *R2Bucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *R2BucketList) DeepCopyInto(out *R2BucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]R2Bucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of the receiver.
func (in *R2BucketList) DeepCopy() *R2BucketList {
	if in == nil {
		return nil
	}
	out := new(R2BucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *R2BucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
