// Package v1alpha1 contains the workers.cloudflare.flare.dev API group (x-fern-sdk-group-name
// "workers.legacy.scripts", first segment "workers"): WorkerScript, a Cloudflare Workers script
// with its modules, bindings and settings.
//
// These types are hand-written (not generated by cmd/flaregen); `make generate manifests`
// (controller-gen) produces their deepcopy methods and CRD.
//
// +kubebuilder:object:generate=true
// +groupName=workers.cloudflare.flare.dev
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

var (
	// GroupVersion is the group version used to register these objects.
	GroupVersion = schema.GroupVersion{Group: "workers.cloudflare.flare.dev", Version: "v1alpha1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme.
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)
