//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "flare.dev/operator/api/common/v1alpha1"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerBinding) DeepCopyInto(out *WorkerBinding) {
	*out = *in
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.JSON != nil {
		in, out := &in.JSON, &out.JSON
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceID != nil {
		in, out := &in.NamespaceID, &out.NamespaceID
		*out = new(string)
		**out = **in
	}
	if in.KVNamespaceRef != nil {
		in, out := &in.KVNamespaceRef, &out.KVNamespaceRef
		*out = new(commonv1alpha1.LocalRef)
		**out = **in
	}
	if in.QueueName != nil {
		in, out := &in.QueueName, &out.QueueName
		*out = new(string)
		**out = **in
	}
	if in.QueueRef != nil {
		in, out := &in.QueueRef, &out.QueueRef
		*out = new(commonv1alpha1.LocalRef)
		**out = **in
	}
	if in.DatabaseID != nil {
		in, out := &in.DatabaseID, &out.DatabaseID
		*out = new(string)
		**out = **in
	}
	if in.D1DatabaseRef != nil {
		in, out := &in.D1DatabaseRef, &out.D1DatabaseRef
		*out = new(commonv1alpha1.LocalRef)
		**out = **in
	}
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
	if in.VPCServiceRef != nil {
		in, out := &in.VPCServiceRef, &out.VPCServiceRef
		*out = new(commonv1alpha1.LocalRef)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(commonv1alpha1.LocalRef)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Entrypoint != nil {
		in, out := &in.Entrypoint, &out.Entrypoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerBinding.
func (in *WorkerBinding) DeepCopy() *WorkerBinding {
	if in == nil {
		return nil
	}
	out := new(WorkerBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerBindingObservation) DeepCopyInto(out *WorkerBindingObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerBindingObservation.
func (in *WorkerBindingObservation) DeepCopy() *WorkerBindingObservation {
	if in == nil {
		return nil
	}
	out := new(WorkerBindingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerModule) DeepCopyInto(out *WorkerModule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerModule.
func (in *WorkerModule) DeepCopy() *WorkerModule {
	if in == nil {
		return nil
	}
	out := new(WorkerModule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerObservability) DeepCopyInto(out *WorkerObservability) {
	*out = *in
	if in.HeadSamplingRate != nil {
		in, out := &in.HeadSamplingRate, &out.HeadSamplingRate
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(WorkerObservabilityLogs)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerObservability.
func (in *WorkerObservability) DeepCopy() *WorkerObservability {
	if in == nil {
		return nil
	}
	out := new(WorkerObservability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerObservabilityLogs) DeepCopyInto(out *WorkerObservabilityLogs) {
	*out = *in
	if in.InvocationLogs != nil {
		in, out := &in.InvocationLogs, &out.InvocationLogs
		*out = new(bool)
		**out = **in
	}
	if in.HeadSamplingRate != nil {
		in, out := &in.HeadSamplingRate, &out.HeadSamplingRate
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerObservabilityLogs.
func (in *WorkerObservabilityLogs) DeepCopy() *WorkerObservabilityLogs {
	if in == nil {
		return nil
	}
	out := new(WorkerObservabilityLogs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerScript) DeepCopyInto(out *WorkerScript) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerScript.
func (in *WorkerScript) DeepCopy() *WorkerScript {
	if in == nil {
		return nil
	}
	out := new(WorkerScript)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkerScript) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerScriptList) DeepCopyInto(out *WorkerScriptList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkerScript, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerScriptList.
func (in *WorkerScriptList) DeepCopy() *WorkerScriptList {
	if in == nil {
		return nil
	}
	out := new(WorkerScriptList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkerScriptList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerScriptObservation) DeepCopyInto(out *WorkerScriptObservation) {
	*out = *in
	if in.Handlers != nil {
		in, out := &in.Handlers, &out.Handlers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CompatibilityFlags != nil {
		in, out := &in.CompatibilityFlags, &out.CompatibilityFlags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Logpush != nil {
		in, out := &in.Logpush, &out.Logpush
		*out = new(bool)
		**out = **in
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]WorkerBindingObservation, len(*in))
		copy(*out, *in)
	}
	if in.Subdomain != nil {
		in, out := &in.Subdomain, &out.Subdomain
		*out = new(WorkerSubdomainObservation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerScriptObservation.
func (in *WorkerScriptObservation) DeepCopy() *WorkerScriptObservation {
	if in == nil {
		return nil
	}
	out := new(WorkerScriptObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerScriptParameters) DeepCopyInto(out *WorkerScriptParameters) {
	*out = *in
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make(map[string]WorkerModule, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(WorkerSourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.CompatibilityFlags != nil {
		in, out := &in.CompatibilityFlags, &out.CompatibilityFlags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]WorkerBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(WorkerObservability)
		(*in).DeepCopyInto(*out)
	}
	if in.Logpush != nil {
		in, out := &in.Logpush, &out.Logpush
		*out = new(bool)
		**out = **in
	}
	if in.WorkersDev != nil {
		in, out := &in.WorkersDev, &out.WorkersDev
		*out = new(WorkersDev)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerScriptParameters.
func (in *WorkerScriptParameters) DeepCopy() *WorkerScriptParameters {
	if in == nil {
		return nil
	}
	out := new(WorkerScriptParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerScriptSpec) DeepCopyInto(out *WorkerScriptSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.ForProvider != nil {
		in, out := &in.ForProvider, &out.ForProvider
		*out = new(WorkerScriptParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerScriptSpec.
func (in *WorkerScriptSpec) DeepCopy() *WorkerScriptSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerScriptSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerScriptStatus) DeepCopyInto(out *WorkerScriptStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerScriptStatus.
func (in *WorkerScriptStatus) DeepCopy() *WorkerScriptStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerScriptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerSourceRef) DeepCopyInto(out *WorkerSourceRef) {
	*out = *in
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerSourceRef.
func (in *WorkerSourceRef) DeepCopy() *WorkerSourceRef {
	if in == nil {
		return nil
	}
	out := new(WorkerSourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerSubdomainObservation) DeepCopyInto(out *WorkerSubdomainObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerSubdomainObservation.
func (in *WorkerSubdomainObservation) DeepCopy() *WorkerSubdomainObservation {
	if in == nil {
		return nil
	}
	out := new(WorkerSubdomainObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkersDev) DeepCopyInto(out *WorkersDev) {
	*out = *in
	if in.PreviewsEnabled != nil {
		in, out := &in.PreviewsEnabled, &out.PreviewsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkersDev.
func (in *WorkersDev) DeepCopy() *WorkersDev {
	if in == nil {
		return nil
	}
	out := new(WorkersDev)
	in.DeepCopyInto(out)
	return out
}
