// Package apivalidation holds the envtest tests of the CRDs' server-side validation: the
// OpenAPI schema (enums, patterns, lengths), the CEL x-kubernetes-validations (required and
// mutually exclusive fields, immutable fields) and the kubectl names (short names,
// categories). The tests create and update objects against a real kube-apiserver with every
// CRD from config/crd/bases; no controller runs, so status is written by the tests.
//
// The rules themselves are documented in docs/api-reference.md (generated by hack/apidocs).
package apivalidation
